export const meta = {
  name: 'codebase-audit',
  description:
    'Budgeted, resumable codebase audit: a map step partitions the scope into per-domain scanner manifests, then every domain scans concurrently (no barrier) under ONE shared token budget, a single fresh-checker adversarial-verify barrier re-scores certainty over the whole finding set (no producer self-grading; one top-tier pass per audit, not per domain), an aggregate barrier dedups + correlates + groups, and a final fan-out routes the grouped findings to the run objective — filing one issue per group via issue-writer, OR writing them to ./audit/{timestamp}/ via artifact-writer — always plus a report summary. Drives the checker + issue-writer + artifact-writer agents via agentType (NOT workflow()) so the one Workflow nesting level stays free; the harness owns orchestration only and never edits code.',
  phases: [
    { title: 'Map', detail: 'partition scope into per-domain scanner manifests; discover check-* skills + project audit agents' },
    { title: 'Scan', detail: 'one checker scan per domain (patterns.sh prescan + heuristic + judgment), fanned without a barrier' },
    { title: 'Verify', detail: 'barrier: one fresh checker adversarially re-scores + refutes the full cross-domain finding set (one top-tier pass, not per domain)' },
    { title: 'Aggregate', detail: 'barrier: dedup, cross-scanner correlation, severity filter, group into issue payloads' },
    { title: 'File', detail: 'route by objective: parallel issue-writer fan-out (dedupe-before-create) OR artifact-writer file output; plus the report summary' },
  ],
}

// ---------------------------------------------------------------------------
// @generated — DO NOT EDIT THIS FILE. Edit the fragments in workflow.src/ and
// run `just gen-workflow-js` (#806).
//
// This artifact is the byte concatenation of workflow.src/'s fragments in the
// order its manifest.txt lists. An edit made here is overwritten by the next
// regeneration, and until then tests/lint-workflow-js-generated.sh fails the
// tree as stale. To change something, find the fragment that owns it — the
// manifest annotates each one — edit there, and regenerate.
//
// The build step exists because the Workflow engine parses a workflow.js as a
// SCRIPT, not a module, so sibling modules are impossible (every import
// spelling fails at parse — probed three ways in #712). Concatenation needs no
// module system, so the artifact the engine executes contains no import even
// though it was assembled from nine files. The artifact stays committed because
// `claude plugin install` copies plugins/ as-is with no build hook. Full
// rationale: bin/generate-workflow-js.mjs.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Input (passed verbatim as the global `args`) — the SKILL Parameters:
//   {
//     scope?:             string,   // dir / glob to limit the scan (default: whole repo)
//     categories?:        string[], // scanner/domain names to run (default: all discovered)
//     depth?:             'quick' | 'standard' | 'deep',   // default 'standard'
//     severityThreshold?: 'critical' | 'high' | 'medium' | 'low',  // default 'medium'
//     output?:            'issues' | 'files',  // objective: file in tracker, or write ./audit files
//     writeReport?:       boolean,  // default true — also persist the report summary md
//     timestamp?:         string,   // run stamp for ./audit paths (SKILL layer supplies it; engine has no Date)
//     auditDir?:          string,   // default './audit' — root for file artifacts
//   }
//
// The `output` objective and `timestamp` are resolved in the SKILL orchestration
// layer BEFORE this harness is invoked: the sandboxed JS engine cannot call
// AskUserQuestion (to ask the objective per run) or Date (to stamp the run), so
// both arrive as args. The harness is defensive — a missing/invalid `output`
// coerces to 'files' (never mutates a tracker unprompted) and a missing
// `timestamp` falls back to a fixed literal so paths are still well-formed.
//
// Returns:
//   { scanner:'codebase-audit', output, report_path, platform, scanned_domains,
//     totals, report_markdown, issues:[{action,url,title,reason}],
//     artifacts:{action,out_dir,files_written,report_path,reason}|null,
//     acknowledged, summary{…, dropped_groups}, budget_exhausted, scan_failure }
//
// Nesting: this harness drives the `checker`, `issue-writer`, and
// `artifact-writer` agents via `agentType` (NOT `workflow()`), so the one
// allowed Workflow nesting level stays free and ONE shared token budget spans
// every domain scan + verify. The harness runs in the sandboxed JS engine (no
// filesystem / shell / git), so ALL file-tree mapping, `patterns.sh` prescan,
// `gh`/`glab` calls, and `./audit` file writes live inside the agents (which
// have Bash / Write) and are driven here only by discriminated mode. Review/scan
// is read-only: the checker never edits, commits, files issues, or writes
// artifacts — only the issue-writer creates issues, and only the artifact-writer
// writes files.
//
// Single-file by necessity (NOT by accident): the Workflow engine loads ONE
// self-contained inline script with NO module system — `import`/`require` are
// unavailable, and there is no filesystem to read sibling sources from. So the
// schemas, injection-hardening utils, prompt builders, and orchestration loop
// CANNOT be split into importable modules (`schemas.js`, `prompt-utils.js`, …);
// they are inlined here deliberately, the same reason `BUDGET_FLOOR` is
// copy-duplicated across all six harnesses (see tests/lint-skills-agents.sh).
// The sections below are kept sharply banner-delimited so each concern is
// independently readable within the one required file. Do not re-file this as a
// "god module — extract modules" finding: the extraction target does not exist
// in this runtime.
// ---------------------------------------------------------------------------

