#!/usr/bin/env bash
# Freshness gate for the generated workflow.js harnesses (#806).
#
# The enrolled harnesses (bin/generate-workflow-js.mjs's ENROLLED list) are
# generated by concatenating the ordered fragments in their `workflow.src/`
# sibling directory. Both the fragments AND the generated artifact are
# committed, because `claude plugin install` copies plugins/ as-is and there is
# no build hook anywhere in the install path — the generated bytes are what
# ships.
#
# WHY THE GATE CANNOT BE PR-TIED. The obvious cheaper design is to regenerate on
# PR push and skip a local check. That fails on this repo's actual usage: the
# ship-issue harness runs on EVERY /workflow:ship-issue review cycle, including
# the many local runs that never open a PR. Under a PR-tied generator, a
# fragment edit would leave the artifact stale and the next local review would
# silently execute the OLD bytes — a review that reports on code that is not the
# code being reviewed, with nothing anywhere saying so. Checking on every
# `just test` makes that state fail loudly instead, locally and in CI.
#
# This is the same posture as the SHA-pinned-actions rule and the single-source
# ruff pin: when two things must agree and one is generated, pin the agreement
# with a gate rather than trusting review to notice.
#
# The gate delegates entirely to `generate-workflow-js.mjs --check`, which also
# enforces the manifest contract in both directions (a listed fragment missing
# on disk, and an unlisted fragment sitting in the source dir). Re-implementing
# either check here would be a second copy of a rule that must agree with the
# generator — exactly the duplication the manifest exists to avoid.
#
# Runner resolution and the skip sentinel follow lint-python.sh (#538): an
# absent node exits 77 so run-all.sh renders `[SKIP] … did not run` rather than
# `[ok]`. A silent skip is indistinguishable from a pass, which is how a gate
# sits inert unnoticed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=tests/lib/harness.sh
source "$SCRIPT_DIR/lib/harness.sh"

test_suite "Generated workflow.js freshness"

# Reserved exit code meaning "this gate did NOT run" (autotools SKIP convention).
SKIP_EXIT_CODE=77

GENERATOR="$REPO_ROOT/bin/generate-workflow-js.mjs"

# The generator is committed alongside this gate, so its absence is a broken
# tree rather than an unavailable optional tool — fail, do not skip. Run as a
# real assertion so the failure is counted and reported like any other.
test_generator_exists() {
    assert_file_exists "$GENERATOR" "bin/generate-workflow-js.mjs is present"
}
run_test test_generator_exists "The generator script exists"

if [ ! -f "$GENERATOR" ]; then
    generate_report
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    skip_test "GATE DID NOT RUN — node not on PATH (install node to check generated harnesses)"
    generate_report
    exit "$SKIP_EXIT_CODE"
fi

# Every enrolled artifact matches its fragments.
#
# On failure the generator's own stderr is printed: it names the stale artifact
# and the remedy (`just gen-workflow-js`), which is more useful than anything
# this gate could restate — and keeping the wording in ONE place means the
# instruction cannot drift from the command that actually regenerates.
test_generated_harnesses_are_fresh() {
    local out rc=0
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?

    if [ "$rc" -ne 0 ]; then
        command printf '%s\n' "$out"
    fi
    assert_equals "0" "$rc" \
        "every enrolled workflow.js matches its workflow.src/ fragments"
}

# NON-VACUITY FLOOR. `--check` exits 0 both when every artifact is fresh AND, if
# the ENROLLED list were ever emptied or a resolution bug made it select nothing,
# when it checked NOTHING at all. The two are indistinguishable by exit code
# alone, and the second is how this gate would sit green while covering no file.
# Pin that it actually reported on the harnesses by counting its `ok` lines.
test_check_actually_covered_harnesses() {
    local out rc=0 count
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    [ "$rc" -eq 0 ] || {
        skip_test "coverage floor not measurable — the freshness check itself failed above"
        return 0
    }

    count="$(command printf '%s\n' "$out" | command grep -c '^ok  ' || true)"
    assert_true "[ \"$count\" -ge 2 ]" \
        "--check reported on at least the two enrolled harnesses (got $count)"
}

# The gate's teeth, proven rather than assumed: a fragment edited without
# regenerating MUST fail. Exercised against a COPY of the tree so the working
# tree is never mutated — a gate that dirties the repo to test itself would be
# caught by the drift check two steps later, and worse, a crash mid-test would
# leave a corrupted fragment behind.
#
# This is the mutation the acceptance criteria asks for (#806 AC4), run every
# time rather than once by hand: without it, `--check` returning 0 on a fresh
# tree is equally consistent with a comparison that can never fail.
test_stale_artifact_is_detected() {
    local sandbox rc=0 out
    sandbox="$(command mktemp -d 2>/dev/null)" || {
        skip_test "mktemp unavailable — cannot mutate in a sandbox"
        return 0
    }
    # shellcheck disable=SC2064  # expand $sandbox now, not at trap time
    trap "command rm -rf '$sandbox'" RETURN

    local frag_dir="$sandbox/plugins/workflow/skills/ship-issue"
    command mkdir -p "$sandbox/bin" "$frag_dir"
    command cp "$GENERATOR" "$sandbox/bin/"
    command cp -R "$REPO_ROOT/plugins/workflow/skills/ship-issue/workflow.src" "$frag_dir/"
    command cp "$REPO_ROOT/plugins/workflow/skills/ship-issue/workflow.js" "$frag_dir/"

    # Baseline: the copied tree is fresh, so --check passes. Without this the
    # mutation below could "fail" for an unrelated reason (a bad copy, a missing
    # path) and still read as the gate working.
    command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue >/dev/null 2>&1 || rc=$?
    assert_equals "0" "$rc" "sandbox baseline: the copied tree checks clean before mutation"

    # Mutate a fragment WITHOUT regenerating — the exact stale state the gate
    # exists to catch.
    command printf '\n// stale-marker\n' >>"$frag_dir/workflow.src/80-orchestration.js"

    rc=0
    out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue 2>&1)" || rc=$?
    assert_true "[ $rc -ne 0 ]" "an unregenerated fragment edit fails --check"
    assert_contains "$out" "STALE" "the failure names the artifact as stale"

    # And regenerating clears it — proving the failure was staleness, not the
    # sandbox being permanently broken by the edit.
    command node "$sandbox/bin/generate-workflow-js.mjs" ship-issue >/dev/null 2>&1
    rc=0
    command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue >/dev/null 2>&1 || rc=$?
    assert_equals "0" "$rc" "regenerating after the fragment edit restores a clean check"
}

# The manifest contract, both directions (#806 AC1). Same sandbox discipline.
#
# The unlisted-on-disk direction is the one that matters most and is easiest to
# omit: a fragment nobody listed is a file an author edits believing it ships,
# while the artifact contains none of its bytes. A glob-driven generator cannot
# detect that state at all, which is why the manifest is explicit.
test_manifest_fails_in_both_directions() {
    local sandbox rc out
    sandbox="$(command mktemp -d 2>/dev/null)" || {
        skip_test "mktemp unavailable — cannot mutate in a sandbox"
        return 0
    }
    # shellcheck disable=SC2064  # expand $sandbox now, not at trap time
    trap "command rm -rf '$sandbox'" RETURN

    local frag_dir="$sandbox/plugins/workflow/skills/ship-issue"
    command mkdir -p "$sandbox/bin" "$frag_dir"
    command cp "$GENERATOR" "$sandbox/bin/"
    command cp -R "$REPO_ROOT/plugins/workflow/skills/ship-issue/workflow.src" "$frag_dir/"
    command cp "$REPO_ROOT/plugins/workflow/skills/ship-issue/workflow.js" "$frag_dir/"

    # Direction 1 — an unlisted fragment appears on disk.
    command printf '// stray\n' >"$frag_dir/workflow.src/99-stray.js"
    rc=0
    out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue 2>&1)" || rc=$?
    assert_true "[ $rc -ne 0 ]" "an unlisted fragment on disk fails"
    assert_contains "$out" "unlisted" "the failure names the unlisted fragment"
    command rm -f "$frag_dir/workflow.src/99-stray.js"

    # Direction 2 — a listed fragment goes missing.
    command mv "$frag_dir/workflow.src/30-dimensions.js" "$sandbox/30-dimensions.js.bak"
    rc=0
    out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue 2>&1)" || rc=$?
    assert_true "[ $rc -ne 0 ]" "a listed-but-missing fragment fails"
    assert_contains "$out" "missing on disk" "the failure names the missing fragment"
}

run_test test_generated_harnesses_are_fresh "Every enrolled workflow.js is fresh w.r.t. its fragments"
run_test test_check_actually_covered_harnesses "--check covered the enrolled harnesses (non-vacuity floor)"
run_test test_stale_artifact_is_detected "A stale artifact FAILS --check (gate proven by mutation)"
run_test test_manifest_fails_in_both_directions "Manifest mismatch fails in BOTH directions"

generate_report
