#!/usr/bin/env bash
# Freshness gate for the generated workflow.js harnesses (#806).
#
# The enrolled harnesses (bin/generate-workflow-js.mjs's ENROLLED list) are
# generated by concatenating the ordered fragments in their `workflow.src/`
# sibling directory. Both the fragments AND the generated artifact are
# committed, because `claude plugin install` copies plugins/ as-is and there is
# no build hook anywhere in the install path — the generated bytes are what
# ships.
#
# WHY THE GATE CANNOT BE PR-TIED. The obvious cheaper design is to regenerate on
# PR push and skip a local check. That fails on this repo's actual usage: the
# ship-issue harness runs on EVERY /workflow:ship-issue review cycle, including
# the many local runs that never open a PR. Under a PR-tied generator, a
# fragment edit would leave the artifact stale and the next local review would
# silently execute the OLD bytes — a review that reports on code that is not the
# code being reviewed, with nothing anywhere saying so. Checking on every
# `just test` makes that state fail loudly instead, locally and in CI.
#
# This is the same posture as the SHA-pinned-actions rule and the single-source
# ruff pin: when two things must agree and one is generated, pin the agreement
# with a gate rather than trusting review to notice.
#
# The gate delegates entirely to `generate-workflow-js.mjs --check`, which also
# enforces the manifest contract in both directions (a listed fragment missing
# on disk, and an unlisted fragment sitting in the source dir). Re-implementing
# either check here would be a second copy of a rule that must agree with the
# generator — exactly the duplication the manifest exists to avoid.
#
# Runner resolution and the skip sentinel follow lint-python.sh (#538): an
# absent node exits 77 so run-all.sh renders `[SKIP] … did not run` rather than
# `[ok]`. A silent skip is indistinguishable from a pass, which is how a gate
# sits inert unnoticed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=tests/lib/harness.sh
source "$SCRIPT_DIR/lib/harness.sh"

test_suite "Generated workflow.js freshness"

# Reserved exit code meaning "this gate did NOT run" (autotools SKIP convention).
SKIP_EXIT_CODE=77

GENERATOR="$REPO_ROOT/bin/generate-workflow-js.mjs"

# The enrolled harnesses' plugin-relative directories, mirroring the generator's
# own ENROLLED list. Space-separated rather than an array: bash 3.2 is the
# portability target and this repo bans bash-4 constructs.
#
# This IS a second copy of the enrollment list, and a deliberate one: the tests
# below mutate a harness's files, which requires knowing its path on disk, and
# the generator exposes no way to enumerate itself from shell. The
# non-vacuity floor above is what keeps the copy honest — it asserts `--check`
# reported on at least as many harnesses as are listed here, so a harness
# enrolled in the generator but missing from this list makes the count check
# fail rather than silently going unmutated.
ENROLLED_DIRS="plugins/workflow/skills/ship-issue plugins/review-audit/skills/codebase-audit"

# The generator is committed alongside this gate, so its absence is a broken
# tree rather than an unavailable optional tool — fail, do not skip. Run as a
# real assertion so the failure is counted and reported like any other.
test_generator_exists() {
    assert_file_exists "$GENERATOR" "bin/generate-workflow-js.mjs is present"
}
run_test test_generator_exists "The generator script exists"

if [ ! -f "$GENERATOR" ]; then
    generate_report
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    skip_test "GATE DID NOT RUN — node not on PATH (install node to check generated harnesses)"
    generate_report
    exit "$SKIP_EXIT_CODE"
fi

# Every enrolled artifact matches its fragments.
#
# On failure the generator's own stderr is printed: it names the stale artifact
# and the remedy (`just gen-workflow-js`), which is more useful than anything
# this gate could restate — and keeping the wording in ONE place means the
# instruction cannot drift from the command that actually regenerates.
test_generated_harnesses_are_fresh() {
    local out rc=0
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?

    if [ "$rc" -ne 0 ]; then
        command printf '%s\n' "$out"
    fi
    assert_equals "0" "$rc" \
        "every enrolled workflow.js matches its workflow.src/ fragments"
}

# NON-VACUITY FLOOR. `--check` exits 0 both when every artifact is fresh AND, if
# the ENROLLED list were ever emptied or a resolution bug made it select nothing,
# when it checked NOTHING at all. The two are indistinguishable by exit code
# alone, and the second is how this gate would sit green while covering no file.
# Pin that it actually reported on the harnesses by counting its `ok` lines.
test_check_actually_covered_harnesses() {
    local out rc=0 count
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    [ "$rc" -eq 0 ] || {
        skip_test "coverage floor not measurable — the freshness check itself failed above"
        return 0
    }

    count="$(command printf '%s\n' "$out" | command grep -c '^ok  ' || true)"

    # Compare against ENROLLED_DIRS rather than a hardcoded number, so this
    # doubles as the drift guard on that list: enroll a harness in the generator
    # without adding it here and the expectation stays too low; add it here
    # without enrolling it and the count falls short. Either way someone is told.
    local expected=0 _d
    for _d in $ENROLLED_DIRS; do expected=$((expected + 1)); done

    assert_true "[ \"$count\" -ge \"$expected\" ]" \
        "--check reported on every enrolled harness (got $count, expected >= $expected)"
}

# Copy one enrolled harness (artifact + fragments + the generator) into a fresh
# temp tree and echo its path, so the mutation tests below can corrupt a real
# harness layout without touching the working tree. A gate that dirties the repo
# to prove itself would trip the drift check two steps later, and a crash
# mid-test would leave a mangled fragment behind.
#
# Echoes nothing and returns 1 when mktemp is unavailable, so each caller can
# skip rather than fail. The caller owns the RETURN trap that removes the
# sandbox: a trap set here would fire when THIS function returns, deleting the
# tree before the test ever used it.
#
# $1 = the harness's plugin-relative directory (e.g. plugins/workflow/skills/ship-issue).
make_harness_sandbox() {
    local harness_dir="$1" sandbox frag_dir
    sandbox="$(command mktemp -d 2>/dev/null)" || return 1

    frag_dir="$sandbox/$harness_dir"
    command mkdir -p "$sandbox/bin" "$frag_dir"
    command cp "$GENERATOR" "$sandbox/bin/"
    command cp -R "$REPO_ROOT/$harness_dir/workflow.src" "$frag_dir/"
    command cp "$REPO_ROOT/$harness_dir/workflow.js" "$frag_dir/"

    command printf '%s' "$sandbox"
}

# The gate's teeth, proven rather than assumed: a fragment edited without
# regenerating MUST fail.
#
# This is the mutation the acceptance criteria asks for (#806 AC4), run every
# time rather than once by hand: without it, `--check` returning 0 on a fresh
# tree is equally consistent with a comparison that can never fail.
#
# Runs against BOTH enrolled harnesses. Proving it on one and assuming the other
# would leave the second harness's protection asserted rather than demonstrated
# — and the two differ in exactly the way that could matter (different fragment
# counts, different manifests, different plugins).
test_stale_artifact_is_detected() {
    local harness name sandbox frag_dir rc out
    for harness in $ENROLLED_DIRS; do
        name="${harness##*/}"
        sandbox="$(make_harness_sandbox "$harness")" || {
            skip_test "mktemp unavailable — cannot mutate in a sandbox"
            return 0
        }
        frag_dir="$sandbox/$harness"

        # Baseline: the copied tree is fresh, so --check passes. Without this the
        # mutation below could "fail" for an unrelated reason (a bad copy, a
        # missing path) and still read as the gate working.
        rc=0
        command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" >/dev/null 2>&1 || rc=$?
        assert_equals "0" "$rc" "$name sandbox baseline: the copy checks clean before mutation"

        # Mutate the LAST fragment (per the manifest) without regenerating — the
        # exact stale state the gate exists to catch. Reading the name from the
        # manifest keeps this working if a fragment is ever renamed.
        local last_frag
        last_frag="$(command sed -e 's/#.*$//' -e 's/[[:space:]]*$//' \
            "$frag_dir/workflow.src/manifest.txt" | command grep -E '\.js$' | command tail -1)"
        command printf '\n// stale-marker\n' >>"$frag_dir/workflow.src/$last_frag"

        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_true "[ $rc -ne 0 ]" "$name: an unregenerated fragment edit fails --check"
        assert_contains "$out" "STALE" "$name: the failure names the artifact as stale"

        # And regenerating clears it — proving the failure was staleness, not the
        # sandbox being permanently broken by the edit.
        command node "$sandbox/bin/generate-workflow-js.mjs" "$name" >/dev/null 2>&1
        rc=0
        command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" >/dev/null 2>&1 || rc=$?
        assert_equals "0" "$rc" "$name: regenerating after the edit restores a clean check"

        command rm -rf "$sandbox"
    done
}

# The manifest contract, in every direction it can be violated (#806 AC1), for
# BOTH enrolled harnesses.
#
# The unlisted-on-disk direction is the one that matters most and is easiest to
# omit: a fragment nobody listed is a file an author edits believing it ships,
# while the artifact contains none of its bytes. A glob-driven generator cannot
# detect that state at all, which is why the manifest is explicit.
test_manifest_fails_in_every_direction() {
    local harness name sandbox frag_dir rc out first_frag
    for harness in $ENROLLED_DIRS; do
        name="${harness##*/}"
        sandbox="$(make_harness_sandbox "$harness")" || {
            skip_test "mktemp unavailable — cannot mutate in a sandbox"
            return 0
        }
        frag_dir="$sandbox/$harness/workflow.src"

        # Direction 1 — an unlisted fragment appears on disk.
        command printf '// stray\n' >"$frag_dir/99-stray.js"
        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_true "[ $rc -ne 0 ]" "$name: an unlisted fragment on disk fails"
        assert_contains "$out" "unlisted" "$name: the failure names the unlisted fragment"
        command rm -f "$frag_dir/99-stray.js"

        first_frag="$(command sed -e 's/#.*$//' -e 's/[[:space:]]*$//' \
            "$frag_dir/manifest.txt" | command grep -E '\.js$' | command head -1)"

        # Direction 2 — a listed fragment goes missing.
        command mv "$frag_dir/$first_frag" "$sandbox/$first_frag.bak"
        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_true "[ $rc -ne 0 ]" "$name: a listed-but-missing fragment fails"
        assert_contains "$out" "missing on disk" "$name: the failure names the missing fragment"
        command mv "$sandbox/$first_frag.bak" "$frag_dir/$first_frag"

        # Direction 3 — the same fragment listed twice. Without this branch the
        # generator would silently CONCATENATE those bytes twice, producing an
        # artifact that is internally consistent with its manifest and therefore
        # invisible to the freshness comparison.
        command printf '%s\n' "$first_frag" >>"$frag_dir/manifest.txt"
        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_true "[ $rc -ne 0 ]" "$name: a duplicate manifest entry fails"
        assert_contains "$out" "listed more than once" "$name: the failure names the duplicate"

        command rm -rf "$sandbox"
    done
}

# An empty or comment-only manifest must be REFUSED, not rendered.
#
# This is the generator's own vacuity guard, and it is exactly the failure this
# gate's non-vacuity floor exists to prevent one level up: an empty manifest
# renders an empty artifact, and `--check` comparing empty against an equally
# empty file would report a clean pass having asserted nothing at all. The guard
# is only worth having if it fires, so fire it.
test_empty_manifest_is_refused() {
    local sandbox frag_dir rc out
    sandbox="$(make_harness_sandbox "plugins/workflow/skills/ship-issue")" || {
        skip_test "mktemp unavailable — cannot mutate in a sandbox"
        return 0
    }
    # shellcheck disable=SC2064  # expand $sandbox now, not at trap time
    trap "command rm -rf '$sandbox'" RETURN
    frag_dir="$sandbox/plugins/workflow/skills/ship-issue/workflow.src"

    # Comment-only, not zero-byte: this proves the guard keys off what the
    # manifest PARSES to, not merely off file size. A zero-byte file alone would
    # leave the comment-stripping path untested.
    command printf '# every line here is a comment\n#\n\n' >"$frag_dir/manifest.txt"

    rc=0
    out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check ship-issue 2>&1)" || rc=$?
    assert_true "[ $rc -ne 0 ]" "a comment-only manifest fails rather than rendering empty"
    assert_contains "$out" "lists no fragments" "the failure says the manifest lists no fragments"
}

# CLI argument handling: both accepted spellings resolve, and every rejected
# input exits 2 rather than silently selecting nothing.
#
# The "selects nothing" case is why this matters beyond tidiness — a resolution
# bug that matched zero harnesses would make `--check` iterate an empty list and
# exit 0, i.e. report success having checked no file. The generator guards that
# with `matches.length !== 1`; this proves the guard fires.
test_cli_argument_handling() {
    local rc out

    # The full artifact-path spelling resolves to the same harness as the short
    # directory-name form used everywhere else in this file.
    rc=0
    out="$(command node "$GENERATOR" --check \
        "plugins/workflow/skills/ship-issue/workflow.js" 2>&1)" || rc=$?
    assert_equals "0" "$rc" "the full artifact-path spelling resolves"
    assert_contains "$out" "ship-issue/workflow.js" "it checked the harness it named"

    # An unknown harness is a usage error, not an empty no-op run.
    rc=0
    out="$(command node "$GENERATOR" --check not-a-harness 2>&1)" || rc=$?
    assert_equals "2" "$rc" "an unknown harness name exits 2"
    assert_contains "$out" "not an enrolled harness" "the failure names the bad argument"

    # An unknown flag likewise, rather than being read as a harness name.
    rc=0
    out="$(command node "$GENERATOR" --bogus-flag 2>&1)" || rc=$?
    assert_equals "2" "$rc" "an unknown flag exits 2"
    assert_contains "$out" "unknown flag" "the failure names the bad flag"
}

# --- The #586-prelude coexistence rule (#811) -------------------------------
#
# #811 settled that a shared cross-harness prelude (#586) does NOT ride on this
# generator: `srcDirFor` is `dirname(artifact)/workflow.src`, so a fragment is
# bound to one harness by construction, and the artifact still cannot `import`
# (#712). The one genuine interaction is how a prelude reaches an ENROLLED
# harness — as a listed FRAGMENT, never as a banner region written into the
# artifact, which this generator would overwrite on its next run.
#
# The two tests below are the teeth. The decision lives in dev-core's
# workflow-authoring skill, addressed by CONTRACT ID rather than by heading or
# sentence: an id fails loud when missing or duplicated, where a prose anchor
# would silently re-anchor (or yield an empty region every assert_contains then
# passes against).
# shellcheck disable=SC2034  # read by extract_contract in the sourced harness
CONTRACT_SEARCH_ROOT="$REPO_ROOT/plugins"

# The decision is recorded, and the recording still carries its operative
# instructions. assert_contract_carries supplies the tamper half — stripping the
# asserted token must demonstrably change the region — so none of this can pass
# vacuously against prose that no longer says it.
#
# Only OPERATIVE tokens are asserted (what a reader must obey), never the
# rationale sentences, which must stay free to be reworded.
test_coexistence_contract_recorded() {
    local region
    region="$(extract_contract prelude-generator-coexistence)"

    assert_contract_carries prelude-generator-coexistence "$region" 'as a fragment' \
        "prelude coexistence"
    assert_contract_carries prelude-generator-coexistence "$region" 'manifest.txt' \
        "prelude coexistence"
    assert_contract_carries prelude-generator-coexistence "$region" 'never' \
        "prelude coexistence"
}

# The forward guard: prove the failure mode the rule exists to prevent is REAL,
# and that fragment form avoids it.
#
# ARMED BY ITS OWN FIXTURES, NOT BY THE REPO. plugins/lib/prelude.js does not
# exist yet (#586 has not landed), so a guard conditioned on it would be inert
# today — and a conditionally-inert test is exactly the self-skipping shape that
# covers only the arm that happens to be present. Both arms are therefore built
# here in a sandbox and run on every invocation regardless of repo state:
#
#   Arm A — a prelude banner living ONLY in the artifact. The next generation
#           overwrites it, so `--check` reports the artifact STALE. That is the
#           two-tools-one-byte-range collision, demonstrated rather than asserted.
#   Arm B — the same banner living in a LISTED FRAGMENT. It survives generation
#           and `--check` stays clean.
#
# Arm B is what makes Arm A meaningful: without it, a failure in A could be any
# mutation at all rather than specifically the region's placement.
# Runs against BOTH enrolled harnesses, for the reason
# test_stale_artifact_is_detected states above: proving it on one and assuming
# the other leaves the second harness's protection asserted rather than
# demonstrated. That is not hypothetical here — codebase-audit's manifest
# carries its own load-bearing ordering constraint (40-injection-utils.js before
# 50-output-paths.js, a module-load TDZ), so appending a prelude fragment there
# exercises a genuinely different manifest shape than ship-issue's.
test_prelude_region_must_be_a_fragment() {
    local sandbox harness name frag_dir artifact rc out banner
    banner='// ==== GENERATED FROM plugins/lib/prelude.js - DO NOT EDIT ===='

    for harness in $ENROLLED_DIRS; do
        name="${harness##*/}"
        sandbox="$(make_harness_sandbox "$harness")" || {
            skip_test "mktemp unavailable — cannot mutate in a sandbox"
            return 0
        }
        frag_dir="$sandbox/$harness/workflow.src"
        artifact="$sandbox/$harness/workflow.js"

        # The synthetic prelude source #586 would introduce. Present in BOTH arms,
        # so it cannot be what distinguishes them — placement is.
        command mkdir -p "$sandbox/plugins/lib"
        command printf '%s\n' "$banner" >"$sandbox/plugins/lib/prelude.js"

        # Arm A — banner appended to the ARTIFACT only.
        command printf '\n%s\n' "$banner" >>"$artifact"
        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_true "[ $rc -ne 0 ]" \
            "$name: a prelude region written into the ARTIFACT is clobbered (--check fails)"
        assert_contains "$out" "STALE" \
            "$name: the artifact-only prelude region is reported as stale"

        # Restore the artifact, so Arm B starts from a clean tree rather than
        # inheriting Arm A's mutation (which would make a pass unattributable).
        command node "$sandbox/bin/generate-workflow-js.mjs" "$name" >/dev/null 2>&1
        rc=0
        command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" >/dev/null 2>&1 || rc=$?
        assert_equals "0" "$rc" \
            "$name: arm B baseline — the sandbox is clean before the fragment arm"

        # Arm B — the SAME banner, this time as a listed fragment. Appended at the
        # manifest's last entry position so existing ordering constraints (including
        # codebase-audit's TDZ pair) are untouched.
        command printf '%s\n' "$banner" >"$frag_dir/90-prelude.js"
        command printf '90-prelude.js\n' >>"$frag_dir/manifest.txt"
        command node "$sandbox/bin/generate-workflow-js.mjs" "$name" >/dev/null 2>&1
        rc=0
        out="$(command node "$sandbox/bin/generate-workflow-js.mjs" --check "$name" 2>&1)" || rc=$?
        assert_equals "0" "$rc" \
            "$name: the same prelude region AS A FRAGMENT survives generation (--check clean)"

        # And it genuinely reached the artifact — otherwise "clean" would only mean
        # the fragment was ignored, which is the unlisted-fragment failure wearing a
        # passing exit code.
        #
        # The marker must be one the artifact does NOT already carry. `DO NOT EDIT`
        # is the tempting choice and is a TAUTOLOGY: every enrolled artifact opens
        # with an `@generated — DO NOT EDIT THIS FILE` banner, so that assertion
        # passes whether or not a single fragment byte landed (measured — a
        # listed-but-EMPTY fragment kept it green). `plugins/lib/prelude.js` appears
        # nowhere in either real artifact, so it can only come from this fixture.
        assert_file_contains "$artifact" "plugins/lib/prelude.js" \
            "$name: the fragment's prelude bytes are present in the generated artifact"

        command rm -rf "$sandbox"
    done
}

run_test test_generated_harnesses_are_fresh "Every enrolled workflow.js is fresh w.r.t. its fragments"
run_test test_check_actually_covered_harnesses "--check covered the enrolled harnesses (non-vacuity floor)"
run_test test_stale_artifact_is_detected "A stale artifact FAILS --check (both harnesses, by mutation)"
run_test test_manifest_fails_in_every_direction "Manifest mismatch fails every way (both harnesses)"
run_test test_empty_manifest_is_refused "A comment-only manifest is refused, not rendered empty"
run_test test_cli_argument_handling "CLI args: both spellings resolve; bad input exits 2"
run_test test_coexistence_contract_recorded "#586 prelude coexistence decision is recorded (#811)"
run_test test_prelude_region_must_be_a_fragment "A prelude region must be a FRAGMENT, not an artifact banner (#811)"

generate_report
