#!/usr/bin/env bash
# Drift gate for the shared workflow.js prelude (#586).
#
# plugins/lib/prelude.js is the single edit site for the scaffolding that six
# harnesses share. bin/generate-prelude.mjs copies each named section into its
# consumers — as a FRAGMENT for the two harnesses enrolled in
# generate-workflow-js.mjs, and as a banner-delimited REGION for the four that
# are not (#811). Both the source and every generated copy are committed,
# because `claude plugin install` copies plugins/ as-is with no build hook: the
# generated bytes are what ships.
#
# WHY A GATE AND NOT REVIEW. The duplication this replaces was already drifting
# in practice — 753261e (#256) had to touch all six harnesses, 3258263 four.
# `stableStringify` and `dataBlock` build prompt text, so a single copy drifting
# silently breaks the #256 byte-stable prefix cache: nothing fails, no test goes
# red, and the cost shows up only as token burn nobody attributes. That is
# exactly the class of invariant that needs a gate rather than a reviewer.
#
# This gate delegates to `generate-prelude.mjs --check`, which recomputes each
# consumer's expected bytes and diffs them. Re-implementing the comparison here
# would be a second copy of a rule that must agree with the generator — the same
# duplication the prelude exists to eliminate.
#
# RELATIONSHIP TO tests/lint-workflow-js-generated.sh: the two gates own
# DISJOINT byte ranges and compose in series. This one owns
# `plugins/lib/prelude.js -> fragment/region`; that one owns
# `fragments -> artifact`. Neither knows about the other, and neither can be
# weakened by the other's outcome. That separation is the whole reason an
# enrolled harness receives a fragment rather than an in-artifact region.
#
# Runner resolution and the skip sentinel follow lint-python.sh (#538): an
# absent node exits 77 so run-all.sh renders `[SKIP] … did not run` rather than
# `[ok]`. A silent skip is indistinguishable from a pass, which is how a gate
# sits inert unnoticed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=tests/lib/harness.sh
source "$SCRIPT_DIR/lib/harness.sh"

test_suite "Shared workflow.js prelude sync"

# Reserved exit code meaning "this gate did NOT run" (autotools SKIP convention).
SKIP_EXIT_CODE=77

GENERATOR="$REPO_ROOT/bin/generate-prelude.mjs"
SOURCE="$REPO_ROOT/plugins/lib/prelude.js"

# The consumers' generated files, mirroring the generator's own CONSUMERS list.
# Space-separated rather than an array: bash 3.2 is the portability target.
#
# This IS a second copy of the consumer list, and a deliberate one: the mutation
# tests below must know a path on disk, and the generator exposes no way to
# enumerate itself from shell. The non-vacuity floor below keeps the copy honest
# — it asserts `--check` reported on at least as many files as are listed here,
# so a consumer added to the generator but missing here fails the count rather
# than silently going unmutated.
CONSUMER_FILES="plugins/workflow/skills/ship-issue/workflow.src/15-prelude.js \
plugins/review-audit/skills/codebase-audit/workflow.src/15-prelude.js \
plugins/dev-core/agents/code-reviewer/workflow.js \
plugins/workflow/skills/orchestrate/workflow.js \
plugins/workflow/agents/rebase-agent/workflow.js \
plugins/workflow/agents/ci-fixer/workflow.js"

# The generator and the source are committed alongside this gate, so their
# absence is a broken tree rather than an unavailable optional tool — fail, do
# not skip. Run as real assertions so each failure is counted and reported.
test_generator_exists() {
    assert_file_exists "$GENERATOR" "bin/generate-prelude.mjs is present"
}
run_test test_generator_exists "The generator script exists"

test_source_exists() {
    assert_file_exists "$SOURCE" "plugins/lib/prelude.js is present"
}
run_test test_source_exists "The prelude source exists"

if [ ! -f "$GENERATOR" ] || [ ! -f "$SOURCE" ]; then
    generate_report
    exit 1
fi

if ! command -v node >/dev/null 2>&1; then
    skip_test "GATE DID NOT RUN — node not on PATH (install node to check the prelude copies)"
    generate_report
    exit "$SKIP_EXIT_CODE"
fi

# Every consumer's generated bytes match the source.
#
# On failure the generator's own stderr is printed: it names the stale file and
# the remedy (`just gen-prelude`), which is more useful than anything this gate
# could restate — and keeping the wording in ONE place means the instruction
# cannot drift from the command that actually regenerates.
test_prelude_copies_are_fresh() {
    local out rc=0
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?

    if [ "$rc" -ne 0 ]; then
        command printf '%s\n' "$out"
    fi
    assert_equals "0" "$rc" \
        "every prelude copy matches plugins/lib/prelude.js"
}

# NON-VACUITY FLOOR. `--check` exits 0 both when every copy is fresh AND, if the
# CONSUMERS list were emptied or a resolution bug made it select nothing, when it
# checked NOTHING at all. The two are indistinguishable by exit code alone, and
# the second is how this gate would sit green while covering no file. Pin that it
# actually reported on the consumers by counting its `ok` lines.
test_check_actually_covered_consumers() {
    local out rc=0 count
    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    [ "$rc" -eq 0 ] || {
        skip_test "coverage floor not measurable — the freshness check itself failed above"
        return 0
    }

    count="$(command printf '%s\n' "$out" | command grep -c '^ok  ' || true)"

    # Compare against CONSUMER_FILES rather than a hardcoded number, so this
    # doubles as the drift guard on that list.
    local expected=0 _f
    for _f in $CONSUMER_FILES; do expected=$((expected + 1)); done

    assert_equals "$expected" "$count" \
        "--check reported on all $expected prelude consumers"
}

# THE GATE HAS TEETH — REGION ARM. A sync gate that only ever sees synced input
# is a tautology: it would pass identically if `--check` compared nothing. Mutate
# a real consumer's generated bytes and assert the gate NOTICES.
#
# This arm perturbs a banner REGION (a non-enrolled harness). The fragment arm
# below perturbs a FRAGMENT, because the two delivery forms take different code
# paths through the generator (spliceRegion vs renderFragment) and a bug in one
# is invisible to a mutation of the other.
test_drift_detected_in_region() {
    local target="$REPO_ROOT/plugins/workflow/agents/ci-fixer/workflow.js"
    local backup="${TEST_TMPDIR:-/tmp}/prelude-region-backup.$$"
    local out rc=0

    # Snapshot-copy, never `git checkout` for restore: this tree may hold
    # uncommitted work, and reverting to HEAD would delete it.
    command cp "$target" "$backup"

    # Perturb a generated line INSIDE the region.
    command sed 's/^const BUDGET_FLOOR = 40_000$/const BUDGET_FLOOR = 99_000/' \
        "$backup" >"$target"

    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    command cp "$backup" "$target"
    command rm -f "$backup"

    assert_true "[ $rc -ne 0 ]" \
        "a drifted banner region makes --check fail"
    assert_contains "$out" "STALE prelude copy" \
        "the failure names the drift and points at the remedy"
}

# THE GATE HAS TEETH — FRAGMENT ARM. Same property, the other delivery form.
test_drift_detected_in_fragment() {
    local target="$REPO_ROOT/plugins/workflow/skills/ship-issue/workflow.src/15-prelude.js"
    local backup="${TEST_TMPDIR:-/tmp}/prelude-fragment-backup.$$"
    local out rc=0

    command cp "$target" "$backup"
    command sed 's/^const TAIL_FLOOR = 8_000$/const TAIL_FLOOR = 1_000/' \
        "$backup" >"$target"

    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    command cp "$backup" "$target"
    command rm -f "$backup"

    assert_true "[ $rc -ne 0 ]" \
        "a drifted generated fragment makes --check fail"
    assert_contains "$out" "STALE prelude copy" \
        "the failure names the drift and points at the remedy"
}

# A SOURCE edit with no regeneration must fail too — the direction that actually
# happens in practice (someone edits plugins/lib/prelude.js and forgets
# `just gen-prelude`). Distinct from the two arms above, which simulate someone
# editing a generated copy directly.
test_unregenerated_source_edit_fails() {
    local backup="${TEST_TMPDIR:-/tmp}/prelude-source-backup.$$"
    local out rc=0

    command cp "$SOURCE" "$backup"
    command sed 's/^const BUDGET_FLOOR = 40_000$/const BUDGET_FLOOR = 50_000/' \
        "$backup" >"$SOURCE"

    out="$(command node "$GENERATOR" --check 2>&1)" || rc=$?
    command cp "$backup" "$SOURCE"
    command rm -f "$backup"

    assert_true "[ $rc -ne 0 ]" \
        "editing the source without regenerating makes --check fail"
}

# BUDGET_FLOOR HOUSE-VALUE COVERAGE (#586 AC5). This subsumes
# lint-skills-agents.sh's test_workflow_budget_floor_consistent, which asserted
# every harness declares the house floor. That test is retired, so the coverage
# has to land somewhere: with one generated source, the house value is pinned by
# checking the SOURCE once — every consumer is then byte-equal to it by the
# freshness assertion above.
#
# The old test also swept all six harnesses for a declaration. That property is
# preserved differently now: a harness that declared its own BUDGET_FLOOR
# *outside* the generated region would be a second declaration, which is a
# redeclaration SyntaxError caught by lint-skills-agents.sh's `node --check`.
HOUSE_BUDGET_FLOOR="40_000"

test_source_declares_house_budget_floor() {
    local declared
    declared="$(command grep -E '^const BUDGET_FLOOR = ' "$SOURCE" | command head -1)"

    assert_equals "const BUDGET_FLOOR = $HOUSE_BUDGET_FLOOR" "$declared" \
        "the prelude source declares the house budget floor ($HOUSE_BUDGET_FLOOR)"
}

# No harness may declare BUDGET_FLOOR outside the generated region — that is the
# drift the retired test existed to prevent, reachable now only by hand-adding a
# duplicate. Counts declarations per harness and requires exactly one.
test_no_harness_declares_budget_floor_twice() {
    local wf count
    while IFS= read -r wf; do
        [ -n "$wf" ] || continue
        count="$(command grep -c '^const BUDGET_FLOOR = ' "$wf" || true)"
        assert_equals "1" "$count" \
            "$(command basename "$(command dirname "$wf")"): exactly one BUDGET_FLOOR declaration"
    done <<EOF
$(command find "$REPO_ROOT/plugins" -name 'workflow.js' -type f | command sort)
EOF
}

# Copy the prelude source, the generator, and every consumer into a fresh temp
# tree and echo its path, so the WRITE-mode tests below can let the generator
# actually rewrite files without touching the working tree. A gate that dirties
# the repo to prove itself would trip its own freshness check two tests later,
# and a crash mid-test would leave a mangled consumer behind.
#
# Echoes nothing and returns 1 when mktemp is unavailable, so each caller skips
# rather than fails. The caller owns the RETURN trap that removes the sandbox: a
# trap set here would fire when THIS function returns, deleting the tree before
# the test could use it.
make_prelude_sandbox() {
    local sandbox _f
    sandbox="$(command mktemp -d 2>/dev/null)" || return 1

    command mkdir -p "$sandbox/bin" "$sandbox/plugins/lib"
    command cp "$GENERATOR" "$sandbox/bin/"
    command cp "$SOURCE" "$sandbox/plugins/lib/"
    for _f in $CONSUMER_FILES; do
        command mkdir -p "$sandbox/$(command dirname "$_f")"
        command cp "$REPO_ROOT/$_f" "$sandbox/$_f"
    done

    command printf '%s' "$sandbox"
}

# WRITE MODE — the half of main() that `just gen-prelude` actually runs, and
# which every other test here leaves untouched because they all pass --check.
# A regression that wrote the wrong bytes, wrote to the wrong target, or silently
# skipped a write would pass the whole rest of this gate.
#
# Asserts the full round trip: edit the source, regenerate, and the copy tracks
# the edit AND --check goes green again on the sandbox.
test_write_mode_regenerates_copies() {
    local sandbox rc=0 out target
    sandbox="$(make_prelude_sandbox)" || {
        skip_test "write-mode test needs mktemp"
        return 0
    }
    # shellcheck disable=SC2064  # expand $sandbox now, not at trap time
    trap "command rm -rf '$sandbox'" RETURN

    # Edit the SOURCE, then regenerate — the real workflow.
    command sed 's/^const BUDGET_FLOOR = 40_000$/const BUDGET_FLOOR = 41_000/' \
        "$SOURCE" >"$sandbox/plugins/lib/prelude.js"

    out="$(cd "$sandbox" && command node bin/generate-prelude.mjs 2>&1)" || rc=$?
    assert_equals "0" "$rc" "write mode exits 0 on a well-formed tree"

    # A banner-region consumer and a fragment consumer both carry the new value —
    # the two delivery forms take different code paths.
    target="$sandbox/plugins/workflow/agents/ci-fixer/workflow.js"
    assert_file_contains "$target" "const BUDGET_FLOOR = 41_000" \
        "write mode updated the banner-region consumer"

    target="$sandbox/plugins/workflow/skills/ship-issue/workflow.src/15-prelude.js"
    assert_file_contains "$target" "const BUDGET_FLOOR = 41_000" \
        "write mode updated the generated fragment"

    # And the tree it just wrote is self-consistent.
    rc=0
    out="$(cd "$sandbox" && command node bin/generate-prelude.mjs --check 2>&1)" || rc=$?
    assert_equals "0" "$rc" "--check passes on the tree write mode just produced"
}

# IDEMPOTENCY, asserted rather than assumed: a second run must report `unchanged`
# for every consumer and write nothing. Without this, a generator that rewrote
# byte-identical content every time would look correct here but churn mtimes and
# defeat any build caching downstream.
test_write_mode_is_idempotent() {
    local sandbox rc=0 out count expected _f
    sandbox="$(make_prelude_sandbox)" || {
        skip_test "idempotency test needs mktemp"
        return 0
    }
    # shellcheck disable=SC2064
    trap "command rm -rf '$sandbox'" RETURN

    out="$(cd "$sandbox" && command node bin/generate-prelude.mjs 2>&1)" || rc=$?
    assert_equals "0" "$rc" "first write-mode run succeeds"

    rc=0
    out="$(cd "$sandbox" && command node bin/generate-prelude.mjs 2>&1)" || rc=$?
    assert_equals "0" "$rc" "second write-mode run succeeds"

    count="$(command printf '%s\n' "$out" | command grep -c '^unchanged  ' || true)"
    expected=0
    for _f in $CONSUMER_FILES; do expected=$((expected + 1)); done
    assert_equals "$expected" "$count" \
        "a second run reports 'unchanged' for all $expected consumers (no rewrite churn)"
}

# CLI TARGET SELECTION. Naming one consumer must rewrite only that consumer —
# a resolution bug that silently widened the target set would be invisible to
# every whole-tree test above.
test_write_mode_targets_one_consumer() {
    local sandbox rc=0 out other_before other_after
    sandbox="$(make_prelude_sandbox)" || {
        skip_test "target-selection test needs mktemp"
        return 0
    }
    # shellcheck disable=SC2064
    trap "command rm -rf '$sandbox'" RETURN

    command sed 's/^const BUDGET_FLOOR = 40_000$/const BUDGET_FLOOR = 42_000/' \
        "$SOURCE" >"$sandbox/plugins/lib/prelude.js"

    other_before="$(command cat "$sandbox/plugins/workflow/agents/rebase-agent/workflow.js")"

    out="$(cd "$sandbox" && command node bin/generate-prelude.mjs ci-fixer 2>&1)" || rc=$?
    assert_equals "0" "$rc" "write mode accepts a single consumer by directory name"

    assert_file_contains "$sandbox/plugins/workflow/agents/ci-fixer/workflow.js" \
        "const BUDGET_FLOOR = 42_000" \
        "the named consumer was rewritten"

    other_after="$(command cat "$sandbox/plugins/workflow/agents/rebase-agent/workflow.js")"
    assert_equals "$other_before" "$other_after" \
        "an UNNAMED consumer was left untouched"
}

# An unrecognized consumer name is a usage error (exit 2), not a silent no-op.
# A generator that exited 0 having written nothing would let `just gen-prelude
# <typo>` look like it worked.
test_unknown_consumer_is_a_usage_error() {
    local out rc=0
    out="$(command node "$GENERATOR" definitely-not-a-consumer 2>&1)" || rc=$?

    assert_equals "2" "$rc" "an unknown consumer name exits 2"
    assert_contains "$out" "not a prelude consumer" \
        "the error names the problem and lists the valid consumers"
}

run_test test_prelude_copies_are_fresh "Every prelude copy matches the source"
run_test test_check_actually_covered_consumers "--check reported on all consumers (non-vacuity floor)"
run_test test_drift_detected_in_region "Drift guard fires on a perturbed banner region"
run_test test_drift_detected_in_fragment "Drift guard fires on a perturbed generated fragment"
run_test test_unregenerated_source_edit_fails "Drift guard fires on an unregenerated source edit"
run_test test_source_declares_house_budget_floor "The source declares the house BUDGET_FLOOR"
run_test test_no_harness_declares_budget_floor_twice "No harness declares BUDGET_FLOOR twice"
run_test test_write_mode_regenerates_copies "Write mode regenerates both delivery forms"
run_test test_write_mode_is_idempotent "Write mode is idempotent (second run rewrites nothing)"
run_test test_write_mode_targets_one_consumer "Write mode targets only the named consumer"
run_test test_unknown_consumer_is_a_usage_error "An unknown consumer name exits 2, not 0"

generate_report
