#!/usr/bin/env python3
"""check-decomposition — Deterministic Pre-Scan (Python primary implementation).

Sizing + language-aware segmentation. Replaces the production-LOC counting prose
that was duplicated across audit-code-health, audit-architecture and
audit-ai-config (issue #663) with one deterministic implementation, and turns the
result from a line count into an actionable **decomposition seam**.

Python 3.11+ primary implementation behind the language-agnostic TSV contract;
the sibling patterns.sh is the portable bash fallback (it exec's this file when a
python3>=3.11 is present). Both emit byte-identical findings — the parity is
pinned by tests/validate-python-ports.sh and the behavior by
tests/validate-decomposition-detectors.sh. See CLAUDE.md § Key conventions.

Input:  argv[1] = file containing paths to scan (one per line)
Output: TSV to stdout: file<TAB>line<TAB>category<TAB>evidence<TAB>certainty

The 5-column contract is NOT widened. A seam is a per-file SPAN, so `line`
carries the seam START and the end line, unit names, fan-in and proposed target
path are encoded as structured text inside `evidence`:

    src/parser.rs<TAB>412<TAB>decomposition-seam<TAB>seam 412-680: fn parse_* \
family (6 units, fan-in 1 <- parse_entry) -> src/parser/parse.rs<TAB>HIGH

Every other check-* skill and all three parity gates keep the contract they have.
The audit-decomposition agent parses this evidence into line_start/line_end.

Thresholds are env-overridable (DECOMP_*, plus the CLAUDE_MD_*/SKILL_*/AGENT_*/
DOC_* bloat vars inherited from check-ai-config when the bloat table moved here).

Exit codes:
  0 = success (zero or more findings)
  1 = usage error (missing argument) or file list not found
"""

from __future__ import annotations

import fnmatch as _fnmatch
import os
import re
import sys

# Non-source files skipped wholesale. Markdown is deliberately ABSENT: this
# scanner segments prose by heading hierarchy and owns doc-file-bloat.
SKIP_GLOBS = (
    "*.lock",
    "*lock.json",
    "*go.sum",
    "*.txt",
    "*.json",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.cfg",
    "*.conf",
)

# Markers that make a long file legitimate — a generated artifact is not a
# decomposition candidate, and saying so is a finding, not a silent drop.
GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated",
    re.IGNORECASE,
)

# Per-language unit headers. Each maps a language key to the regex that starts a
# TOP-LEVEL unit. Anchored at line start (no leading indent) so nested defs are
# not mistaken for top-level ones — that anchoring is what makes a unit span a
# genuine cut point.
UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?(?:def|class)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "js": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:async[ \t]+)?"
        r"(?:function|class|const|let|var)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    "rs": re.compile(
        r"^(?:pub(?:\([a-z]+\))?[ \t]+)?(?:async[ \t]+)?"
        r"(?:fn|struct|enum|trait|impl|mod)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
    "go": re.compile(r"^(?:func|type|var|const)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "sh": re.compile(
        r"^(?:function[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]*\([ \t]*\)|"
        r"^function[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
}

# Comment-line shapes per language (used for the comment/production split).
COMMENT_RE = {
    "py": re.compile(r"^[ \t]*#"),
    "sh": re.compile(r"^[ \t]*#"),
    "js": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "rs": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "go": re.compile(r"^[ \t]*(?://|/\*|\*)"),
}

# A unit header that marks the unit as TEST code. Replaces the per-language
# exclusion prose the three agents each carried a drifting copy of. Because unit
# SPANS are already computed, exclusion is per-unit and exact rather than the
# "to end of file" approximation the prose specified.
TEST_UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?def[ \t]+test_|^class[ \t]+Test"),
    "js": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    "rs": re.compile(r"^[ \t]*#\[(?:cfg\(test\)|test)\]"),
    "go": re.compile(r"^func[ \t]+(?:Test|Benchmark|Fuzz|Example)"),
    "sh": re.compile(r"^(?:function[ \t]+)?test_[A-Za-z0-9_]*[ \t]*\([ \t]*\)"),
}

# Whole-file test-region markers: everything from the match to EOF is test code.
# Kept for the two cases the prose named that are genuinely region-scoped rather
# than unit-scoped.
TEST_REGION_RE = {
    "py": re.compile(r"^if[ \t]+__name__"),
    "rs": re.compile(r"^[ \t]*#\[cfg\(test\)\]"),
    "sh": re.compile(r"^#[ \t]*-+[ \t]*tests?[ \t]*-+"),
}

# Indent width used to convert leading whitespace into a nesting depth.
NEST_UNIT = {"py": 4, "js": 2, "rs": 4, "go": 4, "sh": 4, "md": 2}

# Blankness and indent are defined by REGEX, not str.strip()/str.lstrip(): the
# latter are unicode-aware (\x0b, \x0c, \x85, NBSP...) while the awk fallback
# under LC_ALL=C is not. Pinning both impls to [ \t] is what keeps the TSV
# byte-identical on a file with exotic whitespace.
BLANK_RE = re.compile(r"^[ \t]*$")
INDENT_RE = re.compile(r"^[ \t]*")
# Identifier tokens for the fan-in scan. A MAXIMAL run is what makes membership
# equivalent to a \bNAME\b regex — and, unlike an escaped alternation, it is
# reproducible verbatim in the awk fallback, so the two impls agree by
# construction rather than by two hand-matched regex dialects.
TOKEN_RE = re.compile(r"[A-Za-z0-9_$]+")

# Noun used in seam evidence, per language.
UNIT_NOUN = {
    "py": "def",
    "js": "function",
    "rs": "fn",
    "go": "func",
    "sh": "function",
    "md": "section",
}

EXT_LANG = {
    "py": "py",
    "js": "js",
    "jsx": "js",
    "mjs": "js",
    "cjs": "js",
    "ts": "js",
    "tsx": "js",
    "rs": "rs",
    "go": "go",
    "sh": "sh",
    "bash": "sh",
    "md": "md",
    "markdown": "md",
}


def _int_env(name: str, default: int) -> int:
    """Read an integer threshold from the environment, falling back to DEFAULT.
    Mirrors _int_env in check-ai-config/patterns.py (and the ${VAR:-N} defaults
    in every patterns.sh) so thresholds.yml values can be passed through by the
    orchestrator without either impl diverging."""
    val = os.environ.get(name, "")
    try:
        return int(val)
    except ValueError:
        return default


def emit(path: str, line_no: int, category: str, evidence: str, certainty: str) -> None:
    """Write one TSV finding row."""
    sys.stdout.write(
        "\t".join((path, str(line_no), category, evidence, certainty)) + "\n"
    )


def _glob(path: str, pattern: str) -> bool:
    """`case "$path" in <pattern>)` — an unanchored shell glob over the full
    path. fnmatchcase's `*` crosses '/', matching bash `case` glob semantics."""
    return _fnmatch.fnmatchcase(path, pattern)


def lang_of(path: str) -> str:
    """Language key from the file extension, or '' when unrecognized (metrics
    only, no segmenter)."""
    if "." not in path:
        return ""
    return EXT_LANG.get(path.rsplit(".", 1)[-1].lower(), "")


def family_prefix(name: str) -> str:
    """The family key a unit name belongs to — the shared stem that makes
    `parse_entry` / `parse_header` / `parse_body` one cluster.

    snake_case splits at the first underscore; camelCase and PascalCase split at
    the first internal uppercase letter. The result is lowercased so `ParseEntry`
    and `parse_entry` land in the same family.
    """
    cut = name.find("_")
    if cut > 0:
        return name[:cut].lower()
    i = 1
    while i < len(name) and not ("A" <= name[i] <= "Z"):
        i += 1
    return name[:i].lower()


def md_slug(text: str) -> str:
    """Markdown heading text -> an identifier-shaped slug so family_prefix()
    applies unchanged ('Install on Linux' -> 'install_on_linux')."""
    out = []
    prev_us = False
    for ch in INDENT_RE.sub("", text.rstrip()).lower():
        if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
            out.append(ch)
            prev_us = False
        elif not prev_us:
            out.append("_")
            prev_us = True
    return "".join(out).strip("_")


class Unit:
    """One top-level declaration: its name, family, header line and span."""

    __slots__ = ("name", "prefix", "start", "end", "is_test", "depth")

    def __init__(self, name: str, start: int, depth: int = 0) -> None:
        self.name = name
        self.prefix = family_prefix(name)
        self.start = start
        self.end = start
        self.is_test = False
        self.depth = depth


def find_units(lines: list[str], lang: str) -> list[Unit]:
    """Top-level units in file order, each spanning from its header line to the
    line before the next header (or EOF).

    For markdown, 'top-level' means the shallowest heading depth present, so a
    doc whose sections are all `##` segments by `##` rather than by a lone `#`
    title."""
    units: list[Unit] = []
    if lang == "md":
        heads: list[tuple[int, int, str]] = []  # (depth, line_no, text)
        fenced = False
        for idx, line in enumerate(lines, start=1):
            if line.startswith("```") or line.startswith("~~~"):
                fenced = not fenced
                continue
            if fenced:
                continue
            m = re.match(r"^(#{1,6})[ \t]+(.*)$", line)
            if m:
                heads.append((len(m.group(1)), idx, m.group(2)))
        if not heads:
            return []
        top = min(h[0] for h in heads)
        for depth, line_no, text in heads:
            if depth == top:
                units.append(Unit(md_slug(text) or "section", line_no, depth))
    else:
        rx = UNIT_RE.get(lang)
        if rx is None:
            return []
        test_rx = TEST_UNIT_RE.get(lang)
        pending_test = False
        for idx, line in enumerate(lines, start=1):
            # An attribute line (Rust #[test]) marks the NEXT unit as test code.
            if lang == "rs" and test_rx is not None and test_rx.search(line):
                pending_test = True
                continue
            m = rx.match(line)
            if not m:
                continue
            name = m.group(1)
            if not name and m.lastindex and m.lastindex >= 2:
                name = m.group(2)
            if not name:
                continue
            u = Unit(name, idx)
            if pending_test:
                u.is_test = True
                pending_test = False
            elif test_rx is not None and lang != "rs" and test_rx.search(line):
                u.is_test = True
            units.append(u)

    for i, u in enumerate(units):
        u.end = units[i + 1].start - 1 if i + 1 < len(units) else len(lines)
    return units


def measure(lines: list[str], lang: str, units: list[Unit]) -> dict:
    """The generic sizing layer: total / blank / comment / test-excluded /
    production LOC, max nesting depth, and top-level unit count."""
    total = len(lines)
    comment_rx = COMMENT_RE.get(lang)
    region_rx = TEST_REGION_RE.get(lang)

    # Lines inside a test unit, or after a whole-file test-region marker.
    test_lines = set()
    for u in units:
        if u.is_test:
            test_lines.update(range(u.start, u.end + 1))
    if region_rx is not None:
        for idx, line in enumerate(lines, start=1):
            if region_rx.search(line):
                test_lines.update(range(idx, total + 1))
                break

    blank = 0
    comment = 0
    test_excluded = 0
    max_depth = 0
    nest_unit = NEST_UNIT.get(lang, 4)
    for idx, line in enumerate(lines, start=1):
        if idx in test_lines:
            test_excluded += 1
            continue
        if BLANK_RE.match(line):
            blank += 1
            continue
        if comment_rx is not None and comment_rx.match(line):
            comment += 1
            continue
        depth = len(INDENT_RE.match(line).group(0)) // nest_unit
        if depth > max_depth:
            max_depth = depth

    production = total - blank - comment - test_excluded
    return {
        "total": total,
        "blank": blank,
        "comment": comment,
        "test_excluded": test_excluded,
        "production": production,
        "max_depth": max_depth,
        "units": len([u for u in units if not u.is_test]),
        "comment_pct": (comment * 100 // total) if total else 0,
    }


class Cluster:
    """A maximal run of CONSECUTIVE same-family units — contiguous by
    construction, which is what makes the span a single mechanical move."""

    __slots__ = ("prefix", "units", "start", "end")

    def __init__(self, prefix: str, units: list[Unit]) -> None:
        self.prefix = prefix
        self.units = units
        self.start = units[0].start
        self.end = units[-1].end


def cluster_units(units: list[Unit]) -> list[Cluster]:
    """Group ADJACENT units sharing a family prefix.

    Adjacency is by unit INDEX, not merely by same-prefix order: a test unit (or
    any other family) sitting between two same-family units breaks the run. That
    matters because the span is meant to be a single mechanical move — a
    `render_*` trio interleaved with eight test functions spans 230 lines that
    cannot be lifted out without dragging the tests along, so it is not a seam.
    """
    clusters: list[Cluster] = []
    run: list[Unit] = []
    last_idx = -2
    for idx, u in enumerate(units):
        if u.is_test:
            continue
        if run and run[-1].prefix == u.prefix and idx == last_idx + 1:
            run.append(u)
        else:
            if run:
                clusters.append(Cluster(run[0].prefix, run))
            run = [u]
        last_idx = idx
    if run:
        clusters.append(Cluster(run[0].prefix, run))
    return clusters


def fan_in(lines: list[str], cluster: Cluster, units: list[Unit]) -> tuple[int, str]:
    """How much of the REST of the file reaches into this cluster.

    Returns (reference count, comma-joined names of the referencing top-level
    units, capped at 3). A low fan-in is the signal that the span is a
    low-coupling cut point — the whole point of naming a seam rather than a size.
    """
    names = set(u.name for u in cluster.units)
    count = 0
    callers: list[str] = []
    for idx, line in enumerate(lines, start=1):
        if cluster.start <= idx <= cluster.end:
            continue
        if not (names & set(TOKEN_RE.findall(line))):
            continue
        count += 1
        for u in units:
            if u.start <= idx <= u.end and u.name not in callers:
                callers.append(u.name)
                break
    callers.sort()
    return count, ", ".join(callers[:3])


def target_path(path: str, prefix: str) -> str:
    """Where the seam should move to: a sibling module named for the family,
    under a directory named for the file it came from."""
    if "/" in path:
        directory, base = path.rsplit("/", 1)
    else:
        directory, base = "", path
    stem, dot, ext = base.rpartition(".")
    if not dot:
        stem, ext = base, ""
    suffix = ("." + ext) if ext else ""
    inner = stem + "/" + prefix + suffix
    return (directory + "/" + inner) if directory else inner


def bloat_spec(path: str) -> tuple[int, int, str, str] | None:
    """The per-file-type bloat thresholds, migrated verbatim from
    check-ai-config so the move is behavior-preserving. Returns
    (warn, high, file-type label, category) or None when the path is not an
    AI-instruction or documentation file."""
    if _glob(path, "*/CLAUDE.md") or _glob(path, "*/AGENTS.md"):
        return (
            _int_env("CLAUDE_MD_WARN", 400),
            _int_env("CLAUDE_MD_HIGH", 600),
            "CLAUDE.md",
            "ai-file-bloat",
        )
    if _glob(path, "*/skills/*/SKILL.md"):
        return (
            _int_env("SKILL_WARN", 300),
            _int_env("SKILL_HIGH", 500),
            "skill definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/agents/*/*.md") or _glob(path, "*/agents/*.md"):
        # Both agent layouts: the FLAT agents/<name>.md Claude Code discovers,
        # and the nested agents/<name>/<name>.md a harness-bearing agent uses.
        return (
            _int_env("AGENT_WARN", 250),
            _int_env("AGENT_HIGH", 400),
            "agent definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/docs/*.md"):
        return (
            _int_env("DOC_WARN", 500),
            _int_env("DOC_HIGH", 800),
            "documentation",
            "doc-file-bloat",
        )
    return None


def scan_file(path: str, lines: list[str]) -> None:
    lang = lang_of(path)
    units = find_units(lines, lang)
    m = measure(lines, lang, units)

    warn = _int_env("DECOMP_LOC_WARN", 300)
    high = _int_env("DECOMP_LOC_HIGH", 500)
    seam_min_units = _int_env("DECOMP_SEAM_MIN_UNITS", 3)
    seam_min_lines = _int_env("DECOMP_SEAM_MIN_LINES", 40)
    seam_max_fanin = _int_env("DECOMP_SEAM_MAX_FANIN", 3)
    god_units = _int_env("DECOMP_GOD_UNITS", 12)
    god_concerns = _int_env("DECOMP_GOD_CONCERNS", 3)
    cohesive_max_units = _int_env("DECOMP_COHESIVE_MAX_UNITS", 2)

    metrics = (
        "%d total, %d comment (%d%%), %d blank, %d test-excluded, "
        "max nesting %d, %d top-level units"
        % (
            m["total"],
            m["comment"],
            m["comment_pct"],
            m["blank"],
            m["test_excluded"],
            m["max_depth"],
            m["units"],
        )
    )

    # --- Category: file-length -------------------------------------------
    over = False
    if m["production"] > high:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d high); %s" % (m["production"], high, metrics),
            "HIGH",
        )
    elif m["production"] > warn:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d warning); %s" % (m["production"], warn, metrics),
            "MEDIUM",
        )

    # --- Categories: ai-file-bloat / doc-file-bloat ------------------------
    spec = bloat_spec(path)
    if spec is not None:
        b_warn, b_high, ftype, category = spec
        n = m["total"]
        if n > b_high:
            emit(
                path,
                1,
                category,
                "%s exceeds high threshold: %d lines (>%d)" % (ftype, n, b_high),
                "HIGH",
            )
        elif n > b_warn:
            emit(
                path,
                1,
                category,
                "%s exceeds warning threshold: %d lines (>%d)" % (ftype, n, b_warn),
                "MEDIUM",
            )

    if not lang:
        return

    clusters = cluster_units(units)
    prefixes = []
    for c in clusters:
        if c.prefix not in prefixes:
            prefixes.append(c.prefix)

    # --- Category: god-module ---------------------------------------------
    # Size alone is not a god module. The signal is size AND many top-level
    # units AND several distinct concerns — the coupling half stays with
    # audit-architecture, which now consumes this LOC number instead of
    # re-deriving it from its own copy of the counting rules.
    if (
        m["production"] > warn
        and m["units"] > god_units
        and len(prefixes) >= god_concerns
    ):
        emit(
            path,
            1,
            "god-module",
            "%d production LOC, %d top-level units, %d concerns (%s)"
            % (
                m["production"],
                m["units"],
                len(prefixes),
                ", ".join(prefixes[:5]),
            ),
            "MEDIUM",
        )

    # --- Category: decomposition-seam --------------------------------------
    noun = UNIT_NOUN.get(lang, "unit")
    seams = 0
    for c in clusters:
        span = c.end - c.start + 1
        if len(c.units) < seam_min_units or span < seam_min_lines:
            continue
        count, callers = fan_in(lines, c, units)
        if count == 0:
            fan = "no external references"
        elif count <= seam_max_fanin and callers:
            fan = "fan-in %d <- %s" % (count, callers)
        else:
            fan = "fan-in %d" % count
        emit(
            path,
            c.start,
            "decomposition-seam",
            "seam %d-%d: %s %s_* family (%d units, %s) -> %s"
            % (
                c.start,
                c.end,
                noun,
                c.prefix,
                len(c.units),
                fan,
                target_path(path, c.prefix),
            ),
            "HIGH",
        )
        seams += 1

    # --- Reasoned decline --------------------------------------------------
    # A file over threshold with no seam is a RESULT, not a silence. A generated
    # artifact, a lookup table, one exhaustive match — long and correct. Record
    # why, so "no seam" can never be mistaken for "not examined"; the finding
    # carries the reason into the baseline= acknowledgment.
    if over and seams == 0:
        generated = any(GENERATED_RE.search(ln) for ln in lines[:20])
        if generated:
            reason = "generated file — regenerate rather than split"
        elif m["units"] <= cohesive_max_units:
            reason = "single cohesive unit — no internal seam to cut"
        elif m["comment_pct"] >= 50:
            reason = "majority prose/comment — length is documentation, not logic"
        else:
            reason = "no low-coupling seam found — units are mutually referential"
        emit(
            path,
            1,
            "decomposition-seam",
            "declined: %s (%d production LOC, %d top-level units)"
            % (reason, m["production"], m["units"]),
            "LOW",
        )


def main(argv: list[str]) -> int:
    if len(argv) < 2 or not argv[1]:
        sys.stderr.write("Usage: patterns.py <file-list>\n")
        return 1

    file_list = argv[1]
    try:
        with open(file_list, "r", encoding="utf-8", errors="replace") as fh:
            paths = [ln.rstrip("\n") for ln in fh]
    except OSError:
        sys.stderr.write("Error: file list not found: " + file_list + "\n")
        return 1

    for path in paths:
        if not path:
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                lines = fh.read().splitlines()
        except OSError:
            continue
        if any(_fnmatch.fnmatchcase(path, g) for g in SKIP_GLOBS):
            continue
        scan_file(path, lines)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
