#!/usr/bin/env python3
"""check-decomposition — Deterministic Pre-Scan (Python primary implementation).

Sizing + language-aware segmentation. Replaces the production-LOC counting prose
that was duplicated across audit-code-health, audit-architecture and
audit-ai-config (issue #663) with one deterministic implementation, and turns the
result from a line count into an actionable **decomposition seam**.

Python 3.11+ primary implementation behind the language-agnostic TSV contract;
the sibling patterns.sh is the portable bash fallback (it exec's this file when a
python3>=3.11 is present). Both emit byte-identical findings — the parity is
pinned by tests/validate-python-ports.sh and the behavior by
tests/validate-decomposition-detectors.sh. See CLAUDE.md § Key conventions.

Input:  argv[1] = file containing paths to scan (one per line)
Output: TSV to stdout: file<TAB>line<TAB>category<TAB>evidence<TAB>certainty

The 5-column contract is NOT widened. A seam is a per-file SPAN, so `line`
carries the seam START and the end line, unit names, fan-in and proposed target
path are encoded as structured text inside `evidence`:

    src/parser.rs<TAB>412<TAB>decomposition-seam<TAB>seam 412-680: fn parse_* \
family (6 units, fan-in 1 <- parse_entry) -> src/parser/parse.rs<TAB>HIGH

Every other check-* skill and all three parity gates keep the contract they have.
The audit-decomposition agent parses this evidence into line_start/line_end.

Thresholds are env-overridable (DECOMP_*, plus the CLAUDE_MD_*/SKILL_*/AGENT_*/
DOC_* bloat vars inherited from check-ai-config when the bloat table moved here).

Exit codes:
  0 = success (zero or more findings)
  1 = usage error (missing argument) or file list not found
"""

from __future__ import annotations

import fnmatch as _fnmatch
import os
import re
import sys

# Non-source files skipped wholesale. Markdown is deliberately ABSENT: this
# scanner segments prose by heading hierarchy and owns doc-file-bloat.
SKIP_GLOBS = (
    "*.lock",
    "*lock.json",
    "*go.sum",
    "*.txt",
    "*.json",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.cfg",
    "*.conf",
)

# Markers that make a long file legitimate — a generated artifact is not a
# decomposition candidate, and saying so is a finding, not a silent drop.
GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated",
    re.IGNORECASE,
)

# >>> shared:loc-tables-py (sync: ship-issue/sizing.py)
# Per-language unit headers. Each maps a language key to the regex that starts a
# TOP-LEVEL unit. Anchored at line start (no leading indent) so nested defs are
# not mistaken for top-level ones — that anchoring is what makes a unit span a
# genuine cut point.
UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?(?:def|class)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "js": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:async[ \t]+)?"
        r"(?:function|class|const|let|var)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    # TypeScript is its OWN key, not a js alias (#726). The js arm above matches
    # only value-level forms, so every TYPE-level declaration — interface, type,
    # enum, namespace, declare, abstract class — was invisible as a unit, and a
    # types.ts full of interfaces segmented to ~0 units and was declined as a
    # "single cohesive unit". A confident wrong answer, not a silence.
    #
    # ALTERNATION ORDER IS LOAD-BEARING, and it is a two-runtime trap. Python re
    # is leftmost-FIRST (ordered alternation); POSIX awk ERE is leftmost-LONGEST.
    # With bare `const` listed before `const enum`, Python captures the NAME
    # `enum` from `export const enum Delta` while awk captures `Delta` — a silent
    # TSV divergence surfacing only as a parity failure. Listing the two-word
    # forms FIRST makes both runtimes agree by construction rather than by
    # dialect luck. Same reason `abstract class` precedes `class`.
    "ts": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:declare[ \t]+)?(?:async[ \t]+)?"
        r"(?:const[ \t]+enum|abstract[ \t]+class|function|class|const|let|var"
        r"|interface|type|enum|namespace|module)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    # Rust (#727). `impl` is deliberately ONE unit spanning header -> next
    # top-level header, NOT its methods. This decision is load-bearing and will
    # be re-asked, so the reason lives here: (a) the engine's invariant is
    # column-zero anchoring — an indented item is never a unit — and segmenting
    # inside `impl` would break that for one language only, requiring
    # depth-aware segmentation nothing else in the engine has; (b) Rust's own
    # SPLIT_SHAPE ("new subdir module; mod.rs re-exports") moves whole ITEMS,
    # and splitting one type's impl across files is a real Rust smell, so a
    # method-level seam would propose a split the language discourages. The
    # cost is accepted and visible: a 400-line impl stays one unit and can reach
    # the "single cohesive unit" decline.
    #
    # `impl Trait for Type` captures the TYPE, not the trait, so `impl Display
    # for Foo` and `impl Debug for Foo` cluster with `impl Foo` under family
    # `foo` — the family then means "this type's surface". Capturing the trait
    # scattered one type across as many families as it had impls.
    #
    # CHECKED, CORRECT AS-IS (#727): a nested `mod foo { ... }` is a unit, but
    # the items INSIDE it are indented and therefore invisible — intended, and
    # the same column-zero rule that makes impl one unit. An inline module is a
    # cut point (it moves to its own file wholesale); its contents are not.
    # The visibility class admits `:` and `_` so `pub(in crate::foo)` matches
    # (#727). With `[a-z ]+` the parenthesized group failed, the whole `pub`
    # alternative failed with it, and the item went INVISIBLE — absorbed into
    # the previous unit's span. Pre-existing, but it is this issue's own defect
    # class, and it is one character to close. `pub(crate)` / `pub(super)` were
    # always fine; only the path form broke.
    "rs": re.compile(
        r"^(?:(?:pub(?:\([a-z:_ ]+\))?|default|async|unsafe|const"
        r"|extern(?:[ \t]+\"[^\"]*\")?)[ \t]+)*"
        r"(?:macro_rules![ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        # The generic list must tolerate NESTING: `<[^>]*>` stops at the first
        # `>`, so a trait bound like `impl<T: Into<String>> Foo<T>` failed the
        # whole match and the impl went INVISIBLE — reintroducing the exact
        # defect this arm exists to fix, on the commonest form of generic impl.
        # Regex cannot balance arbitrarily; this covers three levels, which is
        # past anything real (`A<B<C>>` already exhausts two).
        # The optional `Trait for` clause is LINEAR-TIME by construction, and it
        # has to be: with `.*[ \t]+for`, a run of N spaces after `impl` can be
        # split between `.*` and `[ \t]+` in O(N) ways at each of O(N) offsets,
        # and the engine tries all of them before failing. Measured on the live
        # pattern: `"impl " + " "*N + "!"` took 0.25 s at N=1000, 1.9 s at
        # N=2000, 14.5 s at N=4000 — cubic, and reached by a stray line of
        # trailing whitespace, not only by a crafted one. Two changes make it
        # flat (0.7 ms at N=16000): the clause must START on a non-space, and
        # the separator before `for` is a SINGLE [ \t] so greedy `.*` has
        # exactly one way to hand off.
        #
        # Everything between `for` and the type is consumed: `&`, a lifetime,
        # `mut`, and `dyn`. Each of these was captured as the unit NAME —
        # a keyword as the family and as a god-module "concern" in human-read
        # evidence, the same wrong-finding class RESERVED_UNIT_NAME exists to
        # prevent for Swift. `dyn` is listed beside `mut` deliberately: fixing
        # one borrow marker and leaving its sibling is exactly the
        # [[harden-one-knob-grep-every-sibling]] recurrence, and trait objects
        # are idiomatic rather than exotic.
        #
        # The path prefix is consumed so the LAST segment is captured. Taking
        # the first meant `impl A for crate::Foo` landed in family `crate`
        # while `impl B for Foo` landed in `foo` — the same type in two
        # families, which is the precise failure the trait-vs-type capture was
        # changed to fix. `(?:IDENT::)*` is a bounded prefix loop, so it stays
        # linear (a 8000-segment path matches in 0.5 ms).
        r"|impl(?:<(?:[^<>]|<(?:[^<>]|<[^<>]*>)*>)*>)?[ \t]+"
        r"(?:[^ \t].*[ \t]for[ \t]+)?(?:&[ \t]*)?"
        r"(?:'[A-Za-z_][A-Za-z0-9_]*[ \t]+)?(?:mut[ \t]+)?(?:dyn[ \t]+)?"
        r"(?:[A-Za-z_][A-Za-z0-9_]*::)*"
        r"([A-Za-z_][A-Za-z0-9_]*)"
        r"|extern[ \t]+crate[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        r"|(?:fn|struct|enum|trait|mod|type|static|const|union)"
        r"[ \t]+([A-Za-z_][A-Za-z0-9_]*))"
    ),
    # Go (#727). A METHOD is named `Receiver_Method`, so family_prefix's
    # split-at-first-underscore clusters every method on one receiver into one
    # family — which is exactly Go's SPLIT_SHAPE ("additional files in the same
    # package"). Before this the receiver clause made the match FAIL outright
    # (`(` is not in [A-Za-z_]), so methods were not mis-named, they were
    # INVISIBLE — silently absorbed into the preceding unit's span, and a
    # method-heavy file was declined as near-cohesive on a unit count of ~2.
    #
    # The final arm names a GROUPED declaration (`var (` / `const (` / `type (`)
    # for its keyword. Same reason: grouped blocks were invisible, not "one unit
    # each". One visible unit per block is the honest count — the engine cannot
    # see into a block it does not segment.
    #
    # ACCEPTED LIMITATION (#727): the header line carries no identifier, so the
    # keyword IS the name and two adjacent blocks of the same kind (two `var (`
    # runs back to back — legal, and gofmt does not merge them) share family
    # `var` and can cluster as one seam. Accepted rather than fixed: the
    # alternatives are worse. A running index would make the name
    # position-dependent, so inserting a block upstream renames every one below
    # it and the TSV churns on an unrelated edit; naming the block for its first
    # inner identifier would require reading past the header, which this
    # line-anchored engine deliberately does not do. The failure mode is also
    # benign — a seam proposing that two adjacent declaration groups move to one
    # file is a reasonable suggestion even when they are unrelated, unlike the
    # pre-#727 behavior where the blocks were invisible and the file was
    # declined as cohesive.
    #
    # CHECKED, CORRECT AS-IS (#727): `//go:generate` and build tags do not
    # interact with GENERATED_RE. That pattern looks for @generated /
    # "Code generated by" / DO NOT EDIT in the first 20 lines; a `//go:generate`
    # directive contains none of them, and the file it generates carries the
    # real "Code generated by ... DO NOT EDIT." banner that SHOULD match. So the
    # generator's source is sized normally and its output is declined as
    # generated — which is the intended split. No fixture: a test asserting a
    # pattern does not match an unrelated string cannot fail
    # ([[surviving-mutation-may-be-a-real-no-op]]).
    "go": re.compile(
        r"^func[ \t]*\([ \t]*(?:[A-Za-z_][A-Za-z0-9_]*[ \t]+)?\*?[ \t]*"
        r"([A-Za-z_][A-Za-z0-9_]*)(?:\[[^\]]*\])?[ \t]*\)[ \t]*"
        r"([A-Za-z_][A-Za-z0-9_]*)"
        r"|^(?:func|type|var|const)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        r"|^(var|const|type)[ \t]*\("
    ),
    # Swift (#728). Modifiers are a REPEATED optional group, not a fixed
    # sequence: `public final class`, `@objc private static func` and bare
    # `struct` are all real, and Swift imposes no canonical order on them. One
    # `(?:...)*` group covering access levels, `final`/`static`/`class`
    # (type-method), `override`, `@objc`/`@MainActor`-style attributes, and
    # `indirect` matches every ordering without enumerating permutations.
    #
    # `extension` is ONE unit, matching Rust's `impl` (#727). The two are the
    # same construct — a block bundling many methods onto a type — so they must
    # be segmented the same way or the cohesive-decline path treats equivalent
    # code differently by language. If #727 re-decides `impl`, this arm changes
    # in the SAME PR; neither may move alone.
    #
    # `associatedtype` is deliberately NOT here, though the issue listed it.
    # Swift allows it only INSIDE a protocol body, so it is never a top-level
    # declaration — and an arm for it is not merely dead, it is harmful: a
    # protocol whose body is written unindented (legal Swift) would have each
    # `associatedtype` lifted into a phantom top-level unit, corrupting the very
    # count the cohesive-decline and seam paths read. Found by the mutation
    # round: deleting the arm changed nothing, and the reachability check that
    # followed showed the only inputs it fires on are invalid Swift or that
    # false positive ([[surviving-mutation-may-be-a-real-no-op]]). It stays in
    # RESERVED_UNIT_NAME, since it is still a keyword no NAME may be.
    #
    # A keyword captured as the NAME is rejected downstream by
    # RESERVED_UNIT_NAME — see the note there for why that is a filter rather
    # than a negative lookahead.
    "swift": re.compile(
        r"^(?:(?:public|private|internal|fileprivate|open|final|static|class"
        r"|override|indirect|@[A-Za-z_][A-Za-z0-9_]*)[ \t]+)*"
        r"(?:func|class|struct|enum|protocol|extension|actor|typealias)"
        r"[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
    "sh": re.compile(
        r"^(?:function[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]*\([ \t]*\)|"
        r"^function[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
}

# Comment-line shapes per language (used for the comment/production split).
COMMENT_RE = {
    "py": re.compile(r"^[ \t]*#"),
    "sh": re.compile(r"^[ \t]*#"),
    "js": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "ts": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "rs": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "go": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    # Swift (#728). `///` and `/**` doc comments are matched by the `//` and
    # `/*` alternatives respectively — the issue notes this works "by luck" for
    # the `//` arm, so the fixture asserts the production-LOC NUMBER changes on
    # a doc-commented file rather than trusting the shape by inspection.
    "swift": re.compile(r"^[ \t]*(?://|/\*|\*)"),
}

# A unit header that marks the unit as TEST code. Replaces the per-language
# exclusion prose the three agents each carried a drifting copy of. Because unit
# SPANS are already computed, exclusion is per-unit and exact rather than the
# "to end of file" approximation the prose specified.
TEST_UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?def[ \t]+test_|^class[ \t]+Test"),
    "js": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    "ts": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    # NB: `rs` is deliberately absent — Rust marks tests with an ATTRIBUTE on
    # the preceding line, so it lives in ATTR_TEST_RE below. It USED to sit here
    # too, read by a hardcoded `lang == "rs"` attribute branch; #728 moved it to
    # the table that describes what it actually is. Keeping a copy here would be
    # two spellings of one fact, and now that the same-line path no longer
    # excludes rs by name, a stale copy would be live code.
    #
    # The optional receiver clause keeps a TESTIFY-style method
    # (`func (s *Suite) TestFoo`) test-classified (#727). Once UNIT_RE["go"]
    # learned to segment methods, anchoring on `^func[ \t]+Test` alone stopped
    # matching them — the suite method became a production unit and its body
    # counted toward production LOC.
    # The prefix needs a BOUNDARY. Go's rule is `func TestXxx` where Xxx does
    # not begin with a lowercase letter, so a bare prefix match classifies
    # `Testify`, `Benchmarking` and `Exampler` as test code and silently drops
    # their lines from production LOC and the unit count — a wrong number
    # feeding god-module, seam and decline verdicts, with no visible error.
    # Requiring an uppercase letter, `_`, or the end of the name (`(`) after
    # the prefix matches the convention exactly. The bare-func arm had this
    # weakness before #727; extending the prefix to every receiver METHOD would
    # have widened it considerably, so both arms are anchored here.
    "go": re.compile(
        r"^func[ \t]+(?:Test|Benchmark|Fuzz|Example)(?:[A-Z_]|[ \t]*\()"
        r"|^func[ \t]*\([^)]*\)[ \t]*(?:Test|Benchmark|Fuzz|Example)(?:[A-Z_]|[ \t]*\()"
    ),
    "sh": re.compile(r"^(?:function[ \t]+)?test_[A-Za-z0-9_]*[ \t]*\([ \t]*\)"),
    # Swift XCTest (#728) — the SAME-LINE half of Swift's two test conventions:
    # a `func test…` (any modifier prefix) or an `XCTestCase` subclass. The
    # swift-testing half is an ATTRIBUTE on the preceding line and lives in
    # ATTR_TEST_RE below; both ship because the ecosystem is mid-migration.
    #
    # The class arm keys off the `: XCTestCase` conformance rather than a name
    # convention, since Swift test classes are not required to be named Test*.
    # `[^{]*` spans any other protocols in the conformance list without running
    # into the body.
    "swift": re.compile(
        r"^(?:(?:public|private|internal|fileprivate|open|final|static|class"
        r"|override|indirect|@[A-Za-z_][A-Za-z0-9_]*)[ \t]+)*"
        r"(?:func[ \t]+test|class[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*:[^{]*XCTestCase)"
    ),
}

# An ATTRIBUTE line that marks the NEXT unit as test code (#728).
#
# Generalized from a hardcoded `lang == "rs"` branch in find_units(). Rust's
# `#[test]` and swift-testing's `@Test` are the same construct — a marker on the
# line BEFORE the unit header — and hardcoding a second language would have made
# three copies of one idea across four files. Table membership now drives the
# `pending_test` path, so a third attribute-marking language is one entry.
#
# A language may appear in BOTH tables: Swift does, since XCTest is same-line
# while swift-testing is attribute-marked, which is why find_units() checks the
# two paths independently rather than as an either/or.
ATTR_TEST_RE = {
    "rs": re.compile(r"^[ \t]*#\[(?:cfg\(test\)|test)\]"),
    "swift": re.compile(r"^[ \t]*@Test\b"),
}

# Words that must never be accepted as a captured unit NAME (#728).
#
# Swift's `class` is in both the modifier group and the keyword alternation of
# UNIT_RE, so a malformed-but-parseable spelling (`open class override Foo`)
# matches `class` as the keyword and hands back `override` as the name. That is
# not a cosmetic mislabel: the name becomes the seam family and a god-module
# "concern" in evidence a human reads, so a keyword there is a WRONG FINDING.
#
# Enforced as a post-match FILTER rather than a negative lookahead, on purpose.
# POSIX awk ERE has no lookahead at all, so a lookahead would be a Python-only
# construct — the two impls would disagree on exactly these lines, and the
# divergence would surface as a parity failure rather than as the fix it looks
# like. A set membership test transcribes to awk verbatim (is_reserved_name).
#
# Only `swift` populates this today; find_units consults it for every language
# so a future one needs no new branch.
RESERVED_UNIT_NAME = {
    "swift": {
        "public",
        "private",
        "internal",
        "fileprivate",
        "open",
        "final",
        "static",
        "class",
        "override",
        "indirect",
        "func",
        "struct",
        "enum",
        "protocol",
        "extension",
        "actor",
        "typealias",
        "associatedtype",
    },
}

# Whole-file test-region markers: everything from the match to EOF is test code.
# Kept for the two cases the prose named that are genuinely region-scoped rather
# than unit-scoped.
TEST_REGION_RE = {
    "py": re.compile(r"^if[ \t]+__name__"),
    # COLUMN-ZERO only (#727), matching the pending-test attribute guard in
    # find_units. The `[ \t]*` this used to carry made a NESTED marker — a
    # `#[cfg(test)] mod tests` indented inside an outer `mod` — engage the
    # whole-file region path. That marker is not itself a unit header (units are
    # column-zero anchored), so the stop-computation below latched onto whatever
    # top-level unit happened to follow and excluded everything in between:
    # measured on a 16-line fixture, 11 lines test-excluded and a production fn
    # swallowed whole, for 4 production LOC instead of 10. A nested test module
    # is already covered per-unit by its enclosing unit's span; the region path
    # exists for the CONVENTIONAL trailing placement, which is column-zero.
    "rs": re.compile(r"^#\[cfg\(test\)\]"),
    "sh": re.compile(r"^#[ \t]*-+[ \t]*tests?[ \t]*-+"),
}

# Indent width used to convert leading whitespace into a nesting depth.
NEST_UNIT = {
    "py": 4,
    "js": 2,
    "ts": 2,
    "rs": 4,
    "go": 4,
    "sh": 4,
    "md": 2,
    "swift": 4,
}

# Blankness and indent are defined by REGEX, not str.strip()/str.lstrip(): the
# latter are unicode-aware (\x0b, \x0c, \x85, NBSP...) while the awk fallback
# under LC_ALL=C is not. Pinning both impls to [ \t] is what keeps the TSV
# byte-identical on a file with exotic whitespace.
BLANK_RE = re.compile(r"^[ \t]*$")
INDENT_RE = re.compile(r"^[ \t]*")

EXT_LANG = {
    "py": "py",
    "js": "js",
    "jsx": "js",
    "mjs": "js",
    "cjs": "js",
    "ts": "ts",
    "tsx": "ts",
    "rs": "rs",
    "go": "go",
    "sh": "sh",
    "bash": "sh",
    "md": "md",
    "markdown": "md",
    "swift": "swift",
}
# <<< shared:loc-tables-py

# Identifier tokens for the fan-in scan. A MAXIMAL run is what makes membership
# equivalent to a \bNAME\b regex — and, unlike an escaped alternation, it is
# reproducible verbatim in the awk fallback, so the two impls agree by
# construction rather than by two hand-matched regex dialects.
#
# NOT shared with sizing.py: the fan-in scan is an audit-lens concern, and the
# review lens has no cluster coupling analysis to run it over.
TOKEN_RE = re.compile(r"[A-Za-z0-9_$]+")

# Noun used in seam evidence, per language. NOT shared with sizing.py — only
# this lens emits line-range seam rows, so the review lens has nowhere to spend a
# unit noun and copying the table there would add a lookup nothing reads (#730).
# The split SHAPE below is the opposite case: both lenses emit it, which is
# exactly why it IS shared (#725).
UNIT_NOUN = {
    "py": "def",
    "js": "function",
    # Not "function": a TS top-level unit is as often a type-level declaration
    # (interface/type/enum) as a callable, and the noun goes into seam evidence
    # a human reads. "declaration" is the one word true of every ts arm.
    "ts": "declaration",
    "rs": "fn",
    "go": "func",
    "sh": "function",
    "md": "section",
    # Same argument as ts: a Swift top-level unit is as often a TYPE
    # (struct/protocol/enum/extension) as a callable, so "func" would be wrong
    # for most rows. "declaration" is the one word true of every swift arm.
    "swift": "declaration",
}


# >>> shared:split-shape-py (sync: ship-issue/sizing.py)
# LANGUAGE-SHAPED SPLIT GUIDANCE — shared by BOTH lenses (#725).
#
# Introduced on the review lens alone (#695), which was backwards: the AUDIT lens
# is the one that files a backlog somebody picks up weeks later, with none of the
# PR context that makes a bare line range interpretable. That reader needs the
# shape spelled out most, and had it least — the exact "too generic to act on, so
# nothing gets decomposed" failure #663 was filed against.
#
# Keyed by the same language keys the segmenters use (EXT_LANG's values), so
# advice and measurement can never disagree about what a file IS. That invariant
# is asserted structurally: a language with a segmenter and no shape, or a shape
# for a language nothing segments, fails tests/validate-shared-scanner-sync.sh.
# It is what makes adding a language (#726 TypeScript, #727 Rust/Go, #728 Swift)
# a one-table edit rather than two that must be remembered together.
#
# Each string names the SHAPE of the split, not a generic "consider splitting" —
# the finding has to be actionable or it is noise.
SPLIT_SHAPE = {
    "rs": "new subdir module; mod.rs re-exports the decomposed units",
    "py": "package dir with __init__.py re-exporting the public surface",
    "js": "sibling modules + a barrel index.ts",
    # DIFFERENT from js on purpose (#726). The js shape moves runtime modules;
    # an oversized TypeScript file is usually type-heavy, and its real remedy is
    # to group types by DOMAIN under types/ with a re-exporting barrel — a
    # different instruction, which is why ts needs its own key rather than
    # inheriting the js one through an alias.
    "ts": "types/ dir split by domain + a re-exporting barrel index.ts",
    "go": "additional files in the same package (no import churn)",
    # Swift's idiomatic decomposition is extensions in separate files (#728) —
    # `Foo+Networking.swift`, `Foo+Codable.swift`. DIFFERENT from every other
    # shape here because it needs no re-exporting barrel and no module: Swift
    # types are open for extension across files within a module, so a split
    # costs zero import churn at the call site. Naming the `Type+Concern.swift`
    # convention is what makes the row actionable rather than "consider
    # splitting".
    "swift": "extensions in separate files (Type+Concern.swift), same module",
    "sh": "sourced fragment + an explicit ordered list (split-suite convention)",
    "md": (
        "progressive disclosure: move detail to linked files, leave a one-line pointer"
    ),
}

# The shape for a file whose extension has NO segmenter (.rb, .java, .c, .cpp,
# .kt — all scanned, since none are skipped). Weaker than a language-shaped
# string but still a real destination, which is what keeps every actionable
# over-threshold file yielding exactly one seam row.
#
# It lives INSIDE the shared region on purpose. As a bare literal at each call
# site it was two more unpinned copies of the same fact — the precise shape of
# duplication this region exists to end.
SPLIT_SHAPE_FALLBACK = "extract a cohesive unit into a sibling module"


def split_shape(lang: str) -> str:
    """The split shape for LANG, falling back for an unsegmented language.

    Every consumer goes through this rather than indexing SPLIT_SHAPE directly,
    so the fallback cannot fork the way it already had."""
    return SPLIT_SHAPE.get(lang, SPLIT_SHAPE_FALLBACK)


# <<< shared:split-shape-py


# >>> shared:loc-helpers-py (sync: ship-issue/sizing.py)
def _int_env(name: str, default: int) -> int:
    """Read an integer threshold from the environment, falling back to DEFAULT.
    Mirrors _int_env in check-ai-config/patterns.py (and the ${VAR:-N} defaults
    in every patterns.sh) so thresholds.yml values can be passed through by the
    orchestrator without either impl diverging."""
    val = os.environ.get(name, "")
    try:
        return int(val)
    except ValueError:
        return default


def emit(path: str, line_no: int, category: str, evidence: str, certainty: str) -> None:
    """Write one TSV finding row."""
    sys.stdout.write(
        "\t".join((path, str(line_no), category, evidence, certainty)) + "\n"
    )


def lang_of(path: str) -> str:
    """Language key from the file extension, or '' when unrecognized (metrics
    only, no segmenter)."""
    if "." not in path:
        return ""
    return EXT_LANG.get(path.rsplit(".", 1)[-1].lower(), "")


DECL_SUFFIX = ".d.ts"


def is_decl_file(path: str) -> bool:
    """A TypeScript DECLARATION file (*.d.ts), which is type-level by
    construction and has no runtime units to extract (#726).

    Deliberately NOT added to SKIP_GLOBS. A skip makes an over-budget .d.ts
    indistinguishable from an unscanned one, and this scanner's whole discipline
    is that a decline is a RESULT while silence is the bug. So the file is
    measured and sized as usual; only its SEAM is suppressed, and it declines
    with its own reason.

    Matched on the full lowercased path (a case-insensitive suffix test), so
    `Foo.D.TS` on a case-insensitive filesystem classifies the same as
    `foo.d.ts` — the same target must decide alike in every spelling."""
    return path.lower().endswith(DECL_SUFFIX)


# <<< shared:loc-helpers-py


# >>> shared:loc-unit-py (sync: ship-issue/sizing.py)
def family_prefix(name: str) -> str:
    """The family key a unit name belongs to — the shared stem that makes
    `parse_entry` / `parse_header` / `parse_body` one cluster.

    snake_case splits at the first underscore; camelCase and PascalCase split at
    the first internal uppercase letter. The result is lowercased so `ParseEntry`
    and `parse_entry` land in the same family.
    """
    cut = name.find("_")
    if cut > 0:
        return name[:cut].lower()
    i = 1
    while i < len(name) and not ("A" <= name[i] <= "Z"):
        i += 1
    return name[:i].lower()


def md_slug(text: str) -> str:
    """Markdown heading text -> an identifier-shaped slug so family_prefix()
    applies unchanged ('Install on Linux' -> 'install_on_linux')."""
    out = []
    prev_us = False
    for ch in INDENT_RE.sub("", text.rstrip()).lower():
        if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
            out.append(ch)
            prev_us = False
        elif not prev_us:
            out.append("_")
            prev_us = True
    return "".join(out).strip("_")


class Unit:
    """One top-level declaration: its name, family, header line and span.

    THE shared representation for both lenses (#730). The review lens
    (ship-issue/sizing.py) previously carried a parallel 4-tuple shape, which was
    the structural reason the two `find_units` bodies could never be compared
    byte-for-byte — and so the reason the Python halves drifted while their awk
    twins stayed pinned. `prefix` is what the audit lens clusters on; the review
    lens does not cluster, but carrying one field it ignores is far cheaper than
    two representations neither gate can align.
    """

    __slots__ = ("name", "prefix", "start", "end", "is_test")

    def __init__(self, name: str, start: int) -> None:
        self.name = name
        self.prefix = family_prefix(name)
        self.start = start
        self.end = start
        self.is_test = False


def find_units(lines: list[str], lang: str) -> list[Unit]:
    """Top-level units in file order, each spanning from its header line to the
    line before the next header (or EOF).

    For markdown, 'top-level' means the shallowest heading depth present, so a
    doc whose sections are all `##` segments by `##` rather than by a lone `#`
    title."""
    units: list[Unit] = []
    if lang == "md":
        heads: list[tuple[int, int, str]] = []  # (depth, line_no, text)
        fenced = False
        for idx, line in enumerate(lines, start=1):
            if line.startswith("```") or line.startswith("~~~"):
                fenced = not fenced
                continue
            if fenced:
                continue
            m = re.match(r"^(#{1,6})[ \t]+(.*)$", line)
            if m:
                heads.append((len(m.group(1)), idx, m.group(2)))
        if not heads:
            return []
        top = min(h[0] for h in heads)
        for depth, line_no, text in heads:
            if depth == top:
                units.append(Unit(md_slug(text) or "section", line_no))
    else:
        rx = UNIT_RE.get(lang)
        if rx is None:
            return []
        test_rx = TEST_UNIT_RE.get(lang)
        attr_rx = ATTR_TEST_RE.get(lang)
        pending_test = False
        for idx, line in enumerate(lines, start=1):
            m = rx.match(line)
            # An attribute line marks the NEXT unit as test code (Rust #[test],
            # swift-testing @Test). Table-driven since #728 — it was a hardcoded
            # `lang == "rs"` branch.
            #
            # ORDER MATTERS, and differs from the pre-#728 code: the unit match
            # is attempted FIRST, and the attribute only CONSUMES the line when
            # the line is not itself a unit header. Rust's `#[test]` always
            # stands alone so this is a no-op there, but swift-testing writes
            # `@Test func foo()` on ONE line — under the old continue-first
            # shape that line would set the flag and be skipped, losing the unit
            # entirely and marking the NEXT (production) unit as a test instead.
            # Only a COLUMN-ZERO attribute may set the flag (#727). Both
            # ATTR_TEST_RE patterns tolerate leading whitespace — rs because the
            # same spelling doubles as the TEST_REGION_RE marker — so an
            # INDENTED attribute inside a block (`#[test]` within
            # `mod tests { ... }`, `@Test` within an XCTestCase body) used to
            # set this flag and then mark the next TOP-LEVEL unit, a PRODUCTION
            # declaration after the block, as test code — silently dropping its
            # lines from production LOC. The guard is language-agnostic because
            # the invariant is: units are column-zero anchored, so an indented
            # attribute cannot be marking one.
            if attr_rx is not None and not line[:1].isspace() and attr_rx.search(line):
                pending_test = True
                if m is None:
                    continue
            if not m:
                continue
            # Join every group that matched. Most arms set exactly one (the
            # rest are None), so this is the old "group(1) else group(2)" for
            # them; Go's method arm sets TWO — receiver and method — and joins
            # them into `Repo_Get`, the underscore family_prefix then splits on.
            name = "_".join(g for g in m.groups() if g)
            if not name:
                continue
            # A keyword captured as a name means the line parsed a modifier as
            # the unit keyword — drop the bogus unit rather than seed a seam
            # family called "override" (#728). The line is still counted by
            # measure(); only the phantom unit disappears.
            #
            # pending_test MUST be cleared on this path. The dropped header is
            # what the attribute was marking, so leaving the flag set carries it
            # onto the NEXT genuine unit and silently marks a PRODUCTION unit as
            # test — removing its lines from production LOC and suppressing the
            # very findings this scanner exists to emit. The guard against one
            # wrong answer would otherwise manufacture another
            # ([[fix-reintroduces-its-own-failure]]).
            if name in RESERVED_UNIT_NAME.get(lang, ()):
                pending_test = False
                continue
            u = Unit(name, idx)
            if pending_test:
                u.is_test = True
                pending_test = False
            elif test_rx is not None and test_rx.search(line):
                # No longer excludes the attribute-marked languages by name
                # (#728). Rust has no TEST_UNIT_RE entry, so dropping the old
                # `lang != "rs"` guard cannot change its behavior; Swift needs
                # BOTH paths live, since XCTest is same-line while swift-testing
                # is attribute-marked.
                u.is_test = True
            units.append(u)

    for i, u in enumerate(units):
        u.end = units[i + 1].start - 1 if i + 1 < len(units) else len(lines)
    return units


# <<< shared:loc-unit-py


# >>> shared:loc-measure-py (sync: ship-issue/sizing.py)
def measure(lines: list[str], lang: str, units: list[Unit]) -> dict:
    """The generic sizing layer: total / blank / comment / test-excluded /
    production LOC, max nesting depth, and top-level unit count.

    The audit lens (check-decomposition/patterns.py) and the review lens
    (ship-issue/sizing.py) carry byte-identical copies, pinned by
    tests/validate-shared-scanner-sync.sh; the same computation is transcribed
    into awk in the shared:loc-measure-awk region of both bash fallbacks."""
    total = len(lines)
    comment_rx = COMMENT_RE.get(lang)
    region_rx = TEST_REGION_RE.get(lang)

    # Lines inside a test unit, or after a whole-file test-region marker.
    test_lines = set()
    for u in units:
        if u.is_test:
            test_lines.update(range(u.start, u.end + 1))
    if region_rx is not None:
        for idx, line in enumerate(lines, start=1):
            if region_rx.search(line):
                # The region runs to the end of the unit the marker INTRODUCES,
                # not unconditionally to EOF (#727). For the conventional
                # trailing placement these are the same line — the marked unit
                # is the last one — so this is a no-op there. It differs only
                # for a marker in the MIDDLE of a file, where running to EOF
                # excluded every production unit that followed: a `#[cfg(test)]
                # mod tests` at line 5 of an 18-line file excluded 14 lines and
                # reported 3 production LOC instead of 9.
                #
                # Falling back to EOF when no unit follows keeps a marker with
                # no unit after it (a trailing `if __name__` block in py, a
                # `# --- tests ---` banner in sh) excluding its tail as before.
                stop = total
                for u in units:
                    if u.start >= idx:
                        stop = u.end
                        break
                test_lines.update(range(idx, stop + 1))
                break

    blank = 0
    comment = 0
    test_excluded = 0
    max_depth = 0
    nest_unit = NEST_UNIT.get(lang, 4)
    for idx, line in enumerate(lines, start=1):
        if idx in test_lines:
            test_excluded += 1
            continue
        if BLANK_RE.match(line):
            blank += 1
            continue
        if comment_rx is not None and comment_rx.match(line):
            comment += 1
            continue
        depth = len(INDENT_RE.match(line).group(0)) // nest_unit
        if depth > max_depth:
            max_depth = depth

    production = total - blank - comment - test_excluded
    return {
        "total": total,
        "blank": blank,
        "comment": comment,
        "test_excluded": test_excluded,
        "production": production,
        "max_depth": max_depth,
        "units": len([u for u in units if not u.is_test]),
        "comment_pct": (comment * 100 // total) if total else 0,
    }


# <<< shared:loc-measure-py


class Cluster:
    """A maximal run of CONSECUTIVE same-family units — contiguous by
    construction, which is what makes the span a single mechanical move."""

    __slots__ = ("prefix", "units", "start", "end")

    def __init__(self, prefix: str, units: list[Unit]) -> None:
        self.prefix = prefix
        self.units = units
        self.start = units[0].start
        self.end = units[-1].end


def cluster_units(units: list[Unit]) -> list[Cluster]:
    """Group ADJACENT units sharing a family prefix.

    Adjacency is by unit INDEX, not merely by same-prefix order: a test unit (or
    any other family) sitting between two same-family units breaks the run. That
    matters because the span is meant to be a single mechanical move — a
    `render_*` trio interleaved with eight test functions spans 230 lines that
    cannot be lifted out without dragging the tests along, so it is not a seam.
    """
    clusters: list[Cluster] = []
    run: list[Unit] = []
    last_idx = -2
    for idx, u in enumerate(units):
        if u.is_test:
            continue
        if run and run[-1].prefix == u.prefix and idx == last_idx + 1:
            run.append(u)
        else:
            if run:
                clusters.append(Cluster(run[0].prefix, run))
            run = [u]
        last_idx = idx
    if run:
        clusters.append(Cluster(run[0].prefix, run))
    return clusters


def fan_in(lines: list[str], cluster: Cluster, units: list[Unit]) -> tuple[int, str]:
    """How much of the REST of the file reaches into this cluster.

    Returns (reference count, comma-joined names of the referencing top-level
    units, capped at 3). A low fan-in is the signal that the span is a
    low-coupling cut point — the whole point of naming a seam rather than a size.
    """
    names = set(u.name for u in cluster.units)
    count = 0
    callers: list[str] = []
    for idx, line in enumerate(lines, start=1):
        if cluster.start <= idx <= cluster.end:
            continue
        if not (names & set(TOKEN_RE.findall(line))):
            continue
        count += 1
        for u in units:
            if u.start <= idx <= u.end and u.name not in callers:
                callers.append(u.name)
                break
    callers.sort()
    return count, ", ".join(callers[:3])


def target_path(path: str, prefix: str) -> str:
    """Where the seam should move to: a sibling module named for the family,
    under a directory named for the file it came from."""
    if "/" in path:
        directory, base = path.rsplit("/", 1)
    else:
        directory, base = "", path
    stem, dot, ext = base.rpartition(".")
    if not dot:
        stem, ext = base, ""
    suffix = ("." + ext) if ext else ""
    inner = stem + "/" + prefix + suffix
    return (directory + "/" + inner) if directory else inner


def concept_dir(path: str) -> str:
    """Which directory an extracted memory-bundle concept belongs in (#713).

    The source file's OWN directory, not the bundle root. `bundle_kind()`
    explicitly supports a concept nested below the root (its `*/root/*` arm), and
    for `<root>/topics/two-lessons.md` a root-anchored target silently drops the
    `topics/` segment — advice that, followed literally, moves the extracted
    lesson out of its subdirectory instead of alongside the sibling it was
    extracted from. Deriving from the source path is what every other
    seam-target computation here does (`target_path()`).

    Deliberately NOT `target_path()` itself, which builds `dir/stem/prefix.ext`
    — a subdirectory named for the source file. That is right for a code family
    and wrong for a bundle: an extracted lesson is a flat SIBLING of the file it
    came from, never a child of it.

    A flat-bundle file already HAS the root as its own directory, so the common
    case is unchanged by this derivation — only a nested concept moves. The
    bundle-root fallback is therefore defensive and unreachable from the only
    call site: `bundle_kind()` sets a kind only for a path matching
    `<root>/...` or `.../<root>/...`, both of which contain a slash."""
    if "/" in path:
        return path.rsplit("/", 1)[0]
    return _bundle_root()


def bundle_sections(lines: list[str]) -> list[str]:
    """The topic clusters of a bundle markdown file (#700).

    NOT the same as `find_units`' top-level units. `find_units` takes the
    SHALLOWEST heading depth present, which for a normal bundle file is the
    lone `# Title` — so the `##` topic sections, which are exactly what an
    index splits along, would be invisible and every index would decline.

    The rule here is the shallowest depth that has at least TWO headings: a
    `# Title` + `## topics` file clusters by its `##`, and a file written with
    all-`##` sections and no title clusters by those same `##`. Falls back to
    the shallowest depth when nothing repeats (a genuinely unsplittable file)."""
    heads: list[tuple[int, str]] = []
    fenced = False
    for line in lines:
        if line.startswith("```") or line.startswith("~~~"):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = re.match(r"^(#{1,6})[ \t]+(.*)$", line)
        if m:
            heads.append((len(m.group(1)), md_slug(m.group(2)) or "section"))
    if not heads:
        return []
    depths = sorted(set(d for d, _ in heads))
    chosen = depths[0]
    for d in depths:
        if sum(1 for hd, _ in heads if hd == d) >= 2:
            chosen = d
            break
    return [name for d, name in heads if d == chosen]


# >>> shared:bloat-spec-py (sync: ship-issue/sizing.py)
# PROSE FILE-TYPE CLASSIFICATION — shared by BOTH lenses (#724).
#
# What a markdown file IS is a fact about its PATH, and a fact must not fork.
# Before #724 only the audit lens classified prose; the review lens sized every
# .md by the generic md pair (700/1000), so an over-budget agent definition
# passed a per-PR review silently while the audit sweep called it HIGH. The two
# lenses may differ in STRICTNESS — that is a policy dial each owns — but they
# may not disagree about what the file is.
#
# STRICTNESS IS NOT FORKED EITHER, for these files specifically. Both lenses
# apply the bloat_thresholds numbers verbatim; there is no review-lens override
# table. The review lens is looser than the audit lens for CODE because those
# thresholds count production LOC and a per-PR gate that nags gets turned off.
# That argument does not transfer: bloat budgets are measured on TOTAL lines
# because these files load WHOLE into context, and that cost does not depend on
# which lens is looking. What keeps the review lens survivable here is its
# GROWTH DISPOSITION (sizing.py's scan_file), not a bigger number.
def _glob(path: str, pattern: str) -> bool:
    """`case "$path" in <pattern>)` — an unanchored shell glob over the full
    path. fnmatchcase's `*` crosses '/', matching bash `case` glob semantics."""
    return _fnmatch.fnmatchcase(path, pattern)


def _bundle_root() -> str:
    """The configured memory-bundle root, normalized for glob matching (#700).

    Configurable rather than hardcoded, defaulting to `.claude/memory`. An
    EMPTY value means no bundle is configured: memory classification is off and
    nothing errors.

    Normalization strips a leading `./` and any trailing `/` so that every
    spelling of the same root — `.claude/memory`, `./.claude/memory`,
    `.claude/memory/` — decides alike. An unnormalized root would make the
    glob miss, the file would fall back to the code thresholds, and the scan
    would still exit 0 — the silent fail-open this issue exists to close."""
    root = os.environ.get("MEMORY_BUNDLE_ROOT", ".claude/memory").strip()
    while root.startswith("./"):
        root = root[2:]
    while root.endswith("/"):
        root = root[:-1]
    return root


def bundle_kind(path: str) -> str:
    """Which half of the memory bundle PATH is: "index", "concept", or "" when
    it is not a bundle markdown file (#700).

    Only `*.md` under the root is bundle prose — a `.sh` or `.py` sitting in a
    bundle is code and keeps the code thresholds.

    An index is the file loaded every session to route recall: the root
    `MEMORY.md`, a topic sub-index `index-*.md`, or OKF's `index.md`."""
    root = _bundle_root()
    if not root:
        return ""
    # LITERAL containment, deliberately NOT _glob(). The root is operator
    # configuration, and routing it through fnmatch would interpret any glob
    # metacharacter in it (`[`, `]`, `*`, `?`) as syntax. The bash mirror does
    # NOT: a QUOTED expansion in a `case` pattern (`"$MEMORY_BUNDLE_ROOT"/*.md`)
    # is matched literally by bash. So a root like `weird[x]root` made fnmatch
    # read `[x]` as a character class and miss, while bash matched — the two
    # impls disagreed on the same file, breaking the byte-identical TSV
    # contract, silently and at exit 0. These two tests mirror bash's two arms:
    # `"$ROOT"/*` (root at the start) and `*/"$ROOT"/*` (root nested anywhere).
    if not (path.startswith(root + "/") or ("/" + root + "/") in path):
        return ""
    base = path.rsplit("/", 1)[-1]
    if not base.endswith(".md"):
        return ""
    if base == "MEMORY.md" or base == "index.md" or base.startswith("index-"):
        return "index"
    return "concept"


def bloat_spec(path: str) -> tuple[int, int, str, str] | None:
    """The per-file-type bloat thresholds, migrated verbatim from
    check-ai-config so the move is behavior-preserving. Returns
    (warn, high, file-type label, category) or None when the path is not an
    AI-instruction or documentation file.

    The memory-bundle arm is FIRST (#700): inside a configured bundle, bundle
    rules apply, so a `docs/` or `agents/` directory nested in the bundle
    cannot escape to the arms below and be sized by the wrong budget."""
    kind = bundle_kind(path)
    if kind == "index":
        return (
            _int_env("MEMORY_INDEX_WARN", 150),
            _int_env("MEMORY_INDEX_HIGH", 250),
            "memory index",
            "ai-file-bloat",
        )
    if kind == "concept":
        return (
            _int_env("MEMORY_CONCEPT_WARN", 200),
            _int_env("MEMORY_CONCEPT_HIGH", 350),
            "memory concept",
            "ai-file-bloat",
        )
    if _glob(path, "*/CLAUDE.md") or _glob(path, "*/AGENTS.md"):
        return (
            _int_env("CLAUDE_MD_WARN", 400),
            _int_env("CLAUDE_MD_HIGH", 600),
            "CLAUDE.md",
            "ai-file-bloat",
        )
    if _glob(path, "*/skills/*/SKILL.md"):
        return (
            _int_env("SKILL_WARN", 300),
            _int_env("SKILL_HIGH", 500),
            "skill definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/agents/*/*.md") or _glob(path, "*/agents/*.md"):
        # Both agent layouts: the FLAT agents/<name>.md Claude Code discovers,
        # and the nested agents/<name>/<name>.md a harness-bearing agent uses.
        return (
            _int_env("AGENT_WARN", 250),
            _int_env("AGENT_HIGH", 400),
            "agent definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/skills/*/*.md"):
        # Skill COMPANION prose (#589) — a reference file a SKILL.md tells the
        # agent to load. MUST stay below the SKILL.md arm above, which is the
        # narrower pattern: these arms are sequential, so hoisting this one
        # would swallow every SKILL.md into the looser companion budget.
        #
        # Before this arm existed, a companion matched NOTHING here and fell
        # through to the production-LOC code thresholds (300/500) — sized by a
        # rule written for source. Exactly the defect #700 fixed for memory
        # bundles, on the repo's LARGEST prose files.
        return (
            _int_env("COMPANION_WARN", 400),
            _int_env("COMPANION_HIGH", 650),
            "skill companion",
            "ai-file-bloat",
        )
    if _glob(path, "*/docs/*.md"):
        return (
            _int_env("DOC_WARN", 500),
            _int_env("DOC_HIGH", 800),
            "documentation",
            "doc-file-bloat",
        )
    return None


# <<< shared:bloat-spec-py


def scan_file(path: str, lines: list[str]) -> None:
    lang = lang_of(path)
    units = find_units(lines, lang)
    m = measure(lines, lang, units)

    warn = _int_env("DECOMP_LOC_WARN", 300)
    high = _int_env("DECOMP_LOC_HIGH", 500)
    seam_min_units = _int_env("DECOMP_SEAM_MIN_UNITS", 3)
    seam_min_lines = _int_env("DECOMP_SEAM_MIN_LINES", 40)
    seam_max_fanin = _int_env("DECOMP_SEAM_MAX_FANIN", 3)
    god_units = _int_env("DECOMP_GOD_UNITS", 12)
    god_concerns = _int_env("DECOMP_GOD_CONCERNS", 3)
    cohesive_max_units = _int_env("DECOMP_COHESIVE_MAX_UNITS", 2)

    metrics = (
        "%d total, %d comment (%d%%), %d blank, %d test-excluded, "
        "max nesting %d, %d top-level units"
        % (
            m["total"],
            m["comment"],
            m["comment_pct"],
            m["blank"],
            m["test_excluded"],
            m["max_depth"],
            m["units"],
        )
    )

    # --- Size verdict: EXACTLY ONE per file (#701) -------------------------
    # A classified file gets its per-type budget and NOT the generic
    # production-LOC one: bloat_spec() returning a spec IS the statement "this
    # file type has its own budget", and applying the code thresholds on top
    # contradicts it. Before #701 both ran, so classified markdown produced two
    # rows for one problem (two categories, two different numbers), and a docs
    # page UNDER its own doc_md budget was still flagged at the 300 code
    # threshold — a threshold calibrated against a different meaning of "line"
    # (markdown has no comment/test exclusion, so production LOC degenerates
    # into "lines minus blanks").
    #
    # `over` is set by whichever branch fires, NOT by file-length alone: it
    # drives the reasoned-decline emit below, which is what backs
    # audit-decomposition.md's "every size finding pairs with a seam or a
    # recorded decline" contract. Keying it to one branch would silently drop
    # the decline for every classified file.
    over = False
    spec = bloat_spec(path)
    if spec is not None:
        # Per-type budget, measured on TOTAL lines — the deliberate choice
        # recorded in thresholds.yml § bloat_thresholds (#701).
        b_warn, b_high, ftype, category = spec
        n = m["total"]
        if n > b_high:
            over = True
            emit(
                path,
                1,
                category,
                "%s exceeds high threshold: %d lines (>%d)" % (ftype, n, b_high),
                "HIGH",
            )
        elif n > b_warn:
            over = True
            emit(
                path,
                1,
                category,
                "%s exceeds warning threshold: %d lines (>%d)" % (ftype, n, b_warn),
                "MEDIUM",
            )
    elif m["production"] > high:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d high); %s" % (m["production"], high, metrics),
            "HIGH",
        )
    elif m["production"] > warn:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d warning); %s" % (m["production"], warn, metrics),
            "MEDIUM",
        )

    # --- Bundle-aware split guidance (#700) --------------------------------
    # A memory bundle gets its OWN split shape, and the generic markdown
    # heading-cluster seam is SUPPRESSED for it — the same one-verdict move
    # #701 made for size, applied to the seam. Emitting a `seam 40-96:` row for
    # an index would be actively wrong guidance: an index splits by TOPIC
    # CLUSTER, not by line range, and a concept split that does not also add an
    # index line silently orphans the extracted half (#669's `memory-orphan`,
    # the never-recalled failure).
    #
    # Gated on `over`, so a bundle file inside its budget emits NOTHING.
    kind = bundle_kind(path)
    if kind:
        if over:
            names = bundle_sections(lines)
            if kind == "index":
                if len(names) >= 2:
                    emit(
                        path,
                        1,
                        "decomposition-seam",
                        "index split: %d topic clusters (%s) -> index-<topic>.md; "
                        "root keeps one pointer line per sub-index"
                        % (len(names), ", ".join(names[:5])),
                        "HIGH",
                    )
                else:
                    emit(
                        path,
                        1,
                        "decomposition-seam",
                        "declined: index has no topic clusters to split on "
                        "(%d sections) — trim entries instead" % len(names),
                        "LOW",
                    )
            elif len(names) >= 2:
                # Two lessons in one file: extract the second, and REQUIRE its
                # index line in the same breath.
                emit(
                    path,
                    1,
                    "decomposition-seam",
                    "concept split: extract %s to %s/%s.md AND add its index "
                    "line (an extracted concept with no index line is an orphan)"
                    % (names[1], concept_dir(path), names[1]),
                    "HIGH",
                )
            else:
                emit(
                    path,
                    1,
                    "decomposition-seam",
                    "declined: single lesson — no second concept to extract "
                    "(%d sections); tighten the prose instead" % len(names),
                    "LOW",
                )
        return

    if not lang:
        return

    clusters = cluster_units(units)
    prefixes = []
    for c in clusters:
        if c.prefix not in prefixes:
            prefixes.append(c.prefix)

    # --- Category: god-module ---------------------------------------------
    # Size alone is not a god module. The signal is size AND many top-level
    # units AND several distinct concerns — the coupling half stays with
    # audit-architecture, which now consumes this LOC number instead of
    # re-deriving it from its own copy of the counting rules.
    if (
        m["production"] > warn
        and m["units"] > god_units
        and len(prefixes) >= god_concerns
    ):
        emit(
            path,
            1,
            "god-module",
            "%d production LOC, %d top-level units, %d concerns (%s)"
            % (
                m["production"],
                m["units"],
                len(prefixes),
                ", ".join(prefixes[:5]),
            ),
            "MEDIUM",
        )

    # --- Category: decomposition-seam --------------------------------------
    noun = UNIT_NOUN.get(lang, "unit")
    seams = 0
    # A .d.ts holds no runtime code to extract (#726), so it yields no seam —
    # and, because the shape row below is gated on `seams > 0`, no shape row
    # either. It still falls through to the reasoned decline, which is the
    # point: a declaration file is EXAMINED and found unsplittable, not skipped.
    # Silence would be indistinguishable from "not scanned".
    for c in [] if is_decl_file(path) else clusters:
        span = c.end - c.start + 1
        if len(c.units) < seam_min_units or span < seam_min_lines:
            continue
        count, callers = fan_in(lines, c, units)
        if count == 0:
            fan = "no external references"
        elif count <= seam_max_fanin and callers:
            fan = "fan-in %d <- %s" % (count, callers)
        else:
            fan = "fan-in %d" % count
        emit(
            path,
            c.start,
            "decomposition-seam",
            "seam %d-%d: %s %s_* family (%d units, %s) -> %s"
            % (
                c.start,
                c.end,
                noun,
                c.prefix,
                len(c.units),
                fan,
                target_path(path, c.prefix),
            ),
            "HIGH",
        )
        seams += 1

    # --- The split SHAPE (#725) --------------------------------------------
    # The seam rows above say WHERE to cut. This says what the result should
    # LOOK LIKE — a package dir, a barrel index, a sourced fragment. Without it
    # the audit lens hands a backlog reader a bare line range weeks after the
    # sweep, with none of the PR context that would make it interpretable; the
    # review lens, whose reader has the diff on screen, had the better guidance.
    #
    # Gated on `seams > 0`, NOT merely `over`. The `over and seams == 0` arm
    # below emits a reasoned decline — "no low-coupling seam found", "single
    # cohesive unit" — and a shape row beside it would contradict its own
    # neighbour, telling the reader to build a package dir out of a file the
    # scanner just said has nothing to cut. Shape accompanies a real seam; a
    # decline stands alone. (Same one-verdict discipline as #700's bundle
    # suppression, applied to the language path.)
    #
    # Unreachable for a memory bundle by CONSTRUCTION: the bundle branch above
    # returns before this point, so an index/concept never receives generic md
    # advice. Fixtured anyway — an invariant that holds by construction is one
    # refactor away from not holding.
    # `lang` is non-empty here — the `if not lang: return` above this point
    # guarantees it — so SPLIT_SHAPE_FALLBACK is UNREACHABLE in this lens, and
    # deliberately so rather than untested: only the review lens sizes a file
    # with no segmenter (.rb, .java, .c), because only it is handed an arbitrary
    # diff. Recorded here rather than given a test that cannot fail
    # ([[surviving-mutation-may-be-a-real-no-op]]); the fallback IS exercised,
    # through sizing.py, by tests/validate-sizing-scanner.sh's
    # test_unknown_language_still_emits_a_seam_row (named, so the claim is
    # checkable rather than a cross-file assertion the reader must take on
    # trust). If a language is ever added to EXT_LANG without a segmenter, the
    # invariant behind "unreachable" breaks — and the shape/segmenter key-set
    # test in validate-shared-scanner-sync.sh is what fails first.
    if seams > 0:
        emit(
            path,
            1,
            "decomposition-seam",
            "split shape for %s: %s" % (lang, split_shape(lang)),
            "MEDIUM",
        )

    # --- Reasoned decline --------------------------------------------------
    # A file over threshold with no seam is a RESULT, not a silence. A generated
    # artifact, a lookup table, one exhaustive match — long and correct. Record
    # why, so "no seam" can never be mistaken for "not examined"; the finding
    # carries the reason into the baseline= acknowledgment.
    if over and seams == 0:
        generated = any(GENERATED_RE.search(ln) for ln in lines[:20])
        # Ahead of `generated` on purpose (#726): a .d.ts is very often ALSO
        # banner-marked as generated, and "type declaration file" is the more
        # specific fact — it explains why there is nothing to extract even for a
        # hand-maintained one, which the generated reason does not.
        if is_decl_file(path):
            reason = "type declaration file — no runtime units to extract"
        elif generated:
            reason = "generated file — regenerate rather than split"
        elif m["units"] <= cohesive_max_units:
            reason = "single cohesive unit — no internal seam to cut"
        elif m["comment_pct"] >= 50:
            reason = "majority prose/comment — length is documentation, not logic"
        else:
            reason = "no low-coupling seam found — units are mutually referential"
        emit(
            path,
            1,
            "decomposition-seam",
            "declined: %s (%d production LOC, %d top-level units)"
            % (reason, m["production"], m["units"]),
            "LOW",
        )


def main(argv: list[str]) -> int:
    if len(argv) < 2 or not argv[1]:
        sys.stderr.write("Usage: patterns.py <file-list>\n")
        return 1

    file_list = argv[1]
    try:
        with open(file_list, "r", encoding="utf-8", errors="replace") as fh:
            paths = [ln.rstrip("\n") for ln in fh]
    except OSError:
        sys.stderr.write("Error: file list not found: " + file_list + "\n")
        return 1

    for path in paths:
        if not path:
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                lines = fh.read().splitlines()
        except OSError:
            continue
        if any(_fnmatch.fnmatchcase(path, g) for g in SKIP_GLOBS):
            continue
        scan_file(path, lines)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
