#!/usr/bin/env python3
"""check-decomposition — Deterministic Pre-Scan (Python primary implementation).

Sizing + language-aware segmentation. Replaces the production-LOC counting prose
that was duplicated across audit-code-health, audit-architecture and
audit-ai-config (issue #663) with one deterministic implementation, and turns the
result from a line count into an actionable **decomposition seam**.

Python 3.11+ primary implementation behind the language-agnostic TSV contract;
the sibling patterns.sh is the portable bash fallback (it exec's this file when a
python3>=3.11 is present). Both emit byte-identical findings — the parity is
pinned by tests/validate-python-ports.sh and the behavior by
tests/validate-decomposition-detectors.sh. See CLAUDE.md § Key conventions.

Input:  argv[1] = file containing paths to scan (one per line)
Output: TSV to stdout: file<TAB>line<TAB>category<TAB>evidence<TAB>certainty

The 5-column contract is NOT widened. A seam is a per-file SPAN, so `line`
carries the seam START and the end line, unit names, fan-in and proposed target
path are encoded as structured text inside `evidence`:

    src/parser.rs<TAB>412<TAB>decomposition-seam<TAB>seam 412-680: fn parse_* \
family (6 units, fan-in 1 <- parse_entry) -> src/parser/parse.rs<TAB>HIGH

Every other check-* skill and all three parity gates keep the contract they have.
The audit-decomposition agent parses this evidence into line_start/line_end.

Thresholds are env-overridable (DECOMP_*, plus the CLAUDE_MD_*/SKILL_*/AGENT_*/
DOC_* bloat vars inherited from check-ai-config when the bloat table moved here).

Exit codes:
  0 = success (zero or more findings)
  1 = usage error (missing argument) or file list not found
"""

from __future__ import annotations

import fnmatch as _fnmatch
import os
import re
import sys

# The LOC engine and prose spec live in sibling modules (#772). Both entry
# scanners were over the 800 production-LOC py budget and could not be split
# until tests/validate-shared-scanner-sync.sh learned pair members that span
# several files.
#
# sys.path seeding rather than a package: this file is executed directly
# (`python3 patterns.py`, which is how the sibling patterns.sh shim exec's it), so there
# is no package context and a relative import would fail. The same idiom as
# ship-issue/split-verify.py.
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from loc_engine import (  # noqa: E402
    Unit,
    _int_env,
    emit,
    find_units,
    is_decl_file,
    lang_of,
    measure,
    split_shape,
)
from prose_spec import (  # noqa: E402
    bloat_spec,
    bundle_kind,
    bundle_seam_rows,
)

# Non-source files skipped wholesale. Markdown is deliberately ABSENT: this
# scanner segments prose by heading hierarchy and owns doc-file-bloat.
SKIP_GLOBS = (
    "*.lock",
    "*lock.json",
    "*go.sum",
    "*.txt",
    "*.json",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.ini",
    "*.cfg",
    "*.conf",
)

# Markers that make a long file legitimate — a generated artifact is not a
# decomposition candidate, and saying so is a finding, not a silent drop.
GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated",
    re.IGNORECASE,
)


# Identifier tokens for the fan-in scan. A MAXIMAL run is what makes membership
# equivalent to a \bNAME\b regex — and, unlike an escaped alternation, it is
# reproducible verbatim in the awk fallback, so the two impls agree by
# construction rather than by two hand-matched regex dialects.
#
# NOT shared with sizing.py: the fan-in scan is an audit-lens concern, and the
# review lens has no cluster coupling analysis to run it over.
TOKEN_RE = re.compile(r"[A-Za-z0-9_$]+")

# Noun used in seam evidence, per language. NOT shared with sizing.py — only
# this lens emits line-range seam rows, so the review lens has nowhere to spend a
# unit noun and copying the table there would add a lookup nothing reads (#730).
# The split SHAPE below is the opposite case: both lenses emit it, which is
# exactly why it IS shared (#725).
UNIT_NOUN = {
    "py": "def",
    "js": "function",
    # Not "function": a TS top-level unit is as often a type-level declaration
    # (interface/type/enum) as a callable, and the noun goes into seam evidence
    # a human reads. "declaration" is the one word true of every ts arm.
    "ts": "declaration",
    "rs": "fn",
    "go": "func",
    "sh": "function",
    "md": "section",
    # Same argument as ts: a Swift top-level unit is as often a TYPE
    # (struct/protocol/enum/extension) as a callable, so "func" would be wrong
    # for most rows. "declaration" is the one word true of every swift arm.
    "swift": "declaration",
}


class Cluster:
    """A maximal run of CONSECUTIVE same-family units — contiguous by
    construction, which is what makes the span a single mechanical move."""

    __slots__ = ("prefix", "units", "start", "end")

    def __init__(self, prefix: str, units: list[Unit]) -> None:
        self.prefix = prefix
        self.units = units
        self.start = units[0].start
        self.end = units[-1].end


def cluster_units(units: list[Unit]) -> list[Cluster]:
    """Group ADJACENT units sharing a family prefix.

    Adjacency is by unit INDEX, not merely by same-prefix order: a test unit (or
    any other family) sitting between two same-family units breaks the run. That
    matters because the span is meant to be a single mechanical move — a
    `render_*` trio interleaved with eight test functions spans 230 lines that
    cannot be lifted out without dragging the tests along, so it is not a seam.
    """
    clusters: list[Cluster] = []
    run: list[Unit] = []
    last_idx = -2
    for idx, u in enumerate(units):
        if u.is_test:
            continue
        if run and run[-1].prefix == u.prefix and idx == last_idx + 1:
            run.append(u)
        else:
            if run:
                clusters.append(Cluster(run[0].prefix, run))
            run = [u]
        last_idx = idx
    if run:
        clusters.append(Cluster(run[0].prefix, run))
    return clusters


def fan_in(lines: list[str], cluster: Cluster, units: list[Unit]) -> tuple[int, str]:
    """How much of the REST of the file reaches into this cluster.

    Returns (reference count, comma-joined names of the referencing top-level
    units, capped at 3). A low fan-in is the signal that the span is a
    low-coupling cut point — the whole point of naming a seam rather than a size.
    """
    names = set(u.name for u in cluster.units)
    count = 0
    callers: list[str] = []
    for idx, line in enumerate(lines, start=1):
        if cluster.start <= idx <= cluster.end:
            continue
        if not (names & set(TOKEN_RE.findall(line))):
            continue
        count += 1
        for u in units:
            if u.start <= idx <= u.end and u.name not in callers:
                callers.append(u.name)
                break
    callers.sort()
    return count, ", ".join(callers[:3])


def target_path(path: str, prefix: str) -> str:
    """Where the seam should move to: a sibling module named for the family,
    under a directory named for the file it came from."""
    if "/" in path:
        directory, base = path.rsplit("/", 1)
    else:
        directory, base = "", path
    stem, dot, ext = base.rpartition(".")
    if not dot:
        stem, ext = base, ""
    suffix = ("." + ext) if ext else ""
    inner = stem + "/" + prefix + suffix
    return (directory + "/" + inner) if directory else inner


def scan_file(path: str, lines: list[str]) -> None:
    lang = lang_of(path)
    units = find_units(lines, lang)
    m = measure(lines, lang, units)

    warn = _int_env("DECOMP_LOC_WARN", 300)
    high = _int_env("DECOMP_LOC_HIGH", 500)
    seam_min_units = _int_env("DECOMP_SEAM_MIN_UNITS", 3)
    seam_min_lines = _int_env("DECOMP_SEAM_MIN_LINES", 40)
    seam_max_fanin = _int_env("DECOMP_SEAM_MAX_FANIN", 3)
    god_units = _int_env("DECOMP_GOD_UNITS", 12)
    god_concerns = _int_env("DECOMP_GOD_CONCERNS", 3)
    cohesive_max_units = _int_env("DECOMP_COHESIVE_MAX_UNITS", 2)

    metrics = (
        "%d total, %d comment (%d%%), %d blank, %d test-excluded, "
        "max nesting %d, %d top-level units"
        % (
            m["total"],
            m["comment"],
            m["comment_pct"],
            m["blank"],
            m["test_excluded"],
            m["max_depth"],
            m["units"],
        )
    )

    # --- Size verdict: EXACTLY ONE per file (#701) -------------------------
    # A classified file gets its per-type budget and NOT the generic
    # production-LOC one: bloat_spec() returning a spec IS the statement "this
    # file type has its own budget", and applying the code thresholds on top
    # contradicts it. Before #701 both ran, so classified markdown produced two
    # rows for one problem (two categories, two different numbers), and a docs
    # page UNDER its own doc_md budget was still flagged at the 300 code
    # threshold — a threshold calibrated against a different meaning of "line"
    # (markdown has no comment/test exclusion, so production LOC degenerates
    # into "lines minus blanks").
    #
    # `over` is set by whichever branch fires, NOT by file-length alone: it
    # drives the reasoned-decline emit below, which is what backs
    # audit-decomposition.md's "every size finding pairs with a seam or a
    # recorded decline" contract. Keying it to one branch would silently drop
    # the decline for every classified file.
    over = False
    spec = bloat_spec(path)
    if spec is not None:
        # Per-type budget, measured on TOTAL lines — the deliberate choice
        # recorded in thresholds.yml § bloat_thresholds (#701).
        b_warn, b_high, ftype, category = spec
        n = m["total"]
        if n > b_high:
            over = True
            emit(
                path,
                1,
                category,
                "%s exceeds high threshold: %d lines (>%d)" % (ftype, n, b_high),
                "HIGH",
            )
        elif n > b_warn:
            over = True
            emit(
                path,
                1,
                category,
                "%s exceeds warning threshold: %d lines (>%d)" % (ftype, n, b_warn),
                "MEDIUM",
            )
    elif m["production"] > high:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d high); %s" % (m["production"], high, metrics),
            "HIGH",
        )
    elif m["production"] > warn:
        over = True
        emit(
            path,
            1,
            "file-length",
            "%d production LOC (>%d warning); %s" % (m["production"], warn, metrics),
            "MEDIUM",
        )

    # --- Bundle-aware split guidance (#700) --------------------------------
    # A memory bundle gets its OWN split shape, and the generic markdown
    # heading-cluster seam is SUPPRESSED for it — the same one-verdict move
    # #701 made for size, applied to the seam. Emitting a `seam 40-96:` row for
    # an index would be actively wrong guidance: an index splits by TOPIC
    # CLUSTER, not by line range, and a concept split that does not also add an
    # index line silently orphans the extracted half (#669's `memory-orphan`,
    # the never-recalled failure).
    #
    # Gated on `over`, so a bundle file inside its budget emits NOTHING.
    # The ROWS come from the shared `bundle-seam-py` region so both lenses agree
    # on the shape; this lens's DISPOSITION is to emit every one of them,
    # including the LOW `declined:` rows — a backlog reader needs to see that a
    # file was examined and found unsplittable, since silence here would be
    # indistinguishable from "not scanned".
    kind = bundle_kind(path)
    if kind:
        if over:
            for category, evidence, certainty in bundle_seam_rows(path, lines, kind):
                emit(path, 1, category, evidence, certainty)
        return

    if not lang:
        return

    clusters = cluster_units(units)
    prefixes = []
    for c in clusters:
        if c.prefix not in prefixes:
            prefixes.append(c.prefix)

    # --- Category: god-module ---------------------------------------------
    # Size alone is not a god module. The signal is size AND many top-level
    # units AND several distinct concerns — the coupling half stays with
    # audit-architecture, which now consumes this LOC number instead of
    # re-deriving it from its own copy of the counting rules.
    if (
        m["production"] > warn
        and m["units"] > god_units
        and len(prefixes) >= god_concerns
    ):
        emit(
            path,
            1,
            "god-module",
            "%d production LOC, %d top-level units, %d concerns (%s)"
            % (
                m["production"],
                m["units"],
                len(prefixes),
                ", ".join(prefixes[:5]),
            ),
            "MEDIUM",
        )

    # --- Category: decomposition-seam --------------------------------------
    noun = UNIT_NOUN.get(lang, "unit")
    seams = 0
    # A .d.ts holds no runtime code to extract (#726), so it yields no seam —
    # and, because the shape row below is gated on `seams > 0`, no shape row
    # either. It still falls through to the reasoned decline, which is the
    # point: a declaration file is EXAMINED and found unsplittable, not skipped.
    # Silence would be indistinguishable from "not scanned".
    for c in [] if is_decl_file(path) else clusters:
        span = c.end - c.start + 1
        if len(c.units) < seam_min_units or span < seam_min_lines:
            continue
        count, callers = fan_in(lines, c, units)
        if count == 0:
            fan = "no external references"
        elif count <= seam_max_fanin and callers:
            fan = "fan-in %d <- %s" % (count, callers)
        else:
            fan = "fan-in %d" % count
        emit(
            path,
            c.start,
            "decomposition-seam",
            "seam %d-%d: %s %s_* family (%d units, %s) -> %s"
            % (
                c.start,
                c.end,
                noun,
                c.prefix,
                len(c.units),
                fan,
                target_path(path, c.prefix),
            ),
            "HIGH",
        )
        seams += 1

    # --- The split SHAPE (#725) --------------------------------------------
    # The seam rows above say WHERE to cut. This says what the result should
    # LOOK LIKE — a package dir, a barrel index, a sourced fragment. Without it
    # the audit lens hands a backlog reader a bare line range weeks after the
    # sweep, with none of the PR context that would make it interpretable; the
    # review lens, whose reader has the diff on screen, had the better guidance.
    #
    # Gated on `seams > 0`, NOT merely `over`. The `over and seams == 0` arm
    # below emits a reasoned decline — "no low-coupling seam found", "single
    # cohesive unit" — and a shape row beside it would contradict its own
    # neighbour, telling the reader to build a package dir out of a file the
    # scanner just said has nothing to cut. Shape accompanies a real seam; a
    # decline stands alone. (Same one-verdict discipline as #700's bundle
    # suppression, applied to the language path.)
    #
    # Unreachable for a memory bundle by CONSTRUCTION: the bundle branch above
    # returns before this point, so an index/concept never receives generic md
    # advice. Fixtured anyway — an invariant that holds by construction is one
    # refactor away from not holding.
    # `lang` is non-empty here — the `if not lang: return` above this point
    # guarantees it — so SPLIT_SHAPE_FALLBACK is UNREACHABLE in this lens, and
    # deliberately so rather than untested: only the review lens sizes a file
    # with no segmenter (.rb, .java, .c), because only it is handed an arbitrary
    # diff. Recorded here rather than given a test that cannot fail
    # ([[surviving-mutation-may-be-a-real-no-op]]); the fallback IS exercised,
    # through sizing.py, by tests/validate-sizing-scanner.sh's
    # test_unknown_language_still_emits_a_seam_row (named, so the claim is
    # checkable rather than a cross-file assertion the reader must take on
    # trust). If a language is ever added to EXT_LANG without a segmenter, the
    # invariant behind "unreachable" breaks — and the shape/segmenter key-set
    # test in validate-shared-scanner-sync.sh is what fails first.
    if seams > 0:
        emit(
            path,
            1,
            "decomposition-seam",
            "split shape for %s: %s" % (lang, split_shape(lang)),
            "MEDIUM",
        )

    # --- Reasoned decline --------------------------------------------------
    # A file over threshold with no seam is a RESULT, not a silence. A generated
    # artifact, a lookup table, one exhaustive match — long and correct. Record
    # why, so "no seam" can never be mistaken for "not examined"; the finding
    # carries the reason into the baseline= acknowledgment.
    if over and seams == 0:
        generated = any(GENERATED_RE.search(ln) for ln in lines[:20])
        # Ahead of `generated` on purpose (#726): a .d.ts is very often ALSO
        # banner-marked as generated, and "type declaration file" is the more
        # specific fact — it explains why there is nothing to extract even for a
        # hand-maintained one, which the generated reason does not.
        if is_decl_file(path):
            reason = "type declaration file — no runtime units to extract"
        elif generated:
            reason = "generated file — regenerate rather than split"
        elif m["units"] <= cohesive_max_units:
            reason = "single cohesive unit — no internal seam to cut"
        elif m["comment_pct"] >= 50:
            reason = "majority prose/comment — length is documentation, not logic"
        else:
            reason = "no low-coupling seam found — units are mutually referential"
        emit(
            path,
            1,
            "decomposition-seam",
            "declined: %s (%d production LOC, %d top-level units)"
            % (reason, m["production"], m["units"]),
            "LOW",
        )


def main(argv: list[str]) -> int:
    if len(argv) < 2 or not argv[1]:
        sys.stderr.write("Usage: patterns.py <file-list>\n")
        return 1

    file_list = argv[1]
    try:
        with open(file_list, "r", encoding="utf-8", errors="replace") as fh:
            paths = [ln.rstrip("\n") for ln in fh]
    except OSError:
        sys.stderr.write("Error: file list not found: " + file_list + "\n")
        return 1

    for path in paths:
        if not path:
            continue
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as fh:
                lines = fh.read().splitlines()
        except OSError:
            continue
        if any(_fnmatch.fnmatchcase(path, g) for g in SKIP_GLOBS):
            continue
        scan_file(path, lines)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
