#!/usr/bin/env python3
"""ship-issue — review-lens sizing pre-scan (Python primary implementation).

The adversarial pre-PR review had no size lens — a PR could add 900 lines to an
already-oversized file and pass a clean review (issue #695). This scanner
supplies the candidates the new `decomposition` dimension judges.

WHY THIS IS NOT check-decomposition. The audit-lens scanner
(review-audit/skills/check-decomposition) answers "is this file too long?" over a
whole repo. A per-PR gate must answer a DIFFERENT question — "did THIS diff make
it worse?" — because a one-line touch to a pre-existing 1,200-line file is not
the author's debt to pay, and a reviewer that says otherwise gets turned off
within a week. So this scanner is GROWTH-AWARE: it reads a numstat sidecar and
dispositions each file by what the diff actually did to it.

The LOC-counting rules themselves are NOT re-derived. They are physically shared
with check-decomposition through `# >>> shared:loc-*` sentinel regions pinned
byte-for-byte by tests/validate-shared-scanner-sync.sh — the plugins install
independently (workflow without review-audit), so a sourced library is
impossible and a third drifting copy of the LOC rules is exactly what #663 was
filed to kill. Both the Python primaries (`shared:loc-*-py`) and the awk
fallbacks (`shared:loc-*-awk`) are pinned; before #730 only the awk half was,
so the two Python halves — the ones that actually run whenever a python3>=3.11
is present — could drift freely while every gate stayed green.

PROSE FILE-TYPE CLASSIFICATION is shared the same way (`shared:bloat-spec-py`,
#724). Before it, this lens sized every .md by the generic 700/1000 md pair, so
an `agents/*.md` well over its own 250/400 budget — flagged HIGH by the audit
lens — passed a per-PR review in silence. Strictness is a policy dial each lens
owns; what a file IS is a fact about its path and must not fork. The DISPOSITION
below stays this lens's own: classified prose is still growth-graded, so a
one-line touch to a pre-existing over-budget file is LOW, never blocking.

Python 3.11+ primary behind the language-agnostic TSV contract; the sibling
sizing.sh is the portable bash fallback (it exec's this file when a python3>=3.11
is present). Both emit byte-identical findings — parity pinned by
tests/validate-python-ports.sh, behavior by tests/validate-sizing-scanner.sh.
See CLAUDE.md § Key conventions (runtime policy).

Input:  argv[1] = file containing paths to scan (one per line)
        argv[2] = OPTIONAL numstat sidecar: `added<TAB>deleted<TAB>path` rows
                  (`git diff --numstat`). ABSENT => no growth signal, so every
                  over-threshold file is reported at LOW/informational only.
Output: TSV to stdout: file<TAB>line<TAB>category<TAB>evidence<TAB>certainty

The 5-column contract is NOT widened — it is the language boundary every
check-* skill and all three parity gates depend on.

Exit codes:
  0 = success (zero or more findings)
  1 = usage error (missing argument) or file list not found
"""

from __future__ import annotations

import fnmatch as _fnmatch
import os
import re
import sys

# Non-source files skipped wholesale. Mirrors check-decomposition's SKIP_GLOBS.
# Markdown is deliberately ABSENT: prose is the surface this repo feels most
# (#589), and the markdown arm carries its own progressive-disclosure guidance.
SKIP_EXTS = (
    ".lock",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
)

GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated",
    re.IGNORECASE,
)

# >>> shared:loc-tables-py (sync: check-decomposition/patterns.py)
# Per-language unit headers. Each maps a language key to the regex that starts a
# TOP-LEVEL unit. Anchored at line start (no leading indent) so nested defs are
# not mistaken for top-level ones — that anchoring is what makes a unit span a
# genuine cut point.
UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?(?:def|class)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "js": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:async[ \t]+)?"
        r"(?:function|class|const|let|var)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    # TypeScript is its OWN key, not a js alias (#726). The js arm above matches
    # only value-level forms, so every TYPE-level declaration — interface, type,
    # enum, namespace, declare, abstract class — was invisible as a unit, and a
    # types.ts full of interfaces segmented to ~0 units and was declined as a
    # "single cohesive unit". A confident wrong answer, not a silence.
    #
    # ALTERNATION ORDER IS LOAD-BEARING, and it is a two-runtime trap. Python re
    # is leftmost-FIRST (ordered alternation); POSIX awk ERE is leftmost-LONGEST.
    # With bare `const` listed before `const enum`, Python captures the NAME
    # `enum` from `export const enum Delta` while awk captures `Delta` — a silent
    # TSV divergence surfacing only as a parity failure. Listing the two-word
    # forms FIRST makes both runtimes agree by construction rather than by
    # dialect luck. Same reason `abstract class` precedes `class`.
    "ts": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:declare[ \t]+)?(?:async[ \t]+)?"
        r"(?:const[ \t]+enum|abstract[ \t]+class|function|class|const|let|var"
        r"|interface|type|enum|namespace|module)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    # Rust (#727). `impl` is deliberately ONE unit spanning header -> next
    # top-level header, NOT its methods. This decision is load-bearing and will
    # be re-asked, so the reason lives here: (a) the engine's invariant is
    # column-zero anchoring — an indented item is never a unit — and segmenting
    # inside `impl` would break that for one language only, requiring
    # depth-aware segmentation nothing else in the engine has; (b) Rust's own
    # SPLIT_SHAPE ("new subdir module; mod.rs re-exports") moves whole ITEMS,
    # and splitting one type's impl across files is a real Rust smell, so a
    # method-level seam would propose a split the language discourages. The
    # cost is accepted and visible: a 400-line impl stays one unit and can reach
    # the "single cohesive unit" decline.
    #
    # `impl Trait for Type` captures the TYPE, not the trait, so `impl Display
    # for Foo` and `impl Debug for Foo` cluster with `impl Foo` under family
    # `foo` — the family then means "this type's surface". Capturing the trait
    # scattered one type across as many families as it had impls.
    #
    # CHECKED, CORRECT AS-IS (#727): a nested `mod foo { ... }` is a unit, but
    # the items INSIDE it are indented and therefore invisible — intended, and
    # the same column-zero rule that makes impl one unit. An inline module is a
    # cut point (it moves to its own file wholesale); its contents are not.
    # The visibility class admits `:` and `_` so `pub(in crate::foo)` matches
    # (#727). With `[a-z ]+` the parenthesized group failed, the whole `pub`
    # alternative failed with it, and the item went INVISIBLE — absorbed into
    # the previous unit's span. Pre-existing, but it is this issue's own defect
    # class, and it is one character to close. `pub(crate)` / `pub(super)` were
    # always fine; only the path form broke.
    "rs": re.compile(
        r"^(?:(?:pub(?:\([a-z:_ ]+\))?|default|async|unsafe|const"
        r"|extern(?:[ \t]+\"[^\"]*\")?)[ \t]+)*"
        r"(?:macro_rules![ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        # The generic list must tolerate NESTING: `<[^>]*>` stops at the first
        # `>`, so a trait bound like `impl<T: Into<String>> Foo<T>` failed the
        # whole match and the impl went INVISIBLE — reintroducing the exact
        # defect this arm exists to fix, on the commonest form of generic impl.
        # Regex cannot balance arbitrarily; this covers three levels, which is
        # past anything real (`A<B<C>>` already exhausts two).
        # The optional `Trait for` clause is LINEAR-TIME by construction, and it
        # has to be: with `.*[ \t]+for`, a run of N spaces after `impl` can be
        # split between `.*` and `[ \t]+` in O(N) ways at each of O(N) offsets,
        # and the engine tries all of them before failing. Measured on the live
        # pattern: `"impl " + " "*N + "!"` took 0.25 s at N=1000, 1.9 s at
        # N=2000, 14.5 s at N=4000 — cubic, and reached by a stray line of
        # trailing whitespace, not only by a crafted one. Two changes make it
        # flat (0.7 ms at N=16000): the clause must START on a non-space, and
        # the separator before `for` is a SINGLE [ \t] so greedy `.*` has
        # exactly one way to hand off.
        #
        # Everything between `for` and the type is consumed: `&`, a lifetime,
        # `mut`, and `dyn`. Each of these was captured as the unit NAME —
        # a keyword as the family and as a god-module "concern" in human-read
        # evidence, the same wrong-finding class RESERVED_UNIT_NAME exists to
        # prevent for Swift. `dyn` is listed beside `mut` deliberately: fixing
        # one borrow marker and leaving its sibling is exactly the
        # [[harden-one-knob-grep-every-sibling]] recurrence, and trait objects
        # are idiomatic rather than exotic.
        #
        # The path prefix is consumed so the LAST segment is captured. Taking
        # the first meant `impl A for crate::Foo` landed in family `crate`
        # while `impl B for Foo` landed in `foo` — the same type in two
        # families, which is the precise failure the trait-vs-type capture was
        # changed to fix. `(?:IDENT::)*` is a bounded prefix loop, so it stays
        # linear (a 8000-segment path matches in 0.5 ms).
        r"|impl(?:<(?:[^<>]|<(?:[^<>]|<[^<>]*>)*>)*>)?[ \t]+"
        r"(?:[^ \t].*[ \t]for[ \t]+)?(?:&[ \t]*)?"
        r"(?:'[A-Za-z_][A-Za-z0-9_]*[ \t]+)?(?:mut[ \t]+)?(?:dyn[ \t]+)?"
        r"(?:[A-Za-z_][A-Za-z0-9_]*::)*"
        r"([A-Za-z_][A-Za-z0-9_]*)"
        r"|extern[ \t]+crate[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        r"|(?:fn|struct|enum|trait|mod|type|static|const|union)"
        r"[ \t]+([A-Za-z_][A-Za-z0-9_]*))"
    ),
    # Go (#727). A METHOD is named `Receiver_Method`, so family_prefix's
    # split-at-first-underscore clusters every method on one receiver into one
    # family — which is exactly Go's SPLIT_SHAPE ("additional files in the same
    # package"). Before this the receiver clause made the match FAIL outright
    # (`(` is not in [A-Za-z_]), so methods were not mis-named, they were
    # INVISIBLE — silently absorbed into the preceding unit's span, and a
    # method-heavy file was declined as near-cohesive on a unit count of ~2.
    #
    # The final arm names a GROUPED declaration (`var (` / `const (` / `type (`)
    # for its keyword. Same reason: grouped blocks were invisible, not "one unit
    # each". One visible unit per block is the honest count — the engine cannot
    # see into a block it does not segment.
    #
    # ACCEPTED LIMITATION (#727): the header line carries no identifier, so the
    # keyword IS the name and two adjacent blocks of the same kind (two `var (`
    # runs back to back — legal, and gofmt does not merge them) share family
    # `var` and can cluster as one seam. Accepted rather than fixed: the
    # alternatives are worse. A running index would make the name
    # position-dependent, so inserting a block upstream renames every one below
    # it and the TSV churns on an unrelated edit; naming the block for its first
    # inner identifier would require reading past the header, which this
    # line-anchored engine deliberately does not do. The failure mode is also
    # benign — a seam proposing that two adjacent declaration groups move to one
    # file is a reasonable suggestion even when they are unrelated, unlike the
    # pre-#727 behavior where the blocks were invisible and the file was
    # declined as cohesive.
    #
    # CHECKED, CORRECT AS-IS (#727): `//go:generate` and build tags do not
    # interact with GENERATED_RE. That pattern looks for @generated /
    # "Code generated by" / DO NOT EDIT in the first 20 lines; a `//go:generate`
    # directive contains none of them, and the file it generates carries the
    # real "Code generated by ... DO NOT EDIT." banner that SHOULD match. So the
    # generator's source is sized normally and its output is declined as
    # generated — which is the intended split. No fixture: a test asserting a
    # pattern does not match an unrelated string cannot fail
    # ([[surviving-mutation-may-be-a-real-no-op]]).
    "go": re.compile(
        r"^func[ \t]*\([ \t]*(?:[A-Za-z_][A-Za-z0-9_]*[ \t]+)?\*?[ \t]*"
        r"([A-Za-z_][A-Za-z0-9_]*)(?:\[[^\]]*\])?[ \t]*\)[ \t]*"
        r"([A-Za-z_][A-Za-z0-9_]*)"
        r"|^(?:func|type|var|const)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
        r"|^(var|const|type)[ \t]*\("
    ),
    # Swift (#728). Modifiers are a REPEATED optional group, not a fixed
    # sequence: `public final class`, `@objc private static func` and bare
    # `struct` are all real, and Swift imposes no canonical order on them. One
    # `(?:...)*` group covering access levels, `final`/`static`/`class`
    # (type-method), `override`, `@objc`/`@MainActor`-style attributes, and
    # `indirect` matches every ordering without enumerating permutations.
    #
    # `extension` is ONE unit, matching Rust's `impl` (#727). The two are the
    # same construct — a block bundling many methods onto a type — so they must
    # be segmented the same way or the cohesive-decline path treats equivalent
    # code differently by language. If #727 re-decides `impl`, this arm changes
    # in the SAME PR; neither may move alone.
    #
    # `associatedtype` is deliberately NOT here, though the issue listed it.
    # Swift allows it only INSIDE a protocol body, so it is never a top-level
    # declaration — and an arm for it is not merely dead, it is harmful: a
    # protocol whose body is written unindented (legal Swift) would have each
    # `associatedtype` lifted into a phantom top-level unit, corrupting the very
    # count the cohesive-decline and seam paths read. Found by the mutation
    # round: deleting the arm changed nothing, and the reachability check that
    # followed showed the only inputs it fires on are invalid Swift or that
    # false positive ([[surviving-mutation-may-be-a-real-no-op]]). It stays in
    # RESERVED_UNIT_NAME, since it is still a keyword no NAME may be.
    #
    # A keyword captured as the NAME is rejected downstream by
    # RESERVED_UNIT_NAME — see the note there for why that is a filter rather
    # than a negative lookahead.
    "swift": re.compile(
        r"^(?:(?:public|private|internal|fileprivate|open|final|static|class"
        r"|override|indirect|@[A-Za-z_][A-Za-z0-9_]*)[ \t]+)*"
        r"(?:func|class|struct|enum|protocol|extension|actor|typealias)"
        r"[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
    "sh": re.compile(
        r"^(?:function[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]*\([ \t]*\)|"
        r"^function[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
}

# Comment-line shapes per language (used for the comment/production split).
COMMENT_RE = {
    "py": re.compile(r"^[ \t]*#"),
    "sh": re.compile(r"^[ \t]*#"),
    "js": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "ts": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "rs": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "go": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    # Swift (#728). `///` and `/**` doc comments are matched by the `//` and
    # `/*` alternatives respectively — the issue notes this works "by luck" for
    # the `//` arm, so the fixture asserts the production-LOC NUMBER changes on
    # a doc-commented file rather than trusting the shape by inspection.
    "swift": re.compile(r"^[ \t]*(?://|/\*|\*)"),
}

# A unit header that marks the unit as TEST code. Replaces the per-language
# exclusion prose the three agents each carried a drifting copy of. Because unit
# SPANS are already computed, exclusion is per-unit and exact rather than the
# "to end of file" approximation the prose specified.
TEST_UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?def[ \t]+test_|^class[ \t]+Test"),
    "js": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    "ts": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    # NB: `rs` is deliberately absent — Rust marks tests with an ATTRIBUTE on
    # the preceding line, so it lives in ATTR_TEST_RE below. It USED to sit here
    # too, read by a hardcoded `lang == "rs"` attribute branch; #728 moved it to
    # the table that describes what it actually is. Keeping a copy here would be
    # two spellings of one fact, and now that the same-line path no longer
    # excludes rs by name, a stale copy would be live code.
    #
    # The optional receiver clause keeps a TESTIFY-style method
    # (`func (s *Suite) TestFoo`) test-classified (#727). Once UNIT_RE["go"]
    # learned to segment methods, anchoring on `^func[ \t]+Test` alone stopped
    # matching them — the suite method became a production unit and its body
    # counted toward production LOC.
    # The prefix needs a BOUNDARY. Go's rule is `func TestXxx` where Xxx does
    # not begin with a lowercase letter, so a bare prefix match classifies
    # `Testify`, `Benchmarking` and `Exampler` as test code and silently drops
    # their lines from production LOC and the unit count — a wrong number
    # feeding god-module, seam and decline verdicts, with no visible error.
    # Requiring an uppercase letter, `_`, or the end of the name (`(`) after
    # the prefix matches the convention exactly. The bare-func arm had this
    # weakness before #727; extending the prefix to every receiver METHOD would
    # have widened it considerably, so both arms are anchored here.
    "go": re.compile(
        r"^func[ \t]+(?:Test|Benchmark|Fuzz|Example)(?:[A-Z_]|[ \t]*\()"
        r"|^func[ \t]*\([^)]*\)[ \t]*(?:Test|Benchmark|Fuzz|Example)(?:[A-Z_]|[ \t]*\()"
    ),
    "sh": re.compile(r"^(?:function[ \t]+)?test_[A-Za-z0-9_]*[ \t]*\([ \t]*\)"),
    # Swift XCTest (#728) — the SAME-LINE half of Swift's two test conventions:
    # a `func test…` (any modifier prefix) or an `XCTestCase` subclass. The
    # swift-testing half is an ATTRIBUTE on the preceding line and lives in
    # ATTR_TEST_RE below; both ship because the ecosystem is mid-migration.
    #
    # The class arm keys off the `: XCTestCase` conformance rather than a name
    # convention, since Swift test classes are not required to be named Test*.
    # `[^{]*` spans any other protocols in the conformance list without running
    # into the body.
    "swift": re.compile(
        r"^(?:(?:public|private|internal|fileprivate|open|final|static|class"
        r"|override|indirect|@[A-Za-z_][A-Za-z0-9_]*)[ \t]+)*"
        r"(?:func[ \t]+test|class[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*:[^{]*XCTestCase)"
    ),
}

# An ATTRIBUTE line that marks the NEXT unit as test code (#728).
#
# Generalized from a hardcoded `lang == "rs"` branch in find_units(). Rust's
# `#[test]` and swift-testing's `@Test` are the same construct — a marker on the
# line BEFORE the unit header — and hardcoding a second language would have made
# three copies of one idea across four files. Table membership now drives the
# `pending_test` path, so a third attribute-marking language is one entry.
#
# A language may appear in BOTH tables: Swift does, since XCTest is same-line
# while swift-testing is attribute-marked, which is why find_units() checks the
# two paths independently rather than as an either/or.
ATTR_TEST_RE = {
    "rs": re.compile(r"^[ \t]*#\[(?:cfg\(test\)|test)\]"),
    "swift": re.compile(r"^[ \t]*@Test\b"),
}

# Words that must never be accepted as a captured unit NAME (#728).
#
# Swift's `class` is in both the modifier group and the keyword alternation of
# UNIT_RE, so a malformed-but-parseable spelling (`open class override Foo`)
# matches `class` as the keyword and hands back `override` as the name. That is
# not a cosmetic mislabel: the name becomes the seam family and a god-module
# "concern" in evidence a human reads, so a keyword there is a WRONG FINDING.
#
# Enforced as a post-match FILTER rather than a negative lookahead, on purpose.
# POSIX awk ERE has no lookahead at all, so a lookahead would be a Python-only
# construct — the two impls would disagree on exactly these lines, and the
# divergence would surface as a parity failure rather than as the fix it looks
# like. A set membership test transcribes to awk verbatim (is_reserved_name).
#
# Only `swift` populates this today; find_units consults it for every language
# so a future one needs no new branch.
RESERVED_UNIT_NAME = {
    "swift": {
        "public",
        "private",
        "internal",
        "fileprivate",
        "open",
        "final",
        "static",
        "class",
        "override",
        "indirect",
        "func",
        "struct",
        "enum",
        "protocol",
        "extension",
        "actor",
        "typealias",
        "associatedtype",
    },
}

# Whole-file test-region markers: everything from the match to EOF is test code.
# Kept for the two cases the prose named that are genuinely region-scoped rather
# than unit-scoped.
TEST_REGION_RE = {
    "py": re.compile(r"^if[ \t]+__name__"),
    # COLUMN-ZERO only (#727), matching the pending-test attribute guard in
    # find_units. The `[ \t]*` this used to carry made a NESTED marker — a
    # `#[cfg(test)] mod tests` indented inside an outer `mod` — engage the
    # whole-file region path. That marker is not itself a unit header (units are
    # column-zero anchored), so the stop-computation below latched onto whatever
    # top-level unit happened to follow and excluded everything in between:
    # measured on a 16-line fixture, 11 lines test-excluded and a production fn
    # swallowed whole, for 4 production LOC instead of 10. A nested test module
    # is already covered per-unit by its enclosing unit's span; the region path
    # exists for the CONVENTIONAL trailing placement, which is column-zero.
    "rs": re.compile(r"^#\[cfg\(test\)\]"),
    "sh": re.compile(r"^#[ \t]*-+[ \t]*tests?[ \t]*-+"),
}

# Indent width used to convert leading whitespace into a nesting depth.
NEST_UNIT = {
    "py": 4,
    "js": 2,
    "ts": 2,
    "rs": 4,
    "go": 4,
    "sh": 4,
    "md": 2,
    "swift": 4,
}

# Blankness and indent are defined by REGEX, not str.strip()/str.lstrip(): the
# latter are unicode-aware (\x0b, \x0c, \x85, NBSP...) while the awk fallback
# under LC_ALL=C is not. Pinning both impls to [ \t] is what keeps the TSV
# byte-identical on a file with exotic whitespace.
BLANK_RE = re.compile(r"^[ \t]*$")
INDENT_RE = re.compile(r"^[ \t]*")

EXT_LANG = {
    "py": "py",
    "js": "js",
    "jsx": "js",
    "mjs": "js",
    "cjs": "js",
    "ts": "ts",
    "tsx": "ts",
    "rs": "rs",
    "go": "go",
    "sh": "sh",
    "bash": "sh",
    "md": "md",
    "markdown": "md",
    "swift": "swift",
}
# <<< shared:loc-tables-py

# >>> shared:split-shape-py (sync: check-decomposition/patterns.py)
# LANGUAGE-SHAPED SPLIT GUIDANCE — shared by BOTH lenses (#725).
#
# Introduced on the review lens alone (#695), which was backwards: the AUDIT lens
# is the one that files a backlog somebody picks up weeks later, with none of the
# PR context that makes a bare line range interpretable. That reader needs the
# shape spelled out most, and had it least — the exact "too generic to act on, so
# nothing gets decomposed" failure #663 was filed against.
#
# Keyed by the same language keys the segmenters use (EXT_LANG's values), so
# advice and measurement can never disagree about what a file IS. That invariant
# is asserted structurally: a language with a segmenter and no shape, or a shape
# for a language nothing segments, fails tests/validate-shared-scanner-sync.sh.
# It is what makes adding a language (#726 TypeScript, #727 Rust/Go, #728 Swift)
# a one-table edit rather than two that must be remembered together.
#
# Each string names the SHAPE of the split, not a generic "consider splitting" —
# the finding has to be actionable or it is noise.
SPLIT_SHAPE = {
    "rs": "new subdir module; mod.rs re-exports the decomposed units",
    "py": "package dir with __init__.py re-exporting the public surface",
    "js": "sibling modules + a barrel index.ts",
    # DIFFERENT from js on purpose (#726). The js shape moves runtime modules;
    # an oversized TypeScript file is usually type-heavy, and its real remedy is
    # to group types by DOMAIN under types/ with a re-exporting barrel — a
    # different instruction, which is why ts needs its own key rather than
    # inheriting the js one through an alias.
    "ts": "types/ dir split by domain + a re-exporting barrel index.ts",
    "go": "additional files in the same package (no import churn)",
    # Swift's idiomatic decomposition is extensions in separate files (#728) —
    # `Foo+Networking.swift`, `Foo+Codable.swift`. DIFFERENT from every other
    # shape here because it needs no re-exporting barrel and no module: Swift
    # types are open for extension across files within a module, so a split
    # costs zero import churn at the call site. Naming the `Type+Concern.swift`
    # convention is what makes the row actionable rather than "consider
    # splitting".
    "swift": "extensions in separate files (Type+Concern.swift), same module",
    "sh": "sourced fragment + an explicit ordered list (split-suite convention)",
    "md": (
        "progressive disclosure: move detail to linked files, leave a one-line pointer"
    ),
}

# The shape for a file whose extension has NO segmenter (.rb, .java, .c, .cpp,
# .kt — all scanned, since none are skipped). Weaker than a language-shaped
# string but still a real destination, which is what keeps every actionable
# over-threshold file yielding exactly one seam row.
#
# It lives INSIDE the shared region on purpose. As a bare literal at each call
# site it was two more unpinned copies of the same fact — the precise shape of
# duplication this region exists to end.
SPLIT_SHAPE_FALLBACK = "extract a cohesive unit into a sibling module"


def split_shape(lang: str) -> str:
    """The split shape for LANG, falling back for an unsegmented language.

    Every consumer goes through this rather than indexing SPLIT_SHAPE directly,
    so the fallback cannot fork the way it already had."""
    return SPLIT_SHAPE.get(lang, SPLIT_SHAPE_FALLBACK)


# <<< shared:split-shape-py

# Per-language review-lens thresholds, overriding the default pair. A 500-line
# Rust file and a 500-line shell script are not the same claim. Languages absent
# here fall through to REVIEW_LOC_WARN/HIGH — adding one is a one-line edit, and
# an unlisted language is sized rather than silently skipped.
#
# Mirrors the per_language block of check-decomposition/thresholds.yml.
PER_LANG_THRESHOLDS = {
    "sh": ("REVIEW_LOC_WARN_SH", "REVIEW_LOC_HIGH_SH", 700, 1000),
    "md": ("REVIEW_LOC_WARN_MD", "REVIEW_LOC_HIGH_MD", 700, 1000),
    "rs": ("REVIEW_LOC_WARN_RS", "REVIEW_LOC_HIGH_RS", 400, 700),
    "go": ("REVIEW_LOC_WARN_GO", "REVIEW_LOC_HIGH_GO", 400, 700),
    # Swift joins rs/go rather than taking the default pair (#728) — a DECIDED
    # value, not an omission. Same rationale: a compiled, type-dense language
    # packs more meaning per line than shell or prose and turns over harder when
    # long. Swift's verbosity (long API names, trailing closures) argues the
    # other way, but that inflates line COUNT without inflating the units-per-
    # file the threshold is a proxy for.
    "swift": ("REVIEW_LOC_WARN_SWIFT", "REVIEW_LOC_HIGH_SWIFT", 400, 700),
}


# >>> shared:loc-helpers-py (sync: check-decomposition/patterns.py)
def _int_env(name: str, default: int) -> int:
    """Read an integer threshold from the environment, falling back to DEFAULT.
    Mirrors _int_env in check-ai-config/patterns.py (and the ${VAR:-N} defaults
    in every patterns.sh) so thresholds.yml values can be passed through by the
    orchestrator without either impl diverging."""
    val = os.environ.get(name, "")
    try:
        return int(val)
    except ValueError:
        return default


def emit(path: str, line_no: int, category: str, evidence: str, certainty: str) -> None:
    """Write one TSV finding row."""
    sys.stdout.write(
        "\t".join((path, str(line_no), category, evidence, certainty)) + "\n"
    )


def lang_of(path: str) -> str:
    """Language key from the file extension, or '' when unrecognized (metrics
    only, no segmenter)."""
    if "." not in path:
        return ""
    return EXT_LANG.get(path.rsplit(".", 1)[-1].lower(), "")


DECL_SUFFIX = ".d.ts"


def is_decl_file(path: str) -> bool:
    """A TypeScript DECLARATION file (*.d.ts), which is type-level by
    construction and has no runtime units to extract (#726).

    Deliberately NOT added to SKIP_GLOBS. A skip makes an over-budget .d.ts
    indistinguishable from an unscanned one, and this scanner's whole discipline
    is that a decline is a RESULT while silence is the bug. So the file is
    measured and sized as usual; only its SEAM is suppressed, and it declines
    with its own reason.

    Matched on the full lowercased path (a case-insensitive suffix test), so
    `Foo.D.TS` on a case-insensitive filesystem classifies the same as
    `foo.d.ts` — the same target must decide alike in every spelling."""
    return path.lower().endswith(DECL_SUFFIX)


# <<< shared:loc-helpers-py


def thresholds_for(lang: str) -> tuple[int, int]:
    """The (warning, high) production-LOC pair for LANG.

    Review-lens defaults are deliberately LOOSER than the audit lens
    (check-decomposition ships 300/500): an audit sweeps a whole repo and can
    afford to nag, a per-PR gate cannot. See thresholds.yml § review_size_thresholds.
    """
    warn = _int_env("REVIEW_LOC_WARN", 500)
    high = _int_env("REVIEW_LOC_HIGH", 800)
    spec = PER_LANG_THRESHOLDS.get(lang)
    if spec is not None:
        warn_var, high_var, warn_def, high_def = spec
        warn = _int_env(warn_var, warn_def)
        high = _int_env(high_var, high_def)
    return warn, high


# >>> shared:loc-unit-py (sync: check-decomposition/patterns.py)
def family_prefix(name: str) -> str:
    """The family key a unit name belongs to — the shared stem that makes
    `parse_entry` / `parse_header` / `parse_body` one cluster.

    snake_case splits at the first underscore; camelCase and PascalCase split at
    the first internal uppercase letter. The result is lowercased so `ParseEntry`
    and `parse_entry` land in the same family.
    """
    cut = name.find("_")
    if cut > 0:
        return name[:cut].lower()
    i = 1
    while i < len(name) and not ("A" <= name[i] <= "Z"):
        i += 1
    return name[:i].lower()


def md_slug(text: str) -> str:
    """Markdown heading text -> an identifier-shaped slug so family_prefix()
    applies unchanged ('Install on Linux' -> 'install_on_linux')."""
    out = []
    prev_us = False
    for ch in INDENT_RE.sub("", text.rstrip()).lower():
        if ("a" <= ch <= "z") or ("0" <= ch <= "9"):
            out.append(ch)
            prev_us = False
        elif not prev_us:
            out.append("_")
            prev_us = True
    return "".join(out).strip("_")


class Unit:
    """One top-level declaration: its name, family, header line and span.

    THE shared representation for both lenses (#730). The review lens
    (ship-issue/sizing.py) previously carried a parallel 4-tuple shape, which was
    the structural reason the two `find_units` bodies could never be compared
    byte-for-byte — and so the reason the Python halves drifted while their awk
    twins stayed pinned. `prefix` is what the audit lens clusters on; the review
    lens does not cluster, but carrying one field it ignores is far cheaper than
    two representations neither gate can align.
    """

    __slots__ = ("name", "prefix", "start", "end", "is_test")

    def __init__(self, name: str, start: int) -> None:
        self.name = name
        self.prefix = family_prefix(name)
        self.start = start
        self.end = start
        self.is_test = False


def find_units(lines: list[str], lang: str) -> list[Unit]:
    """Top-level units in file order, each spanning from its header line to the
    line before the next header (or EOF).

    For markdown, 'top-level' means the shallowest heading depth present, so a
    doc whose sections are all `##` segments by `##` rather than by a lone `#`
    title."""
    units: list[Unit] = []
    if lang == "md":
        heads: list[tuple[int, int, str]] = []  # (depth, line_no, text)
        fenced = False
        for idx, line in enumerate(lines, start=1):
            if line.startswith("```") or line.startswith("~~~"):
                fenced = not fenced
                continue
            if fenced:
                continue
            m = re.match(r"^(#{1,6})[ \t]+(.*)$", line)
            if m:
                heads.append((len(m.group(1)), idx, m.group(2)))
        if not heads:
            return []
        top = min(h[0] for h in heads)
        for depth, line_no, text in heads:
            if depth == top:
                units.append(Unit(md_slug(text) or "section", line_no))
    else:
        rx = UNIT_RE.get(lang)
        if rx is None:
            return []
        test_rx = TEST_UNIT_RE.get(lang)
        attr_rx = ATTR_TEST_RE.get(lang)
        pending_test = False
        for idx, line in enumerate(lines, start=1):
            m = rx.match(line)
            # An attribute line marks the NEXT unit as test code (Rust #[test],
            # swift-testing @Test). Table-driven since #728 — it was a hardcoded
            # `lang == "rs"` branch.
            #
            # ORDER MATTERS, and differs from the pre-#728 code: the unit match
            # is attempted FIRST, and the attribute only CONSUMES the line when
            # the line is not itself a unit header. Rust's `#[test]` always
            # stands alone so this is a no-op there, but swift-testing writes
            # `@Test func foo()` on ONE line — under the old continue-first
            # shape that line would set the flag and be skipped, losing the unit
            # entirely and marking the NEXT (production) unit as a test instead.
            # Only a COLUMN-ZERO attribute may set the flag (#727). Both
            # ATTR_TEST_RE patterns tolerate leading whitespace — rs because the
            # same spelling doubles as the TEST_REGION_RE marker — so an
            # INDENTED attribute inside a block (`#[test]` within
            # `mod tests { ... }`, `@Test` within an XCTestCase body) used to
            # set this flag and then mark the next TOP-LEVEL unit, a PRODUCTION
            # declaration after the block, as test code — silently dropping its
            # lines from production LOC. The guard is language-agnostic because
            # the invariant is: units are column-zero anchored, so an indented
            # attribute cannot be marking one.
            if attr_rx is not None and not line[:1].isspace() and attr_rx.search(line):
                pending_test = True
                if m is None:
                    continue
            if not m:
                continue
            # Join every group that matched. Most arms set exactly one (the
            # rest are None), so this is the old "group(1) else group(2)" for
            # them; Go's method arm sets TWO — receiver and method — and joins
            # them into `Repo_Get`, the underscore family_prefix then splits on.
            name = "_".join(g for g in m.groups() if g)
            if not name:
                continue
            # A keyword captured as a name means the line parsed a modifier as
            # the unit keyword — drop the bogus unit rather than seed a seam
            # family called "override" (#728). The line is still counted by
            # measure(); only the phantom unit disappears.
            #
            # pending_test MUST be cleared on this path. The dropped header is
            # what the attribute was marking, so leaving the flag set carries it
            # onto the NEXT genuine unit and silently marks a PRODUCTION unit as
            # test — removing its lines from production LOC and suppressing the
            # very findings this scanner exists to emit. The guard against one
            # wrong answer would otherwise manufacture another
            # ([[fix-reintroduces-its-own-failure]]).
            if name in RESERVED_UNIT_NAME.get(lang, ()):
                pending_test = False
                continue
            u = Unit(name, idx)
            if pending_test:
                u.is_test = True
                pending_test = False
            elif test_rx is not None and test_rx.search(line):
                # No longer excludes the attribute-marked languages by name
                # (#728). Rust has no TEST_UNIT_RE entry, so dropping the old
                # `lang != "rs"` guard cannot change its behavior; Swift needs
                # BOTH paths live, since XCTest is same-line while swift-testing
                # is attribute-marked.
                u.is_test = True
            units.append(u)

    for i, u in enumerate(units):
        u.end = units[i + 1].start - 1 if i + 1 < len(units) else len(lines)
    return units


# <<< shared:loc-unit-py


# >>> shared:loc-measure-py (sync: check-decomposition/patterns.py)
def measure(lines: list[str], lang: str, units: list[Unit]) -> dict:
    """The generic sizing layer: total / blank / comment / test-excluded /
    production LOC, max nesting depth, and top-level unit count.

    The audit lens (check-decomposition/patterns.py) and the review lens
    (ship-issue/sizing.py) carry byte-identical copies, pinned by
    tests/validate-shared-scanner-sync.sh; the same computation is transcribed
    into awk in the shared:loc-measure-awk region of both bash fallbacks."""
    total = len(lines)
    comment_rx = COMMENT_RE.get(lang)
    region_rx = TEST_REGION_RE.get(lang)

    # Lines inside a test unit, or after a whole-file test-region marker.
    test_lines = set()
    for u in units:
        if u.is_test:
            test_lines.update(range(u.start, u.end + 1))
    if region_rx is not None:
        for idx, line in enumerate(lines, start=1):
            if region_rx.search(line):
                # The region runs to the end of the unit the marker INTRODUCES,
                # not unconditionally to EOF (#727). For the conventional
                # trailing placement these are the same line — the marked unit
                # is the last one — so this is a no-op there. It differs only
                # for a marker in the MIDDLE of a file, where running to EOF
                # excluded every production unit that followed: a `#[cfg(test)]
                # mod tests` at line 5 of an 18-line file excluded 14 lines and
                # reported 3 production LOC instead of 9.
                #
                # Falling back to EOF when no unit follows keeps a marker with
                # no unit after it (a trailing `if __name__` block in py, a
                # `# --- tests ---` banner in sh) excluding its tail as before.
                stop = total
                for u in units:
                    if u.start >= idx:
                        stop = u.end
                        break
                test_lines.update(range(idx, stop + 1))
                break

    blank = 0
    comment = 0
    test_excluded = 0
    max_depth = 0
    nest_unit = NEST_UNIT.get(lang, 4)
    for idx, line in enumerate(lines, start=1):
        if idx in test_lines:
            test_excluded += 1
            continue
        if BLANK_RE.match(line):
            blank += 1
            continue
        if comment_rx is not None and comment_rx.match(line):
            comment += 1
            continue
        depth = len(INDENT_RE.match(line).group(0)) // nest_unit
        if depth > max_depth:
            max_depth = depth

    production = total - blank - comment - test_excluded
    return {
        "total": total,
        "blank": blank,
        "comment": comment,
        "test_excluded": test_excluded,
        "production": production,
        "max_depth": max_depth,
        "units": len([u for u in units if not u.is_test]),
        "comment_pct": (comment * 100 // total) if total else 0,
    }


# <<< shared:loc-measure-py


# UNIT NAMES ARE CURRENTLY UNREACHABLE IN THIS LENS (#730). `find_units` above is
# shared verbatim with check-decomposition, so a markdown unit is now named by
# `md_slug(text) or "section"` rather than the hardcoded "section" this file used
# to carry. That fork was real but LATENT: nothing here surfaces a unit *name* —
# `decline_reason` and every seam row below read `m["units"]`, a COUNT — so the
# unification changes no output today, which is why the differential over a
# markdown fixture stays byte-identical.
#
# Recorded as unreachable rather than given a test that cannot fail. What would
# make it live: any seam row in this lens that names its markdown sections (the
# direction #725's unified split shape and #729's bundle guidance move toward).
# At that moment the two lenses would have named the same heading differently —
# which is the bug this unification pre-empts. The reachable half (md_slug's own
# slugging rules) IS fixtured, in tests/validate-python-ports.sh.
def decline_reason(path: str, lines: list[str], m: dict) -> str:
    """WHY a long file was not flagged as splittable.

    A decline is a RESULT, not a silence — silence is indistinguishable from
    'not examined', and the recorded reason is what a reviewer cites when
    accepting the length. Reasons are reused verbatim from
    check-decomposition/contract.md so a decline reads identically in both lenses.
    """
    # Ahead of `generated` on purpose (#726) — see the matching order in
    # check-decomposition/patterns.py. A .d.ts is often ALSO banner-marked as
    # generated, and "type declaration file" is the more specific fact.
    if is_decl_file(path):
        return "type declaration file — no runtime units to extract"
    for line in lines[:20]:
        if GENERATED_RE.search(line):
            return "generated file — regenerate rather than split"
    if m["units"] <= _int_env("REVIEW_COHESIVE_MAX_UNITS", 2):
        return "single cohesive unit — no internal seam to cut"
    if m["comment_pct"] >= 50:
        return "majority prose/comment — length is documentation, not logic"
    return "no low-coupling seam found — units are mutually referential"


# >>> shared:bloat-spec-py (sync: check-decomposition/patterns.py)
# PROSE FILE-TYPE CLASSIFICATION — shared by BOTH lenses (#724).
#
# What a markdown file IS is a fact about its PATH, and a fact must not fork.
# Before #724 only the audit lens classified prose; the review lens sized every
# .md by the generic md pair (700/1000), so an over-budget agent definition
# passed a per-PR review silently while the audit sweep called it HIGH. The two
# lenses may differ in STRICTNESS — that is a policy dial each owns — but they
# may not disagree about what the file is.
#
# STRICTNESS IS NOT FORKED EITHER, for these files specifically. Both lenses
# apply the bloat_thresholds numbers verbatim; there is no review-lens override
# table. The review lens is looser than the audit lens for CODE because those
# thresholds count production LOC and a per-PR gate that nags gets turned off.
# That argument does not transfer: bloat budgets are measured on TOTAL lines
# because these files load WHOLE into context, and that cost does not depend on
# which lens is looking. What keeps the review lens survivable here is its
# GROWTH DISPOSITION (sizing.py's scan_file), not a bigger number.
def _glob(path: str, pattern: str) -> bool:
    """`case "$path" in <pattern>)` — an unanchored shell glob over the full
    path. fnmatchcase's `*` crosses '/', matching bash `case` glob semantics."""
    return _fnmatch.fnmatchcase(path, pattern)


def _bundle_root() -> str:
    """The configured memory-bundle root, normalized for glob matching (#700).

    Configurable rather than hardcoded, defaulting to `.claude/memory`. An
    EMPTY value means no bundle is configured: memory classification is off and
    nothing errors.

    Normalization strips a leading `./` and any trailing `/` so that every
    spelling of the same root — `.claude/memory`, `./.claude/memory`,
    `.claude/memory/` — decides alike. An unnormalized root would make the
    glob miss, the file would fall back to the code thresholds, and the scan
    would still exit 0 — the silent fail-open this issue exists to close."""
    root = os.environ.get("MEMORY_BUNDLE_ROOT", ".claude/memory").strip()
    while root.startswith("./"):
        root = root[2:]
    while root.endswith("/"):
        root = root[:-1]
    return root


def bundle_kind(path: str) -> str:
    """Which half of the memory bundle PATH is: "index", "concept", or "" when
    it is not a bundle markdown file (#700).

    Only `*.md` under the root is bundle prose — a `.sh` or `.py` sitting in a
    bundle is code and keeps the code thresholds.

    An index is the file loaded every session to route recall: the root
    `MEMORY.md`, a topic sub-index `index-*.md`, or OKF's `index.md`."""
    root = _bundle_root()
    if not root:
        return ""
    # LITERAL containment, deliberately NOT _glob(). The root is operator
    # configuration, and routing it through fnmatch would interpret any glob
    # metacharacter in it (`[`, `]`, `*`, `?`) as syntax. The bash mirror does
    # NOT: a QUOTED expansion in a `case` pattern (`"$MEMORY_BUNDLE_ROOT"/*.md`)
    # is matched literally by bash. So a root like `weird[x]root` made fnmatch
    # read `[x]` as a character class and miss, while bash matched — the two
    # impls disagreed on the same file, breaking the byte-identical TSV
    # contract, silently and at exit 0. These two tests mirror bash's two arms:
    # `"$ROOT"/*` (root at the start) and `*/"$ROOT"/*` (root nested anywhere).
    if not (path.startswith(root + "/") or ("/" + root + "/") in path):
        return ""
    base = path.rsplit("/", 1)[-1]
    if not base.endswith(".md"):
        return ""
    if base == "MEMORY.md" or base == "index.md" or base.startswith("index-"):
        return "index"
    return "concept"


def bloat_spec(path: str) -> tuple[int, int, str, str] | None:
    """The per-file-type bloat thresholds, migrated verbatim from
    check-ai-config so the move is behavior-preserving. Returns
    (warn, high, file-type label, category) or None when the path is not an
    AI-instruction or documentation file.

    The memory-bundle arm is FIRST (#700): inside a configured bundle, bundle
    rules apply, so a `docs/` or `agents/` directory nested in the bundle
    cannot escape to the arms below and be sized by the wrong budget."""
    kind = bundle_kind(path)
    if kind == "index":
        return (
            _int_env("MEMORY_INDEX_WARN", 150),
            _int_env("MEMORY_INDEX_HIGH", 250),
            "memory index",
            "ai-file-bloat",
        )
    if kind == "concept":
        return (
            _int_env("MEMORY_CONCEPT_WARN", 200),
            _int_env("MEMORY_CONCEPT_HIGH", 350),
            "memory concept",
            "ai-file-bloat",
        )
    if _glob(path, "*/CLAUDE.md") or _glob(path, "*/AGENTS.md"):
        return (
            _int_env("CLAUDE_MD_WARN", 400),
            _int_env("CLAUDE_MD_HIGH", 600),
            "CLAUDE.md",
            "ai-file-bloat",
        )
    if _glob(path, "*/skills/*/SKILL.md"):
        return (
            _int_env("SKILL_WARN", 300),
            _int_env("SKILL_HIGH", 500),
            "skill definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/agents/*/*.md") or _glob(path, "*/agents/*.md"):
        # Both agent layouts: the FLAT agents/<name>.md Claude Code discovers,
        # and the nested agents/<name>/<name>.md a harness-bearing agent uses.
        return (
            _int_env("AGENT_WARN", 250),
            _int_env("AGENT_HIGH", 400),
            "agent definition",
            "ai-file-bloat",
        )
    if _glob(path, "*/skills/*/*.md"):
        # Skill COMPANION prose (#589) — a reference file a SKILL.md tells the
        # agent to load. MUST stay below the SKILL.md arm above, which is the
        # narrower pattern: these arms are sequential, so hoisting this one
        # would swallow every SKILL.md into the looser companion budget.
        #
        # Before this arm existed, a companion matched NOTHING here and fell
        # through to the production-LOC code thresholds (300/500) — sized by a
        # rule written for source. Exactly the defect #700 fixed for memory
        # bundles, on the repo's LARGEST prose files.
        return (
            _int_env("COMPANION_WARN", 400),
            _int_env("COMPANION_HIGH", 650),
            "skill companion",
            "ai-file-bloat",
        )
    if _glob(path, "*/docs/*.md"):
        return (
            _int_env("DOC_WARN", 500),
            _int_env("DOC_HIGH", 800),
            "documentation",
            "doc-file-bloat",
        )
    return None


# <<< shared:bloat-spec-py


def numstat_path(field: str) -> str:
    """The POST-rename path from a `git diff --numstat` path field.

    git does not print a plain path for a renamed file — it prints the rename in
    one of two shapes, and neither matches what `git diff --name-only` puts in
    the caller's file list:

        old.py => new.py          (whole path changed)
        a/{x => y}/f.py           (one path segment changed)

    Left unresolved, the sidecar is keyed by that literal arrow string, the
    lookup for the real path misses, and the file's added-count silently reads 0
    — so a renamed file can never be reported as crossing a threshold no matter
    how much the diff added to it. A rename plus a large addition is exactly when
    the size lens is worth having, and it was the one case guaranteed to be quiet.
    """
    if "=>" not in field:
        return field
    start = field.find("{")
    if start != -1:
        end = field.find("}", start)
        if end != -1:
            inner = field[start + 1 : end]
            after = inner.split("=>", 1)[1].strip() if "=>" in inner else inner
            # An empty side means the segment was dropped entirely
            # (`a/{x => }/f.py`), which collapses the duplicated separator.
            joined = field[:start] + after + field[end + 1 :]
            return joined.replace("//", "/")
    return field.split("=>", 1)[1].strip()


def read_numstat(path: str) -> dict[str, int]:
    """Added-line counts per file from a `git diff --numstat` sidecar.

    Binary files render as `-` in numstat; those rows are skipped rather than
    crashing. A missing/unreadable sidecar yields {} — which the caller treats as
    'no growth signal', NOT as 'no growth'.
    """
    counts: dict[str, int] = {}
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for row in fh:
                parts = row.rstrip("\n").split("\t")
                if len(parts) < 3:
                    continue
                added, _deleted, name = parts[0], parts[1], parts[2]
                try:
                    counts[numstat_path(name)] = int(added)
                except ValueError:
                    continue
    except OSError:
        return {}
    return counts


def scan_prose(
    path: str,
    lines: list[str],
    m: dict,
    spec: tuple[int, int, str, str],
    added: int,
    have_growth: bool,
    min_added: int,
) -> None:
    """Emit the size row for a CLASSIFIED prose file — an agent definition, a
    SKILL.md, a companion, a CLAUDE.md, a memory index/concept, a docs page
    (#724).

    Thresholds and file-type label come from the shared `bloat_spec`, so this
    lens and the audit lens can never disagree about what the file is. What
    stays this lens's own is the DISPOSITION: the audit lens grades a bloat row
    flat HIGH/MEDIUM on size alone, which for a per-PR gate would make a
    one-line touch to a pre-existing 580-line agent file blocking — precisely
    the outcome #695 AC4 exists to prevent, on the file type most likely to be
    brushed against. So the same four-way growth grading the LOC path uses
    applies here, and only `crossed`/`material` are blocking-eligible.

    MEASURED ON TOTAL LINES, matching the audit lens (#701): nothing is
    excluded, because these files are loaded WHOLE into context and every line
    is real cost.
    """
    b_warn, b_high, ftype, category = spec
    total = m["total"]
    if total <= b_warn:
        return

    # PRIOR IS EXACT HERE, not the approximation the production-LOC path needs.
    # That path subtracts raw insertions from a count that excludes blanks and
    # comments, over-subtracts, and needs a clamp to stop a whitespace-heavy
    # reformat faking a threshold crossing. This budget already counts every
    # line, and numstat already counts every inserted line, so the two are in
    # the same unit and the subtraction is the real pre-diff size. The clamp's
    # absence is deliberate, not an oversight.
    prior = max(0, total - added) if have_growth else total
    crossed = have_growth and prior <= b_warn
    material = have_growth and added >= min_added

    band = "high" if total > b_high else "warning"
    limit = b_high if total > b_high else b_warn

    if crossed:
        certainty = "HIGH" if total > b_high else "MEDIUM"
        evidence = (
            f"{ftype} exceeds {band} threshold: {total} lines (>{limit}); this "
            f"diff added {added} lines and pushed it over the {b_warn} budget"
        )
    elif material:
        certainty = "MEDIUM"
        evidence = (
            f"{ftype} exceeds {band} threshold: {total} lines (>{limit}); "
            f"already over before this diff, which added {added} more lines"
        )
    elif have_growth:
        certainty = "LOW"
        evidence = (
            f"{ftype} exceeds {band} threshold: {total} lines (>{limit}); "
            f"pre-existing size, this diff added only {added} lines — "
            f"informational, not this PR's debt"
        )
    else:
        certainty = "LOW"
        evidence = (
            f"{ftype} exceeds {band} threshold: {total} lines (>{limit}); no "
            f"diff growth data supplied — informational only"
        )

    emit(path, 1, category, evidence, certainty)

    # Prose splits by progressive disclosure, never by a line range. Emitted
    # only for the dispositions a reviewer should act on, mirroring the seam
    # rule on the LOC path — a decline row would be noise on a file whose
    # length this diff did not meaningfully change.
    if crossed or material:
        emit(
            path,
            1,
            "decomposition-seam",
            f"split shape for {ftype}: {split_shape('md')}",
            "MEDIUM",
        )


def scan_file(path: str, lines: list[str], added: int, have_growth: bool) -> None:
    """Emit sizing rows for one changed file.

    The growth disposition (AC4) is the whole point of the review lens:

      * crossed a threshold BECAUSE of this diff  -> MEDIUM/HIGH, actionable
      * already over, material growth             -> MEDIUM
      * already over, trivial growth              -> LOW, informational only
      * no growth signal at all                   -> LOW, informational only

    Only the first two are ever blocking-eligible. A one-line touch to a
    pre-existing oversized file CANNOT produce a blocking row, which is the
    property tests/validate-sizing-scanner.sh pins.
    """
    lang = lang_of(path)
    units = find_units(lines, lang)
    m = measure(lines, lang, units)
    warn, high = thresholds_for(lang)
    production = m["production"]
    min_added = _int_env("REVIEW_GROWTH_MIN_ADDED", 50)

    # --- Classified prose: its own budget, never the code one (#724/#701) ----
    # Checked BEFORE the production-LOC early return below, which would
    # otherwise swallow the whole branch: a 580-line agent definition measures
    # 501 production LOC, under the generic md warning of 700, so it returns
    # here and the file is never classified at all. That early return IS the
    # defect #724 reports, seen from the inside.
    #
    # EXACTLY ONE size verdict per file, exactly as the audit lens does it
    # (#701): a spec means "this file type has its own budget", so the generic
    # file-length row is skipped rather than emitted alongside.
    spec = bloat_spec(path)
    if spec is not None:
        scan_prose(path, lines, m, spec, added, have_growth, min_added)
        return

    if production <= warn:
        return

    # Production LOC before this diff, approximated by removing the added lines.
    #
    # THE APPROXIMATION ERRS LOW, NOT HIGH. numstat counts RAW insertions —
    # blanks and comments included — while `production` excludes them, so
    # subtracting one from the other over-subtracts and `prior` is a LOWER bound
    # on the true pre-diff size. (An earlier comment here claimed the opposite
    # and reasoned that erring high fails toward the quiet disposition; it fails
    # toward the LOUD one.) A reformat bundled with a small real change — 900
    # blank lines and 5 production lines added to an already-851-LOC file —
    # drove `prior` negative, satisfied `prior <= warn`, and produced a HIGH
    # "this diff pushed it over" on a file that was far over the threshold to
    # begin with: the loudest possible disposition for exactly the case AC4
    # exists to keep quiet.
    #
    # So `crossed` is CLAMPED: the added count cannot exceed the file's total
    # non-production content, because those lines had to go somewhere. `added`
    # minus the blanks/comments/test lines present is a floor on how many of the
    # insertions were production; anything above that floor is what the diff
    # genuinely contributed to `production`.
    #
    # For the 900-blank reformat: non_production is 900, so at most 5 of the 905
    # insertions were production, `prior` lands at 851 — the real value — and the
    # row correctly takes the quiet `material` path instead of claiming a HIGH
    # crossing. For an ordinary diff, where insertions are mostly production,
    # non_production is small and the clamp changes nothing.
    #
    # `prior` also floors at 0: a negative value can never describe a real file.
    non_production = m["total"] - production
    added_production = max(0, added - non_production)
    prior = max(0, production - added_production) if have_growth else production
    crossed = have_growth and prior <= warn
    material = have_growth and added >= min_added

    # Byte-identical to the `metrics` sprintf in the shared:loc-measure-awk
    # region, so the two impls' evidence strings agree by construction.
    metrics = (
        f"{m['total']} total, {m['comment']} comment ({m['comment_pct']}%), "
        f"{m['blank']} blank, {m['test_excluded']} test-excluded, "
        f"max nesting {m['max_depth']}, {m['units']} top-level units"
    )
    band = "high" if production > high else "warning"
    limit = high if production > high else warn

    if crossed:
        certainty = "HIGH" if production > high else "MEDIUM"
        evidence = (
            f"{production} production LOC (>{limit} {band}); this diff added "
            f"{added} lines and pushed it over the {warn} review threshold; {metrics}"
        )
    elif material:
        certainty = "MEDIUM"
        evidence = (
            f"{production} production LOC (>{limit} {band}); already over before "
            f"this diff, which added {added} more lines; {metrics}"
        )
    elif have_growth:
        certainty = "LOW"
        evidence = (
            f"{production} production LOC (>{limit} {band}); pre-existing size, "
            f"this diff added only {added} lines — informational, not this PR's "
            f"debt; {metrics}"
        )
    else:
        certainty = "LOW"
        evidence = (
            f"{production} production LOC (>{limit} {band}); no diff growth data "
            f"supplied — informational only; {metrics}"
        )

    emit(path, 1, "file-length", evidence, certainty)

    # The split SHAPE, so the finding names a concrete destination rather than
    # bare advice. Only for the dispositions a reviewer should act on.
    #
    # NO `and lang` GUARD. A file whose extension has no segmenter (.rb, .java,
    # .c, .cpp, .kt — scanned, since none are in SKIP_EXTS) yields lang == "",
    # and gating on it dropped BOTH arms: the first was false for want of a
    # language and the second false for want of a quiet disposition, so an
    # actionable over-threshold file emitted a file-length row and NO seam row —
    # silently withholding from the review dimension the one thing it consumes.
    # The generic fallback is weaker advice than a language-shaped one but it is
    # a real destination, and every blocking-eligible file now yields exactly one
    # seam row.
    # `and not is_decl_file(path)` (#726): a .d.ts has no runtime units to
    # extract, so a shape row would tell the reviewer to build a types/ dir out
    # of a file with nothing to move. It takes the decline branch instead, where
    # decline_reason names the declaration file specifically. This mirrors the
    # audit lens, which reaches the same outcome through `seams == 0` — the two
    # lenses gate on different quantities (growth vs seams), so the suppression
    # has to be stated in each rather than inherited.
    if (crossed or material) and not is_decl_file(path):
        shape = split_shape(lang)
        label = lang if lang else "this file"
        emit(
            path,
            1,
            "decomposition-seam",
            f"split shape for {label}: {shape}",
            "MEDIUM",
        )
    else:
        emit(
            path,
            1,
            "decomposition-seam",
            f"declined: {decline_reason(path, lines, m)} ({production} production LOC, "
            f"{m['units']} top-level units)",
            "LOW",
        )


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write("Usage: sizing.py <file-list> [numstat-file]\n")
        return 1
    file_list = argv[1]
    if not os.path.isfile(file_list):
        sys.stderr.write(f"Error: file list not found: {file_list}\n")
        return 1

    growth = read_numstat(argv[2]) if len(argv) > 2 else {}
    have_growth = bool(growth)

    with open(file_list, encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            path = raw.rstrip("\n")
            if not path or not os.path.isfile(path):
                continue
            low = path.lower()
            if (
                low.endswith(SKIP_EXTS)
                or low.endswith("lock.json")
                or low.endswith("go.sum")
            ):
                continue
            try:
                with open(path, encoding="utf-8", errors="replace") as src:
                    lines = src.read().split("\n")
            except OSError:
                continue
            if lines and lines[-1] == "":
                lines.pop()
            scan_file(path, lines, growth.get(path, 0), have_growth)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
