#!/usr/bin/env python3
"""ship-issue — review-lens sizing pre-scan (Python primary implementation).

The adversarial pre-PR review had no size lens — a PR could add 900 lines to an
already-oversized file and pass a clean review (issue #695). This scanner
supplies the candidates the new `decomposition` dimension judges.

WHY THIS IS NOT check-decomposition. The audit-lens scanner
(review-audit/skills/check-decomposition) answers "is this file too long?" over a
whole repo. A per-PR gate must answer a DIFFERENT question — "did THIS diff make
it worse?" — because a one-line touch to a pre-existing 1,200-line file is not
the author's debt to pay, and a reviewer that says otherwise gets turned off
within a week. So this scanner is GROWTH-AWARE: it reads a numstat sidecar and
dispositions each file by what the diff actually did to it.

The LOC-counting rules themselves are NOT re-derived. They are physically shared
with check-decomposition through `# >>> shared:loc-*` sentinel regions pinned
byte-for-byte by tests/validate-shared-scanner-sync.sh — the plugins install
independently (workflow without review-audit), so a sourced library is
impossible and a third drifting copy of the LOC rules is exactly what #663 was
filed to kill.

Python 3.11+ primary behind the language-agnostic TSV contract; the sibling
sizing.sh is the portable bash fallback (it exec's this file when a python3>=3.11
is present). Both emit byte-identical findings — parity pinned by
tests/validate-python-ports.sh, behavior by tests/validate-sizing-scanner.sh.
See CLAUDE.md § Key conventions (runtime policy).

Input:  argv[1] = file containing paths to scan (one per line)
        argv[2] = OPTIONAL numstat sidecar: `added<TAB>deleted<TAB>path` rows
                  (`git diff --numstat`). ABSENT => no growth signal, so every
                  over-threshold file is reported at LOW/informational only.
Output: TSV to stdout: file<TAB>line<TAB>category<TAB>evidence<TAB>certainty

The 5-column contract is NOT widened — it is the language boundary every
check-* skill and all three parity gates depend on.

Exit codes:
  0 = success (zero or more findings)
  1 = usage error (missing argument) or file list not found
"""

from __future__ import annotations

import os
import re
import sys

# Non-source files skipped wholesale. Mirrors check-decomposition's SKIP_GLOBS.
# Markdown is deliberately ABSENT: prose is the surface this repo feels most
# (#589), and the markdown arm carries its own progressive-disclosure guidance.
SKIP_EXTS = (
    ".lock",
    ".txt",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
)

GENERATED_RE = re.compile(
    r"@generated|Code generated by|DO NOT EDIT|autogenerated|auto-generated",
    re.IGNORECASE,
)

UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?(?:def|class)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "js": re.compile(
        r"^(?:export[ \t]+)?(?:default[ \t]+)?(?:async[ \t]+)?"
        r"(?:function|class|const|let|var)[ \t]+([A-Za-z_$][A-Za-z0-9_$]*)"
    ),
    "rs": re.compile(
        r"^(?:pub(?:\([a-z]+\))?[ \t]+)?(?:async[ \t]+)?"
        r"(?:fn|struct|enum|trait|impl|mod)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
    "go": re.compile(r"^(?:func|type|var|const)[ \t]+([A-Za-z_][A-Za-z0-9_]*)"),
    "sh": re.compile(
        r"^(?:function[ \t]+)?([A-Za-z_][A-Za-z0-9_]*)[ \t]*\([ \t]*\)|"
        r"^function[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
    ),
}

COMMENT_RE = {
    "py": re.compile(r"^[ \t]*#"),
    "sh": re.compile(r"^[ \t]*#"),
    "js": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "rs": re.compile(r"^[ \t]*(?://|/\*|\*)"),
    "go": re.compile(r"^[ \t]*(?://|/\*|\*)"),
}

TEST_UNIT_RE = {
    "py": re.compile(r"^(?:async[ \t]+)?def[ \t]+test_|^class[ \t]+Test"),
    "js": re.compile(r"^[ \t]*(?:describe|it|test)[ \t]*\("),
    "rs": re.compile(r"^[ \t]*#\[(?:cfg\(test\)|test)\]"),
    "go": re.compile(r"^func[ \t]+(?:Test|Benchmark|Fuzz|Example)"),
    "sh": re.compile(r"^(?:function[ \t]+)?test_[A-Za-z0-9_]*[ \t]*\([ \t]*\)"),
}

TEST_REGION_RE = {
    "py": re.compile(r"^if[ \t]+__name__"),
    "rs": re.compile(r"^[ \t]*#\[cfg\(test\)\]"),
    "sh": re.compile(r"^#[ \t]*-+[ \t]*tests?[ \t]*-+"),
}

# Blankness/indent by REGEX, not str.strip(): the latter is unicode-aware while
# the awk fallback under LC_ALL=C is not. Pinning both to [ \t] is what keeps the
# TSV byte-identical on a file with exotic whitespace.
BLANK_RE = re.compile(r"^[ \t]*$")
INDENT_RE = re.compile(r"^[ \t]*")

# Indent width used to convert leading whitespace into a nesting depth. Mirrors
# NEST_UNIT in check-decomposition/patterns.py and nest_unit() in the shared
# awk region, so the metrics string is byte-identical across all three.
NEST_UNIT = {"py": 4, "js": 2, "rs": 4, "go": 4, "sh": 4, "md": 2}

EXT_LANG = {
    "py": "py",
    "js": "js",
    "jsx": "js",
    "mjs": "js",
    "cjs": "js",
    "ts": "js",
    "tsx": "js",
    "rs": "rs",
    "go": "go",
    "sh": "sh",
    "bash": "sh",
    "md": "md",
    "markdown": "md",
}

# Language-shaped split guidance (AC7). Keyed by the same language keys the
# segmenters use, so advice and measurement can never disagree about what a file
# IS. Each string names the SHAPE of the split, not a generic "consider
# splitting" — the finding has to be actionable or it is noise.
SPLIT_SHAPE = {
    "rs": "new subdir module; mod.rs re-exports the decomposed units",
    "py": "package dir with __init__.py re-exporting the public surface",
    "js": "sibling modules + a barrel index.ts",
    "go": "additional files in the same package (no import churn)",
    "sh": "sourced fragment + an explicit ordered list (split-suite convention)",
    "md": (
        "progressive disclosure: move detail to linked files, leave a one-line pointer"
    ),
}

# Per-language review-lens thresholds, overriding the default pair. A 500-line
# Rust file and a 500-line shell script are not the same claim. Languages absent
# here fall through to REVIEW_LOC_WARN/HIGH — adding one is a one-line edit, and
# an unlisted language is sized rather than silently skipped.
#
# Mirrors the per_language block of check-decomposition/thresholds.yml.
PER_LANG_THRESHOLDS = {
    "sh": ("REVIEW_LOC_WARN_SH", "REVIEW_LOC_HIGH_SH", 700, 1000),
    "md": ("REVIEW_LOC_WARN_MD", "REVIEW_LOC_HIGH_MD", 700, 1000),
    "rs": ("REVIEW_LOC_WARN_RS", "REVIEW_LOC_HIGH_RS", 400, 700),
    "go": ("REVIEW_LOC_WARN_GO", "REVIEW_LOC_HIGH_GO", 400, 700),
}


def _int_env(name: str, default: int) -> int:
    """Read an integer threshold from the environment, falling back to DEFAULT.
    Mirrors _int_env across the patterns.py family and the ${VAR:-N} defaults in
    every patterns.sh, so thresholds.yml values pass through without either impl
    diverging."""
    val = os.environ.get(name, "")
    try:
        return int(val)
    except ValueError:
        return default


def emit(path: str, line_no: int, category: str, evidence: str, certainty: str) -> None:
    """Write one TSV finding row."""
    sys.stdout.write(
        "\t".join((path, str(line_no), category, evidence, certainty)) + "\n"
    )


def lang_of(path: str) -> str:
    """Language key from the file extension, or '' when unrecognized."""
    if "." not in path:
        return ""
    return EXT_LANG.get(path.rsplit(".", 1)[-1].lower(), "")


def thresholds_for(lang: str) -> tuple[int, int]:
    """The (warning, high) production-LOC pair for LANG.

    Review-lens defaults are deliberately LOOSER than the audit lens
    (check-decomposition ships 300/500): an audit sweeps a whole repo and can
    afford to nag, a per-PR gate cannot. See thresholds.yml § review_size_thresholds.
    """
    warn = _int_env("REVIEW_LOC_WARN", 500)
    high = _int_env("REVIEW_LOC_HIGH", 800)
    spec = PER_LANG_THRESHOLDS.get(lang)
    if spec is not None:
        warn_var, high_var, warn_def, high_def = spec
        warn = _int_env(warn_var, warn_def)
        high = _int_env(high_var, high_def)
    return warn, high


def find_units(lines: list[str], lang: str) -> list[tuple[str, int, int, bool]]:
    """Top-level units as (name, start, end, is_test), each spanning from its
    header line to the line before the next header (or EOF).

    For markdown, 'top-level' means the shallowest heading depth present, so a
    doc whose sections are all `##` segments by `##` rather than by a lone `#`.
    """
    raw: list[tuple[str, int, bool]] = []
    if lang == "md":
        heads: list[tuple[int, int]] = []
        fenced = False
        for idx, line in enumerate(lines, start=1):
            if line.startswith("```") or line.startswith("~~~"):
                fenced = not fenced
                continue
            if fenced:
                continue
            m = re.match(r"^(#{1,6})[ \t]+(.*)$", line)
            if m:
                heads.append((len(m.group(1)), idx))
        if not heads:
            return []
        top = min(h[0] for h in heads)
        for depth, line_no in heads:
            if depth == top:
                raw.append(("section", line_no, False))
    else:
        rx = UNIT_RE.get(lang)
        if rx is None:
            return []
        test_rx = TEST_UNIT_RE.get(lang)
        pending_test = False
        for idx, line in enumerate(lines, start=1):
            # A Rust attribute line marks the NEXT unit as test code.
            if lang == "rs" and test_rx is not None and test_rx.search(line):
                pending_test = True
                continue
            m = rx.match(line)
            if not m:
                continue
            name = m.group(1)
            if not name and m.lastindex and m.lastindex >= 2:
                name = m.group(2)
            if not name:
                continue
            is_test = False
            if pending_test:
                is_test = True
                pending_test = False
            elif test_rx is not None and lang != "rs" and test_rx.search(line):
                is_test = True
            raw.append((name, idx, is_test))

    out: list[tuple[str, int, int, bool]] = []
    for i, (name, start, is_test) in enumerate(raw):
        end = raw[i + 1][1] - 1 if i + 1 < len(raw) else len(lines)
        out.append((name, start, end, is_test))
    return out


def measure(
    lines: list[str], lang: str, units: list[tuple[str, int, int, bool]]
) -> dict:
    """The generic sizing layer: total / blank / comment / test-excluded /
    production LOC and top-level unit count. Byte-equivalent to
    check-decomposition's `measure` — the shared:loc-measure-awk region is the
    same computation transcribed into awk."""
    total = len(lines)
    comment_rx = COMMENT_RE.get(lang)
    region_rx = TEST_REGION_RE.get(lang)

    test_lines: set[int] = set()
    for _name, start, end, is_test in units:
        if is_test:
            test_lines.update(range(start, end + 1))
    if region_rx is not None:
        for idx, line in enumerate(lines, start=1):
            if region_rx.search(line):
                test_lines.update(range(idx, total + 1))
                break

    blank = 0
    comment = 0
    test_excluded = 0
    max_depth = 0
    nest_unit = NEST_UNIT.get(lang, 4)
    for idx, line in enumerate(lines, start=1):
        if idx in test_lines:
            test_excluded += 1
            continue
        if BLANK_RE.match(line):
            blank += 1
            continue
        if comment_rx is not None and comment_rx.match(line):
            comment += 1
            continue
        depth = len(INDENT_RE.match(line).group(0)) // nest_unit
        if depth > max_depth:
            max_depth = depth

    production = total - blank - comment - test_excluded
    return {
        "total": total,
        "blank": blank,
        "comment": comment,
        "test_excluded": test_excluded,
        "production": production,
        "max_depth": max_depth,
        "units": len([u for u in units if not u[3]]),
        "comment_pct": (comment * 100 // total) if total else 0,
    }


def decline_reason(lines: list[str], m: dict) -> str:
    """WHY a long file was not flagged as splittable.

    A decline is a RESULT, not a silence — silence is indistinguishable from
    'not examined', and the recorded reason is what a reviewer cites when
    accepting the length. Reasons are reused verbatim from
    check-decomposition/contract.md so a decline reads identically in both lenses.
    """
    for line in lines[:20]:
        if GENERATED_RE.search(line):
            return "generated file — regenerate rather than split"
    if m["units"] <= _int_env("REVIEW_COHESIVE_MAX_UNITS", 2):
        return "single cohesive unit — no internal seam to cut"
    if m["comment_pct"] >= 50:
        return "majority prose/comment — length is documentation, not logic"
    return "no low-coupling seam found — units are mutually referential"


def read_numstat(path: str) -> dict[str, int]:
    """Added-line counts per file from a `git diff --numstat` sidecar.

    Binary files render as `-` in numstat; those rows are skipped rather than
    crashing. A missing/unreadable sidecar yields {} — which the caller treats as
    'no growth signal', NOT as 'no growth'.
    """
    counts: dict[str, int] = {}
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for row in fh:
                parts = row.rstrip("\n").split("\t")
                if len(parts) < 3:
                    continue
                added, _deleted, name = parts[0], parts[1], parts[2]
                try:
                    counts[name] = int(added)
                except ValueError:
                    continue
    except OSError:
        return {}
    return counts


def scan_file(path: str, lines: list[str], added: int, have_growth: bool) -> None:
    """Emit sizing rows for one changed file.

    The growth disposition (AC4) is the whole point of the review lens:

      * crossed a threshold BECAUSE of this diff  -> MEDIUM/HIGH, actionable
      * already over, material growth             -> MEDIUM
      * already over, trivial growth              -> LOW, informational only
      * no growth signal at all                   -> LOW, informational only

    Only the first two are ever blocking-eligible. A one-line touch to a
    pre-existing oversized file CANNOT produce a blocking row, which is the
    property tests/validate-sizing-scanner.sh pins.
    """
    lang = lang_of(path)
    units = find_units(lines, lang)
    m = measure(lines, lang, units)
    warn, high = thresholds_for(lang)
    production = m["production"]

    if production <= warn:
        return

    min_added = _int_env("REVIEW_GROWTH_MIN_ADDED", 50)
    # Production LOC before this diff, approximated by removing the added lines.
    # An approximation is honest here: numstat counts raw added lines while
    # `production` excludes blanks/comments, so `prior` is an UPPER bound on the
    # pre-diff size. Erring high means we under-claim "the diff crossed it",
    # which fails toward the quieter, non-blocking disposition.
    prior = production - added if have_growth else production
    crossed = have_growth and prior <= warn
    material = have_growth and added >= min_added

    # Byte-identical to the `metrics` sprintf in the shared:loc-measure-awk
    # region, so the two impls' evidence strings agree by construction.
    metrics = (
        f"{m['total']} total, {m['comment']} comment ({m['comment_pct']}%), "
        f"{m['blank']} blank, {m['test_excluded']} test-excluded, "
        f"max nesting {m['max_depth']}, {m['units']} top-level units"
    )
    band = "high" if production > high else "warning"
    limit = high if production > high else warn

    if crossed:
        certainty = "HIGH" if production > high else "MEDIUM"
        evidence = (
            f"{production} production LOC (>{limit} {band}); this diff added "
            f"{added} lines and pushed it over the {warn} review threshold; {metrics}"
        )
    elif material:
        certainty = "MEDIUM"
        evidence = (
            f"{production} production LOC (>{limit} {band}); already over before "
            f"this diff, which added {added} more lines; {metrics}"
        )
    elif have_growth:
        certainty = "LOW"
        evidence = (
            f"{production} production LOC (>{limit} {band}); pre-existing size, "
            f"this diff added only {added} lines — informational, not this PR's "
            f"debt; {metrics}"
        )
    else:
        certainty = "LOW"
        evidence = (
            f"{production} production LOC (>{limit} {band}); no diff growth data "
            f"supplied — informational only; {metrics}"
        )

    emit(path, 1, "file-length", evidence, certainty)

    # The split SHAPE, so the finding names a concrete destination rather than
    # bare advice. Only for the dispositions a reviewer should act on.
    if (crossed or material) and lang:
        shape = SPLIT_SHAPE.get(lang, "extract a cohesive unit into a sibling module")
        emit(
            path,
            1,
            "decomposition-seam",
            f"split shape for {lang}: {shape}",
            "MEDIUM",
        )
    elif not (crossed or material):
        emit(
            path,
            1,
            "decomposition-seam",
            f"declined: {decline_reason(lines, m)} ({production} production LOC, "
            f"{m['units']} top-level units)",
            "LOW",
        )


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        sys.stderr.write("Usage: sizing.py <file-list> [numstat-file]\n")
        return 1
    file_list = argv[1]
    if not os.path.isfile(file_list):
        sys.stderr.write(f"Error: file list not found: {file_list}\n")
        return 1

    growth = read_numstat(argv[2]) if len(argv) > 2 else {}
    have_growth = bool(growth)

    with open(file_list, encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            path = raw.rstrip("\n")
            if not path or not os.path.isfile(path):
                continue
            low = path.lower()
            if (
                low.endswith(SKIP_EXTS)
                or low.endswith("lock.json")
                or low.endswith("go.sum")
            ):
                continue
            try:
                with open(path, encoding="utf-8", errors="replace") as src:
                    lines = src.read().split("\n")
            except OSError:
                continue
            if lines and lines[-1] == "":
                lines.pop()
            scan_file(path, lines, growth.get(path, 0), have_growth)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
