# shellcheck shell=bash
# check-decomposition corpus — python coverage fixtures (issue #663).
#
# Drives every segmenter (Python, JS/TS, Rust, Go, Shell, Markdown), the bloat
# arms migrated here from check-ai-config, the god-module arm, and all three
# decline reasons under measurement.
#
# Sourced by tests/coverage-python.sh, which creates WORKDIR and its EXIT trap
# BEFORE this file. This fragment only BUILDS FIXTURES and exports the path-list
# variables the driver section then feeds to the port under `coverage run`.
#
# NOTE: unlike the tests/ fragments, nothing here asserts — coverage-python.sh is
# a Codecov driver, not a test suite. The behavioural gate for these same
# detectors is tests/validate-decomposition-detectors.sh, and this corpus is kept
# in lockstep with it.

# The path-list / fixture-path variables below are the corpus's EXPORT surface:
# they are read by the driver loop in tests/coverage-python.sh, which sources
# this file. shellcheck analyses one file at a time and so cannot see those uses.
# shellcheck disable=SC2034  # consumed by the driver in tests/coverage-python.sh

DECOMPDIR="$WORKDIR/decomposition"
mkdir -p "$DECOMPDIR/skills/big" "$DECOMPDIR/agents/nested" "$DECOMPDIR/docs"

# --- Python: def-family seam + test-unit exclusion + if __name__ region -------
cat >"$DECOMPDIR/mod.py" <<'EOF'
def main_entry(x):
    return parse_entry(x)

def parse_entry(s):
    return parse_header(s)

def parse_header(s):
    out = []
    for line in s.splitlines():
        out.append(line)
    return out

def parse_body(s):
    return [ln.strip() for ln in s.splitlines()]

def test_parse_entry():
    assert parse_entry("x")

if __name__ == "__main__":
    main_entry("x")
EOF

# --- JS/TS: camelCase family + the describe() test-unit arm -------------------
cat >"$DECOMPDIR/app.ts" <<'EOF'
export function mainEntry(x: string) {
  return renderHeader(x);
}

export function renderHeader(x: string) {
  const a = 1;
  return x + a;
}

export function renderBody(x: string) {
  const b = 2;
  return x + b;
}

export function renderFooter(x: string) {
  return x;
}
EOF

cat >"$DECOMPDIR/app.test.ts" <<'EOF'
describe('a', () => {
  it('b', () => { expect(1).toBe(1); });
  it('c', () => { expect(2).toBe(2); });
});
EOF

# --- Rust: fn-family seam + the #[cfg(test)] region arm ----------------------
cat >"$DECOMPDIR/parser.rs" <<'EOF'
pub fn main_entry(input: &str) -> Result<Doc> {
    let e = parse_entry(input)?;
    Ok(Doc::from(e))
}

pub fn parse_entry(s: &str) -> Result<Entry> {
    Ok(Entry { h: parse_header(s)? })
}

fn parse_header(s: &str) -> Result<Header> {
    let mut out = Header::default();
    for line in s.lines() { out.push(line); }
    Ok(out)
}

fn parse_body(s: &str) -> Result<Body> {
    Ok(Body::default())
}

#[cfg(test)]
mod tests {
    #[test]
    fn t() { assert!(true); }
}
EOF

# --- Go: func-family seam + the func Test exclusion arm ----------------------
cat >"$DECOMPDIR/app.go" <<'EOF'
package main

func MainEntry(s string) string {
	return handleRequest(s)
}

func handleRequest(s string) string {
	return s + "a"
}

func handleResponse(s string) string {
	return s + "b"
}

func handleError(s string) string {
	return s + "c"
}

func TestMainEntry(t *testing.T) {
	MainEntry("x")
}
EOF

# --- Shell: function-family seam + the test-region marker arm ----------------
cat >"$DECOMPDIR/tool.sh" <<'EOF'
#!/usr/bin/env bash
main_entry() {
    render_header "$1"
}

render_header() {
    printf 'h\n'
}

render_body() {
    printf 'b\n'
}

render_footer() {
    printf 'f\n'
}

# --- tests ---
test_render_header() {
    render_header x
}
EOF

# --- Markdown: heading-cluster seam + the fenced-block skip arm --------------
cat >"$DECOMPDIR/guide.md" <<'EOF'
## Overview

Text.

```bash
# not_a_heading
```

## Install on Linux

Steps.

## Install on Mac

Steps.

## Install on Windows

Steps.
EOF

# --- Decline arms: generated, single cohesive unit, mutually referential ------
cat >"$DECOMPDIR/table.py" <<'EOF'
# @generated by codegen; DO NOT EDIT
LOOKUP = {
    "a": 1,
    "b": 2,
    "c": 3,
    "d": 4,
}
EOF

cat >"$DECOMPDIR/single.py" <<'EOF'
class OneBigThing:
    def a(self):
        return 1
    def b(self):
        return 2
    def c(self):
        return 3
EOF

cat >"$DECOMPDIR/web.go" <<'EOF'
package main

func Alpha(s string) string {
	return Beta(s)
}

func Beta(s string) string {
	return Gamma(s)
}

func Gamma(s string) string {
	return s
}
EOF

# --- god-module: 15 units across 3 concern families --------------------------
: >"$DECOMPDIR/god.py"
for _i in 1 2 3 4 5; do
    printf 'def parse_%s(x):\n    return x\n\n' "$_i" >>"$DECOMPDIR/god.py"
done
for _i in 1 2 3 4 5; do
    printf 'def render_%s(x):\n    return x\n\n' "$_i" >>"$DECOMPDIR/god.py"
done
for _i in 1 2 3 4 5; do
    printf 'def store_%s(x):\n    return x\n\n' "$_i" >>"$DECOMPDIR/god.py"
done
unset _i

# --- Bloat arms (migrated from check-ai-config by #663) ----------------------
# Each file type routes to its own threshold family; the driver tunes the
# thresholds down so these tiny fixtures trip both the warn and high branches.
printf '%s\n' l1 l2 l3 l4 l5 >"$DECOMPDIR/CLAUDE.md"
printf '%s\n' '---' 'description: d' '---' '## Workflow' a b c >"$DECOMPDIR/skills/big/SKILL.md"
printf '%s\n' l1 l2 l3 l4 l5 >"$DECOMPDIR/agents/rev.md"
printf '%s\n' l1 l2 l3 l4 l5 >"$DECOMPDIR/agents/nested/nested.md"
printf '%s\n' l1 l2 l3 l4 l5 >"$DECOMPDIR/docs/guide.md"

# --- Skip globs + unknown extension (metrics-only, no segmenter) -------------
printf '%s\n' '{"a": 1}' >"$DECOMPDIR/package-lock.json"
printf '%s\n' 'plain data' >"$DECOMPDIR/notes.txt"
printf '%s\n' 'x' 'y' 'z' >"$DECOMPDIR/README"

# An unreadable source file drives the per-file open() OSError arm.
DECOMP_UNREAD="$DECOMPDIR/unreadable.py"
printf '%s\n' 'def a(): pass' >"$DECOMP_UNREAD"
chmod 000 "$DECOMP_UNREAD" 2>/dev/null || true

DECOMP_LIST="$WORKDIR/decomposition-list.txt"
: >"$DECOMP_LIST"
for f in "$DECOMPDIR"/mod.py "$DECOMPDIR"/app.ts "$DECOMPDIR"/app.test.ts \
    "$DECOMPDIR"/parser.rs "$DECOMPDIR"/app.go "$DECOMPDIR"/tool.sh \
    "$DECOMPDIR"/guide.md "$DECOMPDIR"/table.py "$DECOMPDIR"/single.py \
    "$DECOMPDIR"/web.go "$DECOMPDIR"/god.py \
    "$DECOMPDIR"/CLAUDE.md "$DECOMPDIR"/skills/big/SKILL.md \
    "$DECOMPDIR"/agents/rev.md "$DECOMPDIR"/agents/nested/nested.md \
    "$DECOMPDIR"/docs/guide.md \
    "$DECOMPDIR"/package-lock.json "$DECOMPDIR"/notes.txt "$DECOMPDIR"/README \
    "$DECOMP_UNREAD"; do
    printf '%s\n' "$f" >>"$DECOMP_LIST"
done
# A blank line drives the main() empty-path `if not path: continue` arm.
printf '\n' >>"$DECOMP_LIST"

# A file-list PATH that itself does not exist drives the file-list-not-found arm.
DECOMP_NOFILE_LIST="$WORKDIR/decomposition-nonexistent-list-XYZ.txt"
